with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:1900px;position:relative;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2K000000000000EBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:960px;top:377px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:960px;top:395px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:967px;top:385px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:960px;top:403px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:1746px;top:173px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:1746px;top:164px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:958px;top:319px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:958px;top:337px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:1618px;top:556px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:1495px;top:556px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:1373px;top:556px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:1251px;top:556px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:911px;top:338px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:911px;top:320px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:911px;top:303px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:838px;top:399px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:838px;top:408px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹25−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:838px;top:416px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹28−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:916px;top:416px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹28−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:916px;top:408px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹25−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:916px;top:399px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:988px;top:504px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:988px;top:513px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹25−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:988px;top:522px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹28−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:599px;top:734px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:595px;top:879px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:595px;top:879px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:240px;top:156px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹28−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:249px;top:206px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:40px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:1838px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:947px;top:279px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:943px;top:250px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:1601px;top:385px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:1481px;top:385px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:1358px;top:385px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:1236px;top:385px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:1053px;top:396px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:997px;top:535px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:925px;top:429px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:847px;top:440px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:504px;top:470px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:408px;top:501px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:467px;top:501px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:463px;top:753px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>STARTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:326px;top:470px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:1693px;top:159px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:1644px;top:345px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:1690px;top:199px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:1669px;top:200px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:1669px;top:191px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:1653px;top:256px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:1187px;top:159px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:1104px;top:234px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:1103px;top:356px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:1119px;top:191px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:1119px;top:200px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:1140px;top:199px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:1041px;top:430px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹24−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:1041px;top:421px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:1375px;top:364px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM ‹24−B, C› ‹27−B, C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:1278px;top:484px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:1232px;top:739px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:1271px;top:720px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:1222px;top:423px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:1400px;top:484px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:1354px;top:739px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:1394px;top:720px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:1345px;top:423px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:1522px;top:484px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:1477px;top:739px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:1516px;top:720px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:1466px;top:423px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:1644px;top:484px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:1599px;top:739px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:1638px;top:720px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:1598px;top:423px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:1048px;top:356px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:1228px;top:879px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:1228px;top:879px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:1094px;top:423px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:1718px;top:182px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*3 : K20A9 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:1718px;top:191px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*4 : D17A2 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:345px;top:368px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G201*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:345px;top:376px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G301*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:784px;top:178px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:826px;top:177px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:526px;top:129px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:598px;top:589px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:71px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Battery, Starting System, Charging System, Ignition System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:214px;top:501px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:321px;top:115px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:296px;top:117px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:296px;top:108px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:1815px;top:77px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:1771px;top:79px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:1721px;top:112px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:1721px;top:134px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:481px;top:446px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:688px;top:123px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:214px;top:68px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:1718px;top:164px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*1 : Under−hood fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:1718px;top:173px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*2 : Under−dash fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:693px;top:306px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:1813px;top:144px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:1771px;top:145px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:349px;top:289px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:476px;top:139px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:826px;top:155px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:598px;top:445px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:255px;top:501px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:232px;top:631px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:285px;top:753px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>STARTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:882px;top:306px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:487px;top:129px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:982px;top:567px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:832px;top:501px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:911px;top:500px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:874px;top:501px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:699px;top:787px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:751px;top:619px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RECTIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:841px;top:590px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>VOLTAGE REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:598px;top:306px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:340px;top:229px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ELD UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:138px;top:501px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:563px;top:92px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:240px;top:147px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>‹25−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:1771px;top:134px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:1771px;top:123px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:1771px;top:112px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:1771px;top:68px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:784px;top:156px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.8 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:1721px;top:123px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:138px;top:879px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:438px;top:223px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:240px;top:138px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:253px;top:168px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:687px;top:134px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:688px;top:112px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:605px;top:140px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:605px;top:129px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:605px;top:118px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:605px;top:106px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:564px;top:120px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:421px;top:139px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:146px;top:48px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:621px;top:381px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>STARTER <br>CUT <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:621px;top:653px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>CLUTCH <br>SWITCH <br>(On : <br>Pedal Pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:919px;top:303px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>PRIMARY O<sub>2</sub>  SENSOR*<sup>4</sup> <br>‹28−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:919px;top:320px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>EVAP CANISTER PURGE <br>VALVE ‹25−A› ‹28−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:919px;top:338px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>REVERSE LOCKOUT <br>SOLENOID*<sup>3</sup>      ‹25−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:1132px;top:298px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IGNITION <br>COIL <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:1677px;top:798px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>SPARK <br>PLUGS<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}