with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00B44100036411KBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:88px;top:34px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:173px;top:240px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>07GAF-SD40200<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:369px;top:33px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:1px;top:211px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>0 °±3 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:410px;top:210px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>0 °±3 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:243px;top:191px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:56px;top:173px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:139px;top:174px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:49px;top:90px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Press<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:57px;top:276px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:395px;top:175px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:278px;top:176px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:227px;top:121px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Press<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:377px;top:90px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Press<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:311px;top:276px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}