with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:475px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2K000000000000EBA912.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:138px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:360px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:582px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:804px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:861px;top:82px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:861px;top:86px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:482px;top:387px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:487px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:127px;top:82px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:127px;top:86px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:882px;top:73px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.14 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:904px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:859px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:859px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:83px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:83px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:651px;top:147px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:755px;top:234px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:798px;top:144px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:796px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:823px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:881px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:673px;top:336px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:673px;top:391px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:672px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:798px;top:391px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:846px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:848px;top:391px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:697px;top:236px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:720px;top:236px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:714px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:687px;top:308px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:673px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:728px;top:308px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR WINDOW WIPER INTERMITTENT CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:798px;top:178px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:823px;top:178px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:712px;top:178px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:665px;top:178px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:750px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:775px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:537px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:541px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>59<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:329px;top:451px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G302 : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:859px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:859px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:859px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:859px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:82px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:83px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:83px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:82px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:919px;top:18px;font-weight:normal;font-size:8.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:11px;top:17px;font-weight:normal;font-size:8.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:478px;top:388px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:454px;top:388px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.31 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:905px;top:77px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:882px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.18 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:38px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.18 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:62px;top:77px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:62px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:40px;top:73px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.14 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:62px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:32px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:40px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:62px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:911px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:882px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:904px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:882px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:482px;top:169px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:486px;top:453px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G203*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:235px;top:97px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:35px;top:27px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>With Auto Wiper<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:840px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*4 : D17A2 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:840px;top:95px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*3 : K20A9 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:840px;top:91px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2 : Under−dash fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:840px;top:86px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1 : Under−hood fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:224px;top:97px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:224px;top:92px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:482px;top:125px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:266px;top:125px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:216px;top:114px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:301px;top:169px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:368px;top:272px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:487px;top:422px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:486px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G301*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:423px;top:394px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:418px;top:275px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:423px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:412px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:393px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:393px;top:275px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:492px;top:275px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:467px;top:275px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:467px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:498px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:462px;top:228px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:335px;top:422px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:329px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G201 : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:340px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:339px;top:338px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:324px;top:376px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>As<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:368px;top:322px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:368px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:301px;top:291px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:384px;top:394px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:565px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:565px;top:217px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:565px;top:394px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DWELL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:565px;top:228px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:565px;top:195px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:582px;top:422px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:580px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:540px;top:228px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:498px;top:228px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:512px;top:394px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:540px;top:394px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:571px;top:173px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RAIN SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:512px;top:355px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:543px;top:355px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:510px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:543px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:540px;top:217px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:462px;top:217px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:501px;top:217px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:502px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:462px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:540px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:216px;top:422px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:214px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:143px;top:422px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:142px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G481<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:212px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:71px;top:241px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:215px;top:242px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:176px;top:241px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:82px;top:242px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:63px;top:143px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WINDSHIELD WIPER/WASHER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:139px;top:183px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:127px;top:192px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:92px;top:183px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MIST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:116px;top:196px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:104px;top:192px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:216px;top:136px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:143px;top:242px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:120px;top:242px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:160px;top:242px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:265px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:238px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:35px;top:11px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>Wipers/Washers<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:904px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:882px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:882px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:882px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:882px;top:34px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:60px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:58px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:58px;top:34px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:40px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:62px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:227px;top:191px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:188px;top:216px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INTERMITTENT <br>DWELL TIME <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:227px;top:382px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:327px;top:304px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WINDSHIELD <br>WIPER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:435px;top:290px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WINDSHIELD <br>WIPER <br>HI/LO RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:510px;top:290px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUTO <br>WIPER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:534px;top:282px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>CONTROL <br>UNIT <br>‹14−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:749px;top:212px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BACK−UP <br>LIGHT <br>SWITCH <br>‹7−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:685px;top:357px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR <br>WINDOW <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:846px;top:182px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR WINDOW <br>WIPER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:618px;top:213px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR WINDOW <br>WIPER/WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}