with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:655px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:655px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00D10600012345KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:655px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:339px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To left-rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:443px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To right-rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:255px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To right-front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:503px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To left-front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:375px;top:394px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:359px;top:456px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:623px;top:553px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:680px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLARE NUTS<br>15 N·m <br>(1.5 kgf·m, 11 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:610px;top:392px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 mm NUT<br>9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:456px;top:612px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 mm BOLT<br>9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:229px;top:163px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}