with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:1108px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E2KJ20100000000LEA290.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:132px;top:1013px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT t<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:128px;top:973px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT u<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:143px;top:921px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT v<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:65px;top:422px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT x<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:266px;top:1059px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT y<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:282px;top:1032px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:598px;top:933px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT y1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:295px;top:1005px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:326px;top:940px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:348px;top:896px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:338px;top:918px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:358px;top:873px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:455px;top:1024px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:488px;top:960px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:474px;top:989px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:507px;top:934px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT z9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:669px;top:881px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT y3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:629px;top:757px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT y4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:621px;top:516px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT y5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:442px;top:395px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT y2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:27px;top:337px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2526 (99.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:34px;top:323px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2585 (101.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:40px;top:310px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2601 (102.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:47px;top:296px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2605 (102.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:54px;top:282px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2883 (113.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:61px;top:268px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2890 (113.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:68px;top:255px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>3001 (118.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:75px;top:241px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>3030 (119.3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:318px;top:145px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>Rear damper center 68 x 73 (2.7 x 2.9) Slot<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:26px;top:95px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>x<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:26px;top:71px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>w<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:26px;top:44px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>v<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:61px;top:45px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:26px;top:120px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>y<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:26px;top:145px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:61px;top:145px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:26px;top:170px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:61px;top:170px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:61px;top:70px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:61px;top:95px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:61px;top:120px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:26px;top:195px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:61px;top:195px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ12 (0.47)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:283px;top:70px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:283px;top:95px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:283px;top:120px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:283px;top:145px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:283px;top:170px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:283px;top:195px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:283px;top:45px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>z3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:318px;top:70px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For trailing arm φ30 (1.18)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:318px;top:46px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:318px;top:95px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For trailing arm φ30 (1.18)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:318px;top:120px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:318px;top:170px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For rear cross beam φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:318px;top:195px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole right φ15 (0.59), left φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:629px;top:70px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>y2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:629px;top:95px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>y3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:629px;top:120px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>y4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:629px;top:145px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>y5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:629px;top:46px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>y1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:664px;top:46px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For rear cross beam φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:664px;top:70px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For rear cross beam φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:664px;top:95px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:664px;top:120px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:664px;top:145px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ50 (1.97)<br></b></nobr>");
write("</p>");
write("</div>");
write("<svg id=\"bl2_1\" class=\"drag\" style=\"position:absolute; left:11px; top:548px; width:4px; height:100px; overflow:visible;\"><line x1=\"1\" y1=\"98\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_1\" class=\"drag\" on=\"true\" string=\"518 (20.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_2\" class=\"drag\" style=\"position:absolute; left:31px; top:548px; width:4px; height:100px; overflow:visible;\"><line x1=\"1\" y1=\"98\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_2\" class=\"drag\" on=\"true\" string=\"828 (32.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_3\" class=\"drag\" style=\"position:absolute; left:50px; top:549px; width:4px; height:99px; overflow:visible;\"><line x1=\"1\" y1=\"97\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_3\" class=\"drag\" on=\"true\" string=\"510 (20.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_4\" class=\"drag\" style=\"position:absolute; left:129px; top:536px; width:4px; height:111px; overflow:visible;\"><line x1=\"1\" y1=\"109\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_4\" class=\"drag\" on=\"true\" string=\"1080 (42.52)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_5\" class=\"drag\" style=\"position:absolute; left:154px; top:660px; width:4px; height:77px; overflow:visible;\"><line x1=\"1\" y1=\"75\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_5\" class=\"drag\" on=\"true\" string=\"320 (12.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_6\" class=\"drag\" style=\"position:absolute; left:153px; top:548px; width:4px; height:85px; overflow:visible;\"><line x1=\"1\" y1=\"83\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_6\" class=\"drag\" on=\"true\" string=\"330 (13.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_7\" class=\"drag\" style=\"position:absolute; left:248px; top:576px; width:4px; height:101px; overflow:visible;\"><line x1=\"1\" y1=\"99\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_7\" class=\"drag\" on=\"true\" string=\"650 (25.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_8\" class=\"drag\" style=\"position:absolute; left:267px; top:538px; width:4px; height:109px; overflow:visible;\"><line x1=\"1\" y1=\"107\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_8\" class=\"drag\" on=\"true\" string=\"1215 (47.83)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_9\" class=\"drag\" style=\"position:absolute; left:296px; top:577px; width:4px; height:99px; overflow:visible;\"><line x1=\"1\" y1=\"97\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_9\" class=\"drag\" on=\"true\" string=\"305 (12.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_10\" class=\"drag\" style=\"position:absolute; left:353px; top:502px; width:4px; height:145px; overflow:visible;\"><line x1=\"1\" y1=\"143\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_10\" class=\"drag\" on=\"true\" string=\"1056 (41.57)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_11\" class=\"drag\" style=\"position:absolute; left:378px; top:544px; width:4px; height:103px; overflow:visible;\"><line x1=\"1\" y1=\"101\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_11\" class=\"drag\" on=\"true\" string=\"940 (37.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_12\" class=\"drag\" style=\"position:absolute; left:464px; top:631px; width:4px; height:82px; overflow:visible;\"><line x1=\"1\" y1=\"80\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_12\" class=\"drag\" on=\"true\" string=\"200 (7.78)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_13\" class=\"drag\" style=\"position:absolute; left:465px; top:519px; width:4px; height:86px; overflow:visible;\"><line x1=\"1\" y1=\"84\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_13\" class=\"drag\" on=\"true\" string=\"150 (5.91)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_14\" class=\"drag\" style=\"position:absolute; left:483px; top:542px; width:4px; height:105px; overflow:visible;\"><line x1=\"1\" y1=\"103\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_14\" class=\"drag\" on=\"true\" string=\"800 (31.5)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_15\" class=\"drag\" style=\"position:absolute; left:499px; top:538px; width:4px; height:109px; overflow:visible;\"><line x1=\"1\" y1=\"107\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_15\" class=\"drag\" on=\"true\" string=\"1140 (44.88)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_16\" class=\"drag\" style=\"position:absolute; left:678px; top:635px; width:4px; height:65px; overflow:visible;\"><line x1=\"1\" y1=\"63\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_16\" class=\"drag\" on=\"true\" string=\"60 (2.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_17\" class=\"drag\" style=\"position:absolute; left:695px; top:630px; width:4px; height:84px; overflow:visible;\"><line x1=\"1\" y1=\"82\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_17\" class=\"drag\" on=\"true\" string=\"220 (8.66)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_18\" class=\"drag\" style=\"position:absolute; left:697px; top:529px; width:4px; height:80px; overflow:visible;\"><line x1=\"1\" y1=\"78\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_18\" class=\"drag\" on=\"true\" string=\"135 (5.31)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_19\" class=\"drag\" style=\"position:absolute; left:715px; top:548px; width:4px; height:100px; overflow:visible;\"><line x1=\"1\" y1=\"98\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_19\" class=\"drag\" on=\"true\" string=\"1020 (40.16)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl2_20\" class=\"drag\" style=\"position:absolute; left:734px; top:546px; width:4px; height:101px; overflow:visible;\"><line x1=\"1\" y1=\"99\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_20\" class=\"drag\" on=\"true\" string=\"1045 (41.14)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</div>");
}