with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:952px; height:1023px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:952px;position:relative;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R51100000000YDAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:779px;top:15px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>TAILGATE FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:202px;top:89px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>HOOD FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:49px;top:264px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>HOOD HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:595px;top:887px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>FRONT DOOR PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:480px;top:948px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>DOOR HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:255px;top:988px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>FRONT FENDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:83px;top:750px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>FRONT LOWER<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:261px;top:750px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>WHEELHOUSE<br>UPPER MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:354px;top:719px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>OUTRIGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:454px;top:656px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>SIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:751px;top:413px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>REAR WHEEL ARCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:335px;top:184px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>REAR FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:446px;top:144px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>REAR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:37px;top:345px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>FLOOR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:29px;top:419px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>DASHBOARD UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:36px;top:487px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>FRONT SIDE<br>FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:524px;top:113px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>TAILGATE HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:576px;top:587px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>CENTER PILLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:390px;top:693px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>FRONT PILLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:827px;top:704px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>REAR DOOR<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:730px;top:778px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>DOOR HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:609px;top:241px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>REAR FLOOR STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:695px;top:321px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>JACK-UP STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:82px;top:19px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b></b>Indicates anti-rust agents.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}