with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:475px;position:relative;height:320px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E00H46200053401MAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:244px;top:149px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>24 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:193px;top:84px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:157px;top:104px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:240px;top:210px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:189px;top:172px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:298px;top:45px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:300px;top:75px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:389px;top:45px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:386px;top:76px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:102px;top:258px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:328px;top:257px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:37px;top:96px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}