with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:336px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:336px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E1JE34150339125KBAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:336px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:344px;top:29px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:376px;top:306px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:82px;top:192px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:442px;top:298px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:50px;top:103px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:89px;top:37px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:151px;top:121px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:184px;top:88px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}