with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:527px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:527px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E21A20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:527px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:423px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:446px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:473px;top:30px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:501px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:528px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:552px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:805px;top:121px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:807px;top:164px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:806px;top:201px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:806px;top:268px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:619px;top:480px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:537px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:332px;top:493px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:300px;top:493px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:265px;top:492px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:231px;top:487px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:195px;top:479px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:163px;top:461px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:267px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:398px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:603px;top:23px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}