with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E25A18224000000KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:395px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>59 N·m <br>(6.0 kgf·m, 43 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:176px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE ENGINE MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:464px;top:148px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m <br>(6.5 kgf·m, 47 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:158px;top:774px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:633px;top:194px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:17px;top:1030px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m (6.5 kgf·m, 47 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:727px;top:535px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m <br>(6.5 kgf·m, 47 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:16px;top:714px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m <br>(6.5 kgf·m, 47 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}