with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:640px;position:relative;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E2K000000000000EBA209.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:297px;top:623px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:294px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:628px;top:170px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(With ultrasonic)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:639px;top:220px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ALARM CONTROL SIREN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:616px;top:594px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:571px;top:594px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:616px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:618px;top:667px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:526px;top:616px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:530px;top:667px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:471px;top:903px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501 : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:471px;top:894px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G502 : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:483px;top:782px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:350px;top:782px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:346px;top:894px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:574px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:565px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:530px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:527px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:485px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:483px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:441px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:437px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:394px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:349px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:352px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:186px;top:667px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:165px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:165px;top:727px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:165px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:165px;top:754px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:165px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:183px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:227px;top:594px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:183px;top:594px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:120px;top:667px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:116px;top:616px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:304px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:164px;top:218px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:162px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:161px;top:250px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:161px;top:283px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:227px;top:283px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:222px;top:361px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:111px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:47px;top:894px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:51px;top:311px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:528px;top:502px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:349px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:405px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:349px;top:594px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:408px;top:623px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:390px;top:591px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>INTEGRATED <br>CONTROL UNIT <br>‹8−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:373px;top:722px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IGNITION <br>KEY <br>SWITCH <br>(Closed : <br>Key inserted)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:156px;top:176px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.14 <br>(15 A)*<sup>1</sup> <br>FUSE <br>‹7−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:7px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT <br>REAR <br>SUPER <br>LOCKING <br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:12px;top:343px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT <br>SUPER <br>LOCKING <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:251px;top:384px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY<br>HORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:256px;top:312px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY <br>HORN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:110px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>SWITCH <br>‹8−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:173px;top:754px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT REAR <br>DOOR SWITCH <br>‹2−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:173px;top:727px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT REAR <br>DOOR SWITCH <br>‹2−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:173px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR SWITCH <br>‹2−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:340px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY <br>INDICATOR <br>LIGHT <br>‹2−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:459px;top:309px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>INTEGRATED CONTROL UNIT <br>‹7−C› ‹9−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:522px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>AUDIO <br>UNIT <br>‹15−B› <br>‹16−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:605px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR LOCK <br>KNOB SWITCH <br>‹8−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:283px;top:590px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE <br>ASSEMBLY <br>‹2−C›<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}