with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1063px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E25A14426100000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:219px;top:498px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:133px;top:499px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:318px;top:499px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:576px;top:63px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:691px;top:255px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.18 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:648px;top:627px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:842px;top:860px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SG3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:826px;top:899px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:757px;top:860px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RAD TW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:740px;top:899px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:570px;top:899px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:664px;top:688px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FAN C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:599px;top:860px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>TW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:657px;top:899px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:685px;top:860px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:863px;top:688px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:335px;top:105px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.10 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:195px;top:105px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.9 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:123px;top:627px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:192px;top:48px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:130px;top:1021px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:51px;top:38px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:106px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:441px;top:498px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:134px;top:877px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:682px;top:23px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:719px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:707px;top:52px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:648px;top:63px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:777px;top:63px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:319px;top:877px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:308px;top:627px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:614px;top:270px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:338px;top:48px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.2 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:316px;top:1021px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:149px;top:316px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:235px;top:316px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:235px;top:395px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:149px;top:395px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:149px;top:717px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:149px;top:781px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:335px;top:717px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:335px;top:781px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:470px;top:339px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C <br>CONDENSER <br>FAN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:249px;top:346px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RADIATOR <br>FAN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:349px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C <br>CONDENSER <br>FAN <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:160px;top:739px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RADIATOR <br>FAN <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:755px;top:995px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ENGINE COOLANT <br>TEMPERATURE <br>(ECT) SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:678px;top:219px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:598px;top:995px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ENGINE COOLANT <br>TEMPERATURE <br>(ECT) SENSOR 1<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}