with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:527px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:527px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E27A20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:527px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:88px;top:80px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:108px;top:53px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:143px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:181px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:287px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:421px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:682px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:590px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:737px;top:80px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:714px;top:63px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:769px;top:102px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:784px;top:132px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:764px;top:454px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:726px;top:477px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:671px;top:498px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:570px;top:500px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:256px;top:491px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:313px;top:502px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:173px;top:461px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:221px;top:476px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:93px;top:353px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:488px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:762px;top:336px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:77px;top:402px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STARTER<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}