with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E20A18300000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:3px;top:747px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN BEARINGS<br><a href=\"javascript:parent.Cts('000000000000958','iR01')\"></b>Oil Clearance,</a><br><a href=\"javascript:parent.Cts('000000000000958','iR02')\">Selection,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:724px;top:492px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT<br><a href=\"javascript:parent.Cts('000000000000953','i000')\"></b>End Play,</a><br><a href=\"javascript:parent.Cts('000000000000957','i000')\">Runout,</a><br><a href=\"javascript:parent.Cts('000000000000957','i000')\">Out-of-Round,</a><br><a href=\"javascript:parent.Cts('000000000000955','i000')\">Removal,</a><br><a href=\"javascript:parent.Cts('000000000000956','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:695px;top:654px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT OIL SEAL,<br>TRANSMISSION END<br><a href=\"javascript:parent.Cts('000000000000956','i000')\"></b>Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:231px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRAIN BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:357px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:539px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PAN<br><a href=\"javascript:parent.Cts('000000000000951','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000952','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:684px;top:251px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLYWHEEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:666px;top:725px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE BLOCK END COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:640px;top:760px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOWEL PINS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:580px;top:810px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THRUST WASHERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:386px;top:932px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOWEL PINS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:354px;top:962px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:295px;top:1000px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP<br><a href=\"javascript:parent.Cts('000000000001029','i000')\"></b>Overhaul,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:87px;top:1044px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT OIL SEAL,<br>PULLEY END<br><a href=\"javascript:parent.Cts('000000000001029','i000')\"></b>Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:0px;top:930px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNOCK SENSOR<br><a href=\"javascript:parent.Cts('000000000000994','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:42px;top:642px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:42px;top:577px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL SCREEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:41px;top:457px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN BEARING CAP<br>BRIDGE<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}