with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:543px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00D14300014711LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:242px;top:156px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PIN BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:327px;top:484px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CALIPER<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:42px;top:256px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PIN B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:681px;top:515px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PAD SHIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:467px;top:487px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WEAR INDICATOR<br></b>Install inner pad with<br>its wear indicator upward.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:374px;top:448px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER PAD SHIMS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:555px;top:292px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE PADS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:417px;top:29px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.0 mm<br>50 N·m<br>(5.1 kgf·m, 37 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:57px;top:135px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PIN A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:374px;top:194px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PAD RETAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:823px;top:343px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PISTON BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:853px;top:195px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:678px;top:322px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CALIPER BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:601px;top:29px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLEEDER SCREW<br>10 x 1.0 mm<br>9 N·m (0.9 kgf·m, 7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:92px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: Rubber grease<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:124px;top:481px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>108 N·m<br>(11.0 kgf·m, 79.6 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:91px;top:59px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: Silicone grease<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:799px;top:106px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PISTON SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}