with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R51100000000YDAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:190px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:165px;top:174px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:177px;top:195px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:129px;top:295px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:116px;top:359px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:97px;top:451px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:254px;top:497px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR INNER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:232px;top:597px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:401px;top:608px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:422px;top:482px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:551px;top:482px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>LOWER STIFFENER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:554px;top:599px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:706px;top:478px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:807px;top:572px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:707px;top:609px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:698px;top:298px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:689px;top:393px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>LOWER STIFFENER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:663px;top:250px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:698px;top:134px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>LOWER STIFFENER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:555px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:546px;top:133px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:336px;top:118px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:335px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:443px;top:459px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[Z]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:102px;top:627px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: Z]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:57px;top:832px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:39px;top:717px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:254px;top:761px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>LOWER STIFFENER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:250px;top:874px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:361px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:421px;top:689px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:397px;top:812px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:833px;top:748px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:779px;top:657px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:768px;top:1051px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:704px;top:943px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:825px;top:832px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[A]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:406px;top:924px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[DETAIL AREA: A]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:308px;top:994px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:515px;top:1066px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:362px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7.5 mm<br>(0.3 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:435px;top:1061px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0.5 mm<br>(0.02 in.)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}