with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:640px;position:relative;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E2K000000000000EBA211.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:617px;top:585px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LT BLU : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:489px;top:629px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>PUR : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:461px;top:662px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>PNK : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:619px;top:470px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:502px;top:470px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:603px;top:470px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:486px;top:470px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:405px;top:591px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:405px;top:319px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:402px;top:356px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:47px;top:217px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:575px;top:245px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:398px;top:518px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:402px;top:401px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:631px;top:507px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:461px;top:674px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLU : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:488px;top:640px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>PNK : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:622px;top:596px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:581px;top:507px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:513px;top:507px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:480px;top:462px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>EXTEND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:594px;top:462px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RETRACT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:593px;top:860px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RETRACT ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:492px;top:860px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>MIRROR ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:595px;top:841px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>EXTEND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:591px;top:785px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RETRACT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:626px;top:876px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LEFT POWER MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:450px;top:785px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:545px;top:785px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:547px;top:841px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:443px;top:840px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:403px;top:562px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:497px;top:718px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:470px;top:718px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:524px;top:718px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:631px;top:629px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:7px;top:468px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:259px;top:695px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:224px;top:785px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:222px;top:908px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:220px;top:568px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:42px;top:695px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:5px;top:908px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:8px;top:785px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:3px;top:568px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:23px;top:217px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:23px;top:208px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:8px;top:329px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:36px;top:394px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>POWER <br>MIRROR <br>DEFOGGER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:59px;top:618px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LEFT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:253px;top:618px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>RIGHT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:387px;top:285px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY <br>‹4−D› ‹5−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:389px;top:618px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>DASHLIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>‹3−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:426px;top:455px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>LIGHT <br>(1.4 W)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}