with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:831px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E25A20324100000CAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:2px;top:82px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>APP <br>SENSOR A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:2px;top:182px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>APP <br>SENSOR B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:184px;top:36px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:184px;top:57px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:184px;top:77px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:184px;top:127px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:183px;top:147px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:183px;top:168px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:297px;top:108px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:409px;top:35px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:521px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>From THROTTLE<br>ACTUATOR<br>CONTROL MODULE<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:412px;top:100px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VARIOUS<br>SENSORS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:468px;top:203px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:468px;top:224px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:512px;top:269px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:512px;top:290px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:498px;top:308px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:550px;top:347px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:551px;top:399px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:172px;top:265px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:205px;top:367px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TP SENSOR A/B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:745px;top:430px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:543px;top:486px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THROTTLE ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:691px;top:303px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:854px;top:269px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>From<br>THROTTLE<br>ACTUATOR<br>CONTROL<br>MODULE<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:763px;top:165px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THROTTLE<br>ACTUATOR<br>CONTROL<br>MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:488px;top:246px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:787px;top:303px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}