with(document) {
write("<div id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:995px;\">");
write("<div id=\"rect5\"class=\"drag\" style=\"width:950px;position:relative;height:995px;\">");
write("<img id=\"img5\" src=\"../img/SJD5E2PJ54230100000EAAD22.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:995px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:671px;top:737px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b> <br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:671px;top:725px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b> <br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:671px;top:661px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:671px;top:697px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window wiper intermittent control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:671px;top:747px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ultrasonic siren (KE)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:671px;top:797px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Accessory power socket<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:340px;top:796px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:312px;top:797px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:312px;top:747px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:340px;top:746px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:340px;top:696px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:312px;top:697px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:576px;top:947px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:593px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:600px;top:947px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:600px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:593px;top:924px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" class=\"drag\" style=\"position:absolute;left:575px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" class=\"drag\" style=\"position:absolute;left:671px;top:454px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light (KE)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" class=\"drag\" style=\"position:absolute;left:671px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear super loking actuator (KE)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" class=\"drag\" style=\"position:absolute;left:671px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear super loking actuator (KE)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" class=\"drag\" style=\"position:absolute;left:312px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" class=\"drag\" style=\"position:absolute;left:340px;top:174px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" class=\"drag\" style=\"position:absolute;left:533px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" class=\"drag\" style=\"position:absolute;left:505px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" class=\"drag\" style=\"position:absolute;left:505px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" class=\"drag\" style=\"position:absolute;left:532px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" class=\"drag\" style=\"position:absolute;left:340px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" class=\"drag\" style=\"position:absolute;left:312px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" class=\"drag\" style=\"position:absolute;left:340px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" class=\"drag\" style=\"position:absolute;left:357px;top:924px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" class=\"drag\" style=\"position:absolute;left:364px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>R. side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" class=\"drag\" style=\"position:absolute;left:364px;top:947px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" class=\"drag\" style=\"position:absolute;left:357px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" class=\"drag\" style=\"position:absolute;left:340px;top:947px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" class=\"drag\" style=\"position:absolute;left:340px;top:389px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" class=\"drag\" style=\"position:absolute;left:102px;top:889px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" class=\"drag\" style=\"position:absolute;left:312px;top:389px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" class=\"drag\" style=\"position:absolute;left:671px;top:389px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" class=\"drag\" style=\"position:absolute;left:340px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" class=\"drag\" style=\"position:absolute;left:312px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" class=\"drag\" style=\"position:absolute;left:312px;top:489px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" class=\"drag\" style=\"position:absolute;left:340px;top:489px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" class=\"drag\" style=\"position:absolute;left:671px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" class=\"drag\" style=\"position:absolute;left:671px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rignt taillight/brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" class=\"drag\" style=\"position:absolute;left:671px;top:489px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Fuel pump<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" class=\"drag\" style=\"position:absolute;left:671px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" class=\"drag\" style=\"position:absolute;left:312px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" class=\"drag\" style=\"position:absolute;left:340px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" class=\"drag\" style=\"position:absolute;left:526px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" class=\"drag\" style=\"position:absolute;left:498px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" class=\"drag\" style=\"position:absolute;left:498px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" class=\"drag\" style=\"position:absolute;left:526px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" class=\"drag\" style=\"position:absolute;left:671px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" class=\"drag\" style=\"position:absolute;left:339px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" class=\"drag\" style=\"position:absolute;left:312px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" class=\"drag\" style=\"position:absolute;left:671px;top:604px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" class=\"drag\" style=\"position:absolute;left:671px;top:618px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window wiper motor<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" class=\"drag\" style=\"position:absolute;left:671px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>High mount brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" class=\"drag\" style=\"position:absolute;left:671px;top:646px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate latch switch<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" class=\"drag\" style=\"position:absolute;left:104px;top:946px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" class=\"drag\" style=\"position:absolute;left:121px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" class=\"drag\" style=\"position:absolute;left:128px;top:947px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Floor wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" class=\"drag\" style=\"position:absolute;left:340px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" class=\"drag\" style=\"position:absolute;left:102px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" class=\"drag\" style=\"position:absolute;left:312px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" class=\"drag\" style=\"position:absolute;left:312px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" class=\"drag\" style=\"position:absolute;left:340px;top:74px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p5_69\" class=\"drag\" style=\"position:absolute;left:671px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat belt switch<br></b></nobr>");
write("</p>");
write("<p id=\"p5_70\" class=\"drag\" style=\"position:absolute;left:340px;top:224px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p5_71\" class=\"drag\" style=\"position:absolute;left:312px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_72\" class=\"drag\" style=\"position:absolute;left:671px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_73\" class=\"drag\" style=\"position:absolute;left:671px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater<br></b></nobr>");
write("</p>");
write("<p id=\"p5_74\" class=\"drag\" style=\"position:absolute;left:671px;top:275px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's seat heater<br></b></nobr>");
write("</p>");
write("<p id=\"p5_75\" class=\"drag\" style=\"position:absolute;left:312px;top:275px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_76\" class=\"drag\" style=\"position:absolute;left:340px;top:274px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p5_77\" class=\"drag\" style=\"position:absolute;left:128px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness A<br></b></nobr>");
write("</p>");
write("<p id=\"p5_78\" class=\"drag\" style=\"position:absolute;left:121px;top:924px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_79\" class=\"drag\" style=\"position:absolute;left:104px;top:924px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}