with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:943px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:943px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00J16166200000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:943px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:825px;top:174px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR QUARTER<br>INNER TRIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:717px;top:110px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR REAR SASH TRIM<br><a href=\"javascript:parent.Cts('000000000000212','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:793px;top:493px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PLASTIC COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:569px;top:62px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR CENTER OUTER CHANNEL TAPE<br><a href=\"javascript:parent.Cts('000000000000207','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:467px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR ROOF OUTER CHANNEL TAPE<br><a href=\"javascript:parent.Cts('000000000000207','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:560px;top:522px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR WEATHERSTRIP<br><a href=\"javascript:parent.Cts('000000000000213','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:414px;top:475px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR<br><a href=\"javascript:parent.Cts('000000000000197','i000')\"></b>Position Adjustment,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:748px;top:656px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ARMREST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:688px;top:725px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PULL POCKET CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:713px;top:857px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SWITCH PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:684px;top:911px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER WINDOW SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:196px;top:629px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PANEL BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:232px;top:856px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR PANEL<br><a href=\"javascript:parent.Cts('000000000000211','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:190px;top:481px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:105px;top:522px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR GLASS<br>INNER WEATHERSTRIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:68px;top:428px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR CHECKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:197px;top:244px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:23px;top:321px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR GLASS OUTER<br>WEATHERSTRIP<br><a href=\"javascript:parent.Cts('000000000000208','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}