with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:447px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:447px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00J36200000000CAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:447px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:433px;top:23px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>FRONT<br>SPEAKERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:429px;top:136px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:254px;top:136px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:151px;top:218px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>GRAPHIC/<br>COLOR SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:338px;top:218px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>KEY SWITCH<br>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:439px;top:218px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>VOICE SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:316px;top:315px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>NAVIGATION UNIT <br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:214px;top:355px;font-weight:normal;font-size:6.4pt;\">");
write("<nobr><b>·    YAW RATE SENSOR  <br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:344px;top:355px;font-weight:normal;font-size:6.4pt;\">");
write("<nobr><b>·    DVD−ROM  <br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:432px;top:384px;font-weight:normal;font-size:6.4pt;\">");
write("<nobr><b>GPS<br>RECEIVER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:653px;top:324px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:637px;top:382px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>GPS<br>ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:561px;top:316px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>VSP<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}