with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2ED52100000000CDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:70px;top:932px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:62px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:626px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of male terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:719px;top:963px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:493px;top:931px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL SENSOR 2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:361px;top:861px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:106px;top:30px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE FLUID<br>LEVEL SWITCH<br>2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:39px;top:508px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM CONNECTOR E (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:394px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br>4P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:39px;top:203px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br>12P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:40px;top:355px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GAUGE ASSEMBLY CONNECTOR A (20P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:742px;top:204px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA OFF SWITCH<br>6P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:707px;top:30px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEERING ANGLE SENSOR<br>5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:40px;top:667px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA CONTROL UNIT 46P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:418px;top:508px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YAW RATE/LATERAL ACCELERATION SENSOR 4P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:393px;top:355px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GAUGE ASSEMBLY CONNECTOR B (28P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:359px;top:202px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br>21P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:468px;top:964px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:391px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}