with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:641px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:641px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00J18573900000MBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:641px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:62px;top:22px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:316px;top:214px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:40px;top:363px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:227px;top:441px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:360px;top:385px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:107px;top:456px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:91px;top:560px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:233px;top:68px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m (2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:222px;top:588px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>8 x 1.25 mm<br>18 N·m (1.8 kgf·m, 13 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}