with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:767px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:767px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E25F00000047011KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:767px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:440px;top:627px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER STEERING<br>PRESSURE SWITCH<br>12 N·m<br>(1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:389px;top:424px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FEED HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:585px;top:707px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER LINE FLARE NUTS<br>27 N·m<br>(2.8 kgf·m, 20 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:572px;top:464px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FEED HOSE FLARE NUT<br>16 x 1.5 mm<br>28 N·m<br>(2.9 kgf·m, 21 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:8px;top:469px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP INLET HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:305px;top:686px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RETURN LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:372px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:46px;top:566px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:278px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:261px;top:648px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:251px;top:408px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11 N·m <br>(1.1 kgf·m, <br>8.0 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:512px;top:362px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RETURN LINE FLARE NUT<br>16 x 1.5 mm<br>42 N·m <br>(4.3 kgf·m, 31 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:116px;top:429px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:64px;top:273px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2.5−5.5 mm<br>(0.01−0.22 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:320px;top:270px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2.0−4.0 mm<br>(0.08−0.16 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:568px;top:229px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2.5−5.5 mm<br>(0.01−0.22 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:121px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ADJUSTABLE HOSE CLAMP (A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:639px;top:21px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOSE CLAMP (B)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}