with(document) {
write("<div id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:559px;\">");
write("<div id=\"rect4\"class=\"drag\" style=\"width:950px;position:relative;height:559px;\">");
write("<img id=\"img4\" src=\"../img/SJD5E21A20300000000DBAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:559px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:142px;top:158px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:178px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:210px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:241px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:269px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:325px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:376px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:415px;top:43px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:774px;top:420px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:742px;top:470px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:616px;top:510px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:430px;top:517px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:395px;top:521px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:360px;top:521px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:326px;top:522px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:97px;top:468px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:96px;top:422px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:457px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:677px;top:503px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS A<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:144px;top:516px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:63px;top:221px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:0px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}