with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E25A14600000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:427px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IGNITION COIL<br>COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:455px;top:579px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br>GUIDE A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:679px;top:490px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:615px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHAIN CASE COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:365px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT POSITION<br>(CKP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:19px;top:745px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TENSIONER<br>ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:760px;top:746px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT<br>PULLEY<br><a href=\"javascript:parent.Cts('000000000001140','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:498px;top:165px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD COVER<br><a href=\"javascript:parent.Cts('000000000001128','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000001129','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:529px;top:249px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br><a href=\"javascript:parent.Cts('000000000001138','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000001139','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:760px;top:587px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VARIABLE VALVE<br>TIMING CONTROL<br>(VTC) OIL SOLENOID<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:760px;top:923px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT<br>PULLEY BOLT<br><a href=\"javascript:parent.Cts('000000000001140','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:204px;top:969px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CKP PULSE PLATE<br><a href=\"javascript:parent.Cts('000000000001176','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:18px;top:905px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUTO-TENSIONER<br><a href=\"javascript:parent.Cts('000000000001141','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:602px;top:420px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br>GUIDE B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:452px;top:945px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHAIN CASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:408px;top:986px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}