with(document) {
write("<div id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:339px;\">");
write("<div id=\"rect6\"class=\"drag\" style=\"width:950px;position:relative;height:339px;\">");
write("<img id=\"img6\" src=\"../img/SJD5E2PJ54230100000EAAD23.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:339px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:689px;top:40px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left taillight/brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:689px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light (KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:358px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:329px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:329px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:358px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:689px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:119px;top:218px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G702<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:689px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:358px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:329px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:160px;top:289px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>R. side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:153px;top:288px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:136px;top:289px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}