with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:895px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:895px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E00R11100000000YCAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:895px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:711px;top:402px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR BUMPER BEAM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:676px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:750px;top:141px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:739px;top:513px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>38 N·m <br>(3.9 kgf·m, 28 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:537px;top:849px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR SIDE SEAT PIPES<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:306px;top:849px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>K20A9 ENGINE MODEL<br>BATTERY BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:135px;top:819px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:41px;top:740px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT BUMPER BEAM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:374px;top:627px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:254px;top:283px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:102px;top:157px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:43px;top:396px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D17A2 ENGINE MODEL<br>BATTERY BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:314px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT REAR WHEELHOUSE<br>GUSSET<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:698px;top:99px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT REAR WHEELHOUSE<br>GUSSET<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}