with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1007px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1007px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00J16126700000DAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1007px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:567px;top:128px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IMMOBILIZER LABEL/<br>IMMOBILIZER and SECURITY LABEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:569px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLASS<br><a href=\"javascript:parent.Cts('000000000000451','i000')\"></b>Replacement,</a><br><a href=\"javascript:parent.Cts('000000000000453','i000')\">Adjustment,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:43px;top:79px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLASS RUN CHANNEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:342px;top:385px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR<br><a href=\"javascript:parent.Cts('000000000000451','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:277px;top:618px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER HANDLE<br>PROTECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:217px;top:586px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPACER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:503px;top:448px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR CYLINDER (Driver's)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:117px;top:650px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER HANDLE<br><a href=\"javascript:parent.Cts('000000000000201','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:460px;top:715px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RETAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:649px;top:546px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LATCH<br><a href=\"javascript:parent.Cts('000000000000200','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:760px;top:659px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STRIKER<br><a href=\"javascript:parent.Cts('000000000000203','i000')\"></b>Adjustment,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:643px;top:798px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEVER COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:461px;top:847px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER HANDLE CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:294px;top:690px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LATCH CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:431px;top:890px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER HANDLE CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:187px;top:965px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER HANDLE<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}