with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:703px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:703px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2AJ54200000000DEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:703px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:273px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KEYLESS RECEIVER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:501px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHT WASHER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:578px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IMOES UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:655px;top:80px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FOG LIGHT CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:41px;top:517px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECURITY<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:415px;top:617px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:553px;top:573px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:0px;top:670px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>RHD type is shown, LHD type is similar.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}