with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:952px; height:719px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:952px;position:relative;height:719px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00D00060845111KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:719px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:244px;top:251px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:569px;top:16px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:580px;top:71px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, <br>16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:709px;top:262px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:527px;top:513px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:469px;top:655px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:171px;top:657px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:81px;top:572px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:3px;top:334px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:280px;top:40px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>EQUALIZER COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:404px;top:144px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>MID COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:460px;top:413px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>EQUALIZER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:507px;top:380px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>ADJUSTING NUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:124px;top:525px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>LEFT PARKING BRAKE CABLE<br></b>Check for faulty movement.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:502px;top:611px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>RIGHT PARKING BRAKE CABLE<br></b>Check for faulty movement.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:730px;top:465px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PARKING BRAKE LEVER<br></b>Check for smooth operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:684px;top:519px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PARKING BRAKE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:744px;top:16px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PARKING BRAKE CABLE A<br></b>Check for faulty movement.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:625px;top:216px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m (2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}