with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:475px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2K000000000000EBA907.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:138px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:360px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:582px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:804px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:815px;top:82px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:815px;top:86px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:111px;top:160px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:355px;top:407px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:188px;top:286px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:188px;top:268px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:369px;top:363px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:200px;top:139px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:673px;top:338px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:477px;top:338px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:553px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:554px;top:347px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:614px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:618px;top:347px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:545px;top:166px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:355px;top:393px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:355px;top:376px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:317px;top:277px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:318px;top:158px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:318px;top:122px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:153px;top:139px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:919px;top:18px;font-weight:normal;font-size:8.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:35px;top:11px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>Brake Lights, Back−up Lights, Turn Signal/Hazard Lights<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:20px;top:17px;font-weight:normal;font-size:8.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:855px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:910px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:855px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:724px;top:194px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:724px;top:111px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:881px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.16 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:903px;top:77px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:62px;top:77px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:32px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:85px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:62px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:39px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:84px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:574px;top:347px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:599px;top:347px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:200px;top:255px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:153px;top:255px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:902px;top:38px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:881px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:853px;top:90px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1 : Under−hood fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:853px;top:94px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2 : Under−dash fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:881px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:881px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:881px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:881px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:881px;top:33px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:902px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:62px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:60px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:60px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:58px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:58px;top:33px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:40px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:85px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:85px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:85px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:39px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:62px;top:38px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:856px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:855px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:855px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:853px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:855px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:881px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:639px;top:296px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:542px;top:188px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:563px;top:145px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:574px;top:145px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:676px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:678px;top:418px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:675px;top:316px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:674px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:477px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:515px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:517px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:517px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:545px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:589px;top:200px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:589px;top:177px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:722px;top:180px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:686px;top:200px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:423px;top:220px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INTEGRATED CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:481px;top:316px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:445px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:548px;top:274px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TURN SIGNAL/HAZARD DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:714px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:639px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:481px;top:418px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:714px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:722px;top:130px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:683px;top:130px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:445px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:642px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:479px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:443px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G702<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:640px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:712px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:316px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:312px;top:236px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:318px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:325px;top:98px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:325px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:268px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:364px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:266px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G702<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:314px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:264px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:152px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:151px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:150px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:197px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:148px;top:236px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:101px;top:236px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:198px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:104px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:103px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G702<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:101px;top:194px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:199px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:104px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:104px;top:139px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:337px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:195px;top:236px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:569px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:598px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:567px;top:103px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:567px;top:125px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:653px;top:200px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:653px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:517px;top:296px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:838px;top:200px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:881px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:902px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:112px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:112px;top:98px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:122px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:809px;top:444px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:811px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:643px;top:82px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:622px;top:83px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.16 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:193px;top:151px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SECURITY <br>HORN <br>RELAY <br>‹9−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:116px;top:157px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRAKE <br>PEDAL <br>POSITION <br>SWITCH <br>(Closed : <br>Pedal pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:149px;top:151px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HORN <br>RELAY <br>‹18−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:148px;top:268px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ECM <br>‹25−C› <br>‹29−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:192px;top:268px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ABS <br>MODULATOR− <br>CONTROL UNIT <br>‹21−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:116px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT <br>BRAKE <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:163px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT <br>BRAKE <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:210px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HIGH <br>MOUNT <br>BRAKE <br>LIGHT <br>(18 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:329px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BACK−UP <br>LIGHT SWITCH <br>(On the transmission <br>housing)<br>(Closed : In position R)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:279px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT <br>BUCK−UP <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:329px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT <br>BACK−UP <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:359px;top:376px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR WIPER <br>INTERMITTENT <br>CONTROL UNIT <br>‹12−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:359px;top:393px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NAVIGATION <br>UNIT <br>‹17−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:584px;top:138px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TURN SIGNAL <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:714px;top:94px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY <br>‹4−D› ‹5−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:734px;top:154px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LIGHT <br>(0.56 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:736px;top:128px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HAZARD <br>WARNING <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:715px;top:207px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DASH LIGHTS<br>BRIGHTNESS <br>CONTROLLER <br>‹3−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:451px;top:296px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT TURN <br>SIGNAL LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:457px;top:365px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:495px;top:384px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SIDE <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:529px;top:365px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FRONT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:688px;top:296px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT TURN <br>SIGNAL LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:596px;top:362px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TURN SIGNAL <br>INDICATOR LIGHT <br>(LED) <br>‹3−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:653px;top:365px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FRONT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:692px;top:384px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SIDE <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:725px;top:365px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:553px;top:362px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SECURITY <br>CONTROL UNIT <br>‹9−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:192px;top:286px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VSA <br>MODULATOR− <br>CONTROL UNIT <br>‹22−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:359px;top:407px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR WIPER <br>INTERMITTENT <br>CONTROL UNIT <br>‹13−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:803px;top:195px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(FUSE/RELAY <br>BOX SOCKET)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}