with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1130px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1130px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E25R41100000000YDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1130px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:95px;top:186px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Top View<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:96px;top:822px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Side View<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:296px;top:862px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:296px;top:797px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:321px;top:746px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:397px;top:1059px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:629px;top:1039px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:444px;top:779px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:255px;top:254px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:337px;top:186px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:299px;top:220px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:374px;top:555px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:399px;top:497px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:378px;top:683px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:563px;top:716px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>123 (4.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:563px;top:732px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>171 (6.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:563px;top:747px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>223 (8.78)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:476px;top:194px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>350 (13.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:488px;top:210px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>274 (10.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:499px;top:227px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>220 (8.66)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:297px;top:883px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>M10 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:296px;top:818px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>M10 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:320px;top:768px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>M10 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:444px;top:801px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:397px;top:1080px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:630px;top:1060px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:520px;top:1085px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>VERTICAL LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:137px;top:1033px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>BASE LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:136px;top:474px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>CENTER LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:11px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:137px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:434px;top:56px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:91px;top:55px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:56px;top:105px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:399px;top:55px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:91px;top:80px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:56px;top:80px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:56px;top:55px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:399px;top:80px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:91px;top:105px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:399px;top:105px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:434px;top:105px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:434px;top:80px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51) <br></b></nobr>");
write("</p>");
write("</div>");
write("<svg id=\"bl1_1\" class=\"drag\" style=\"position:absolute; left:312px; top:448px; width:4px; height:160px; overflow:visible;\"><line x1=\"1\" y1=\"158\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" class=\"drag\" on=\"true\" string=\"450 (17.7) e1, g1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_2\" class=\"drag\" style=\"position:absolute; left:328px; top:451px; width:4px; height:158px; overflow:visible;\"><line x1=\"1\" y1=\"156\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" class=\"drag\" on=\"true\" string=\"439 (17.3) f1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_3\" class=\"drag\" style=\"position:absolute; left:313px; top:335px; width:4px; height:102px; overflow:visible;\"><line x1=\"1\" y1=\"100\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" class=\"drag\" on=\"true\" string=\"580 (22.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_4\" class=\"drag\" style=\"position:absolute; left:328px; top:341px; width:4px; height:96px; overflow:visible;\"><line x1=\"1\" y1=\"94\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" class=\"drag\" on=\"true\" string=\"510 (20.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_5\" class=\"drag\" style=\"position:absolute; left:343px; top:343px; width:4px; height:94px; overflow:visible;\"><line x1=\"1\" y1=\"92\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" class=\"drag\" on=\"true\" string=\"492 (19.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_6\" class=\"drag\" style=\"position:absolute; left:327px; top:912px; width:4px; height:105px; overflow:visible;\"><line x1=\"1\" y1=\"103\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" class=\"drag\" on=\"true\" string=\"416 (16.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_7\" class=\"drag\" style=\"position:absolute; left:457px; top:974px; width:4px; height:49px; overflow:visible;\"><line x1=\"1\" y1=\"47\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" class=\"drag\" on=\"true\" string=\"256\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_8\" class=\"drag\" style=\"position:absolute; left:474px; top:968px; width:4px; height:60px; overflow:visible;\"><line x1=\"1\" y1=\"58\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" class=\"drag\" on=\"true\" string=\"(10.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_9\" class=\"drag\" style=\"position:absolute; left:506px; top:958px; width:4px; height:63px; overflow:visible;\"><line x1=\"1\" y1=\"61\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" class=\"drag\" on=\"true\" string=\"254\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_10\" class=\"drag\" style=\"position:absolute; left:524px; top:962px; width:4px; height:67px; overflow:visible;\"><line x1=\"1\" y1=\"65\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" class=\"drag\" on=\"true\" string=\"(10.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_11\" class=\"drag\" style=\"position:absolute; left:592px; top:893px; width:4px; height:118px; overflow:visible;\"><line x1=\"1\" y1=\"116\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" class=\"drag\" on=\"true\" string=\"391 (15.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</div>");
}