with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R51100000000YDAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:516px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD UPPER<br>SIDE MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:684px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:434px;top:122px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:751px;top:90px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:725px;top:117px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE MEMBER EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:710px;top:147px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WINDSHIELD LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:270px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT DAMPER<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:168px;top:127px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:112px;top:260px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:58px;top:366px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:121px;top:418px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACKPLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:159px;top:451px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:35px;top:506px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:123px;top:604px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:238px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:289px;top:733px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEERING<br>JOINT COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:172px;top:733px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUBFRAME<br>BRACKET<br>UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:144px;top:861px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:102px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEERING GEAR BOX<br>STIFFENER UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:161px;top:1073px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:423px;top:759px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: Z]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:440px;top:1071px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:747px;top:981px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:726px;top:675px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: Y]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:511px;top:441px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[Z]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:572px;top:450px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[Y]<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}