with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:847px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:847px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R11100000000YCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:847px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:418px;top:205px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVER'S AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:777px;top:319px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CABLE REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:805px;top:399px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MEMORY ERASE<br>SIGNAL (MES)<br>CONNECTOR (2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:774px;top:487px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br>(DTC) 16P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:761px;top:569px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SRS UNIT<br>(With built-in sensor)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:599px;top:728px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE IMPACT<br>SENSOR (FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:545px;top:808px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE SEAT BELT<br>OUTER LAP TENSIONER (RHD type)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:379px;top:769px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE SEAT <br>BELT TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:704px;top:622px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE <br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:109px;top:606px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE SEAT BELT<br>OUTER LAP TENSIONER<br>(LHD type)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:286px;top:705px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CENTER SEAT<br>BELT TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:227px;top:655px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE IMPACT<br>SENSOR (FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:15px;top:549px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE SEAT<br>BELT TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:30px;top:382px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:143px;top:247px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PASSENGER'S AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:677px;top:180px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SRS INDICATOR<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}