with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:1900px;position:relative;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2K000000000000EBAD19.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:854px;top:469px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:1629px;top:775px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:1638px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:919px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:919px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:885px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:166px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:166px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:482px;top:531px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(FUSE/RELAY BOX SOCKET)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:350px;top:870px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G201*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:350px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G301*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:1350px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:1485px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:1488px;top:329px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:1390px;top:295px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:1390px;top:268px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:1422px;top:329px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:1412px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:905px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G301*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:905px;top:870px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G201*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:432px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU *<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:431px;top:644px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN *<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:431px;top:578px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU *<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:1286px;top:267px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:1353px;top:378px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:1229px;top:445px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:1225px;top:378px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:1285px;top:378px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:1285px;top:445px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:1352px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:1419px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:1416px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:1484px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:1355px;top:718px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>66<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:1488px;top:718px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:1708px;top:218px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*4 : D17A2 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:1708px;top:209px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*3 : K20A9 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:1708px;top:200px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : Under−dash fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:1708px;top:191px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : Under−hood fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:1823px;top:89px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:71px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>HVAC (Heating, Ventilation, and Air Conditioning)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:670px;top:223px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:985px;top:456px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:1001px;top:300px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:1001px;top:291px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:1023px;top:299px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:736px;top:456px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:607px;top:291px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:607px;top:300px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:369px;top:300px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:369px;top:291px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:591px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:353px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:391px;top:299px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:629px;top:299px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:859px;top:299px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:835px;top:291px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:835px;top:300px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:589px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:592px;top:778px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:986px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:983px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:986px;top:778px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:909px;top:778px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:818px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:354px;top:778px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:1285px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:1230px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:429px;top:567px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN *<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:486px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:487px;top:778px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:482px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:434px;top:684px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>64<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:745px;top:523px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>65<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:1719px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:1719px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:1717px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:1808px;top:78px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:1808px;top:100px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:1764px;top:68px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:1764px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:1764px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:1764px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:1764px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:124px;top:78px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:80px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:117px;top:68px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:120px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:124px;top:89px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:65px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:80px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:124px;top:100px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:77px;top:157px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:124px;top:155px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:164px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:165px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:165px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:165px;top:157px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:1838px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:23px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:377px;top:338px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RADIATOR <br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:610px;top:329px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>CONDENSER <br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:760px;top:329px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>COMPRESSOR <br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:926px;top:338px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLOWER <br>MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:1009px;top:510px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLOWER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:299px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RADIATOR <br>FAN MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:615px;top:695px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>CONDENSER <br>FAN MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:510px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THERMAL <br>PROTECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:843px;top:690px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>COMPRESSOR <br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:1004px;top:732px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER <br>TRANSISTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:427px;top:709px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM <br>‹25−D›<br>‹28−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:1235px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RECIRCULATION <br>CONTROL MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:1344px;top:742px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECT <br>SENSOR <br>‹25−C› <br>‹28−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:1473px;top:743px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br>‹3−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:1398px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER <br>RELAY ‹11−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:1398px;top:295px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER MIRROR <br>DEFOGGER <br>RELAY ‹11−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:1470px;top:295px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY <br>‹4−D› ‹5−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:737px;top:548px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM <br>‹25−D›<br>‹28−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:414px;top:467px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(FUSE/RELAY <br>BOX SOCKET)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}