with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:349px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:349px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E20A14616700000KCAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:349px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:218px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:330px;top:315px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:141px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:330px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:399px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:64px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:3px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:449px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:141px;top:315px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:448px;top:315px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:10px;top:315px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:413px;top:315px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:58px;top:315px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:218px;top:315px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}