with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1119px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R31100000000YDAD22.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:466px;top:37px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:693px;top:442px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:603px;top:517px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:551px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:583px;top:732px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:450px;top:1090px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:187px;top:868px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:161px;top:827px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Include (A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:94px;top:667px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:160px;top:772px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:475px;top:885px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:327px;top:313px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:508px;top:791px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR SEPARATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:552px;top:869px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR<br>LOWER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:510px;top:1077px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:586px;top:569px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}