with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:433px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:433px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E20A18300043401KCAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:433px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:9px;top:51px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m<br>(1.2 kgf·m, <br>8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:364px;top:212px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m<br>(4.5 kgf·m, <br>33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:306px;top:287px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>8 x 1.25 mm<br>24 N·m<br>(2.4 kgf·m, 17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:262px;top:364px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m<br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:93px;top:364px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>8 x 1.25 mm<br>24 N·m<br>(2.4 kgf·m, 17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:100px;top:296px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:373px;top:117px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:75px;top:248px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}