with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00H46200053401MAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:116px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>8 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:69px;top:59px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:61px;top:91px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:165px;top:65px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:158px;top:102px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:289px;top:60px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:284px;top:92px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:387px;top:60px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:380px;top:92px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:105px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:343px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:213px;top:232px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}