with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:831px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2JJ20170700000KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:426px;top:335px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>26 N·m <br>(2.7 kgf·m, 20 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:651px;top:740px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPECIAL BOLTS<br>14 x 1.5 mm<br>103 N·m <br>(10.5 kgf·m, 76 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:138px;top:44px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:638px;top:139px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Reference hole alignment<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:610px;top:171px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUBFRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:789px;top:171px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REFERENCE HOLE<br>(Body side)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:599px;top:374px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SCREWDIVER or<br>TAPERED PUNCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:795px;top:368px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSTALLATION<br>REFERENCE HOLE<br>(Subframe side)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:686px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSTALLATION<br>REFERENCE HOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:559px;top:422px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUBFRAME<br>REAR DAMPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:372px;top:290px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSTALLATION<br>REFERENCE HOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:128px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:309px;top:430px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:558px;top:485px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:467px;top:618px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:123px;top:526px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}