with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1108px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R41100000000YDA190.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:102px;top:637px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>CENTER LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:434px;top:1081px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>VERTICAL LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:262px;top:851px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:265px;top:879px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT b<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:240px;top:941px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT c<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:252px;top:903px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT d<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:398px;top:527px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT e<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:414px;top:585px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT f<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:404px;top:558px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT g<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:412px;top:874px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:497px;top:730px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:394px;top:902px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT k<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:499px;top:709px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT l<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:677px;top:934px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT m<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:681px;top:905px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT n<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:773px;top:946px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:775px;top:888px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:740px;top:705px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT q<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:848px;top:893px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT r<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:877px;top:928px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT s<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:496px;top:758px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:859px;top:416px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT w<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:706px;top:1080px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1976 (77.80)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:606px;top:927px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>225 (8.85)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:498px;top:915px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>90 (3.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:498px;top:901px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>86 (3.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:498px;top:887px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>66 (2.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:589px;top:875px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>43<br>(1.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:499px;top:873px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>15 (0.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:587px;top:943px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>350 (13.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:671px;top:955px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>585 (23.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:644px;top:970px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>655 (25.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:652px;top:983px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>875 (34.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:660px;top:997px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1046 (41.18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:668px;top:1011px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1142 (44.96)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:676px;top:1025px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1325 (52.17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:683px;top:1039px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1506 (59.29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:691px;top:1052px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1511 (59.49)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:699px;top:1067px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1910 (75.20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:802px;top:400px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1992 (78.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:809px;top:386px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2016 (79.37)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:815px;top:372px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2142 (84.33)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:823px;top:358px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2181 (85.87)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:830px;top:344px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2316 (91.18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:441px;top:399px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>475 (18.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:561px;top:542px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>63<br>(2.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:524px;top:572px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>112<br>(4.41)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:518px;top:604px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>151<br>(5.94)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:496px;top:758px;font-weight:normal;font-size:8.1pt;\">");
write("<nobr><b>POINT i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:476px;top:659px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>342 (13.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:487px;top:674px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>271 (10.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:497px;top:690px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>209 (8.23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:11px;top:15px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:390px;top:39px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front damper φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:390px;top:64px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Front damper center φ78 (3.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:137px;top:15px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:390px;top:89px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front damper φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:390px;top:114px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front damper φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:390px;top:139px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front subframe φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:390px;top:164px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front subframe φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:390px;top:189px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:23px;top:39px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:58px;top:139px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:58px;top:39px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front subframe φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:58px;top:64px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:23px;top:114px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>d<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:23px;top:139px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>e<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:58px;top:89px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:23px;top:89px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>c<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:23px;top:64px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>b<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:23px;top:164px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>f<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:58px;top:114px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:23px;top:188px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>g<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:58px;top:189px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:58px;top:164px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:355px;top:39px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:355px;top:114px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>k<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:355px;top:138px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>l<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:355px;top:89px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:355px;top:64px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:355px;top:163px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>m<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:355px;top:188px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>n<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:714px;top:139px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:679px;top:39px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:714px;top:89px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:714px;top:39px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:714px;top:64px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ50 (1.97)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:679px;top:114px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>r<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:679px;top:89px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>q<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:679px;top:64px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:714px;top:114px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:679px;top:139px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>s<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:679px;top:164px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>t<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:678px;top:189px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>u<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:714px;top:164px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:714px;top:188px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("</div>");
write("<svg id=\"bl1_1\" class=\"drag\" style=\"position:absolute; left:265px; top:497px; width:4px; height:144px; overflow:visible;\"><line x1=\"1\" y1=\"142\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" class=\"drag\" on=\"true\" string=\"1240 (48.81)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_2\" class=\"drag\" style=\"position:absolute; left:280px; top:499px; width:4px; height:142px; overflow:visible;\"><line x1=\"1\" y1=\"140\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" class=\"drag\" on=\"true\" string=\"1160 (45.67)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_3\" class=\"drag\" style=\"position:absolute; left:294px; top:497px; width:4px; height:144px; overflow:visible;\"><line x1=\"1\" y1=\"142\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" class=\"drag\" on=\"true\" string=\"1154 (45.43)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_4\" class=\"drag\" style=\"position:absolute; left:308px; top:499px; width:4px; height:142px; overflow:visible;\"><line x1=\"1\" y1=\"140\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" class=\"drag\" on=\"true\" string=\"1053 (41.46)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_5\" class=\"drag\" style=\"position:absolute; left:321px; top:665px; width:4px; height:92px; overflow:visible;\"><line x1=\"1\" y1=\"90\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" class=\"drag\" on=\"true\" string=\"556 (21.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_6\" class=\"drag\" style=\"position:absolute; left:335px; top:667px; width:4px; height:90px; overflow:visible;\"><line x1=\"1\" y1=\"88\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" class=\"drag\" on=\"true\" string=\"502 (19.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_7\" class=\"drag\" style=\"position:absolute; left:349px; top:666px; width:4px; height:91px; overflow:visible;\"><line x1=\"1\" y1=\"89\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" class=\"drag\" on=\"true\" string=\"481 (18.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_8\" class=\"drag\" style=\"position:absolute; left:322px; top:513px; width:4px; height:91px; overflow:visible;\"><line x1=\"1\" y1=\"89\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" class=\"drag\" on=\"true\" string=\"445 (17.5)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_9\" class=\"drag\" style=\"position:absolute; left:336px; top:512px; width:4px; height:92px; overflow:visible;\"><line x1=\"1\" y1=\"90\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" class=\"drag\" on=\"true\" string=\"440 (17.3)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_10\" class=\"drag\" style=\"position:absolute; left:349px; top:511px; width:4px; height:93px; overflow:visible;\"><line x1=\"1\" y1=\"91\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" class=\"drag\" on=\"true\" string=\"437 (17.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_11\" class=\"drag\" style=\"position:absolute; left:387px; top:500px; width:4px; height:141px; overflow:visible;\"><line x1=\"1\" y1=\"139\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" class=\"drag\" on=\"true\" string=\"980 (38.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_12\" class=\"drag\" style=\"position:absolute; left:594px; top:637px; width:4px; height:101px; overflow:visible;\"><line x1=\"1\" y1=\"99\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" class=\"drag\" on=\"true\" string=\"351 (13.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_13\" class=\"drag\" style=\"position:absolute; left:594px; top:534px; width:4px; height:97px; overflow:visible;\"><line x1=\"1\" y1=\"95\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" class=\"drag\" on=\"true\" string=\"351 (13.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_14\" class=\"drag\" style=\"position:absolute; left:610px; top:548px; width:4px; height:93px; overflow:visible;\"><line x1=\"1\" y1=\"91\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" class=\"drag\" on=\"true\" string=\"649 (25.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_15\" class=\"drag\" style=\"position:absolute; left:673px; top:545px; width:4px; height:96px; overflow:visible;\"><line x1=\"1\" y1=\"94\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" class=\"drag\" on=\"true\" string=\"940 (37.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_16\" class=\"drag\" style=\"position:absolute; left:695px; top:523px; width:4px; height:118px; overflow:visible;\"><line x1=\"1\" y1=\"116\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" class=\"drag\" on=\"true\" string=\"1120 (44.09)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_17\" class=\"drag\" style=\"position:absolute; left:716px; top:545px; width:4px; height:96px; overflow:visible;\"><line x1=\"1\" y1=\"94\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" class=\"drag\" on=\"true\" string=\"826 (32.5)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_18\" class=\"drag\" style=\"position:absolute; left:827px; top:548px; width:4px; height:93px; overflow:visible;\"><line x1=\"1\" y1=\"91\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" class=\"drag\" on=\"true\" string=\"510 (20.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("<svg id=\"bl1_19\" class=\"drag\" style=\"position:absolute; left:934px; top:541px; width:4px; height:100px; overflow:visible;\"><line x1=\"1\" y1=\"98\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" class=\"drag\" on=\"true\" string=\"826 (32.5)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</div>");
}