with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E20A14600000000DAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:538px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROCKER ARM ASSEMBLY<br><a href=\"javascript:parent.Cts('000000000000926','i000')\"></b>Overhaul,</a><br><a href=\"javascript:parent.Cts('000000000000927','i000')\">Inspection,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:415px;top:498px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL CONTROL <br>ORIFICE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:670px;top:194px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOWEL PINS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:724px;top:310px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT<br><a href=\"javascript:parent.Cts('000000000000923','i000')\"></b>Inspection,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:15px;top:402px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTEC SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:15px;top:514px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTEC SOLENOID<br>VALVE FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:15px;top:623px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE <br>COTTERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:15px;top:738px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING <br>RETAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:15px;top:789px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:15px;top:853px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE <br>SEAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:170px;top:243px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:241px;top:949px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD<br><a href=\"javascript:parent.Cts('000000000000916','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000919','i000')\">Inspection,</a><br><a href=\"javascript:parent.Cts('000000000000917','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:15px;top:911px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE SPRING <br>SEAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:819px;top:905px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACK COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:303px;top:1071px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:724px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:718px;top:611px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE SEAL<br><a href=\"javascript:parent.Cts('000000000000937','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:708px;top:684px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE GUIDE<br><a href=\"javascript:parent.Cts('000000000000941','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:841px;top:412px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT <br>PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:726px;top:412px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:591px;top:1039px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br><a href=\"javascript:parent.Cts('000000000000937','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000938','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:85px;top:964px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:655px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RUBBER SEALS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:47px;top:226px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER <br>HEAD PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:463px;top:559px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}