with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:791px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:791px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E2PJ54230100000EAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:791px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:683px;top:653px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b> <br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:683px;top:639px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b> <br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:690px;top:396px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VTEC oil pressure switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:422px;top:396px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:369px;top:396px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:389px;top:575px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:369px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:369px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:369px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:369px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:369px;top:346px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:393px;top:246px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:393px;top:161px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:393px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:393px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:393px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:393px;top:118px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:393px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:393px;top:96px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:393px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:690px;top:575px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:422px;top:574px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:422px;top:417px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:690px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (LG)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:690px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CMP sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:422px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:690px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CKP sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:422px;top:460px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:422px;top:346px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:690px;top:346px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (LG)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:422px;top:246px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:690px;top:246px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.4 ignition coil<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:690px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.3 ignition coil<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:422px;top:224px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:422px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:690px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radiator fan switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:690px;top:161px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Vehicle speed sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:422px;top:160px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:690px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.2 ignition coil<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:690px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.1 ignition coil<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:422px;top:203px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:422px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:422px;top:117px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:690px;top:118px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>EGR valve<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:422px;top:96px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:690px;top:96px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IAC valve<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:690px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:422px;top:74px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:422px;top:531px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:690px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:229px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Knock sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:690px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:422px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:393px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:120px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:137px;top:710px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:154px;top:709px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:161px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Engine wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:204px;top:731px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:211px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:218px;top:412px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:218px;top:569px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Primary O<sub>2</sub>/air <br>fuel latio sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:218px;top:141px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}