with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R51100000000YDAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:121px;top:50px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:180px;top:170px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:257px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR<br>WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:288px;top:54px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR<br>FOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:286px;top:142px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:410px;top:59px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR<br>FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:378px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>LOWER EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:543px;top:12px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL UPPER<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:541px;top:128px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:833px;top:97px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:658px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BUMPER LOWER<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:711px;top:146px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:801px;top:239px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:786px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:802px;top:351px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>CENTER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:803px;top:422px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:814px;top:600px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:637px;top:558px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>CENTER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:728px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JACK-UP STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:502px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:494px;top:733px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:135px;top:614px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:342px;top:635px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:210px;top:738px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:329px;top:737px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:14px;top:439px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:5px;top:375px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:149px;top:268px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEEL<br>ARCH EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:18px;top:241px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR INNER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:18px;top:140px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:439px;top:782px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[DETAIL AREA: A]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:622px;top:804px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:625px;top:904px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE SILL EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:609px;top:971px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE SILL EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:128px;top:987px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:214px;top:1079px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:410px;top:418px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[A]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:817px;top:550px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:671px;top:738px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:589px;top:1087px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}