with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E15E34150300000KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:75px;top:420px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:79px;top:191px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:206px;top:120px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RUBBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:139px;top:53px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER KNOB<br>8 N·m<br>(0.8 kgf·m, 5.8 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:512px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:425px;top:602px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:320px;top:725px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT CABLE CLIP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:185px;top:757px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COTTER PIN<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:462px;top:1057px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COTTER PIN<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:587px;top:1045px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:684px;top:914px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:185px;top:1072px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(P/N 41211-PY5-305)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}