with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:407px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:407px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00J36200000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:407px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:17px;top:24px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:29px;top:83px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>No.28 (7.5 A) FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:30px;top:101px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>No.24 (15 A) FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:17px;top:114px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:29px;top:132px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RELAY MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:117px;top:47px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:283px;top:308px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>SH DISP BUS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:283px;top:289px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DISP BUS (−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:136px;top:215px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:170px;top:174px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:170px;top:192px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:197px;top:160px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:207px;top:150px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:200px;top:179px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:207px;top:169px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:197px;top:197px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:203px;top:187px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:225px;top:218px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:225px;top:226px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(Inside of center<br>module unit)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:283px;top:150px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:282px;top:160px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>R SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:283px;top:168px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:282px;top:179px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>G SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:282px;top:187px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:282px;top:197px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:283px;top:205px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:283px;top:215px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>C SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:283px;top:223px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:283px;top:234px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GND SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:283px;top:242px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:283px;top:252px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>SH SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:283px;top:260px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:283px;top:270px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DISP BUS (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:282px;top:279px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:283px;top:297px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:227px;top:340px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:159px;top:335px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>LF<br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:159px;top:353px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RF<br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:200px;top:343px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>LF SP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:200px;top:362px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RF SP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:283px;top:344px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RG L (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:283px;top:334px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:283px;top:362px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GND RG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:283px;top:352px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:679px;top:53px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BACK LT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:697px;top:42px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:692px;top:89px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:696px;top:78px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:694px;top:117px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:696px;top:107px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:691px;top:138px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>ILL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:696px;top:127px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:688px;top:160px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>R SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:695px;top:150px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:687px;top:178px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>G SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:695px;top:169px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:688px;top:196px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:692px;top:187px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:688px;top:215px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>C SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:692px;top:205px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:678px;top:234px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GND SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:690px;top:224px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:684px;top:252px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>SH SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:694px;top:242px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:659px;top:270px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DISP BUS (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:692px;top:260px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:660px;top:289px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DISP BUS (−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:691px;top:279px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:666px;top:309px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>SH DISP BUS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:695px;top:297px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:676px;top:343px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RG L (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:693px;top:334px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:679px;top:362px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GND RG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:693px;top:353px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:686px;top:380px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>SH RG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:696px;top:371px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:721px;top:202px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:793px;top:52px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>VSP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:793px;top:43px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:793px;top:95px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DIAG P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:793px;top:84px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:834px;top:47px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:793px;top:113px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DIAG N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:793px;top:103px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:837px;top:72px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>NAVIGATION SERVICE<br>CHECK CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:867px;top:38px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>ECM<br>(VEHICLE<br>SPEED<br>SIGNAL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:793px;top:138px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:793px;top:128px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:834px;top:133px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:855px;top:155px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:787px;top:153px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GPS ANTENNA<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:793px;top:179px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:793px;top:169px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:793px;top:197px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>SH GPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:793px;top:187px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:865px;top:179px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GPS<br>ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:340px;top:155px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:341px;top:174px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:340px;top:192px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:341px;top:210px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:341px;top:228px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:341px;top:247px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:639px;top:47px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:638px;top:210px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:638px;top:229px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:638px;top:247px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:33px;top:47px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>No.6 (7.5 A) FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:117px;top:84px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:170px;top:236px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:169px;top:155px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:169px;top:132px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:203px;top:231px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:186px;top:241px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>ILL (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:283px;top:326px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RG R (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:283px;top:316px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:341px;top:265px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:341px;top:283px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:341px;top:302px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:340px;top:321px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:341px;top:338px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:341px;top:358px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:638px;top:84px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:638px;top:112px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:639px;top:132px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:638px;top:155px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:639px;top:174px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:638px;top:192px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:638px;top:265px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:638px;top:283px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:639px;top:301px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:638px;top:322px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:639px;top:357px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:639px;top:339px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:638px;top:375px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:696px;top:317px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:676px;top:326px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RG R (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:834px;top:89px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:834px;top:107px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:117px;top:101px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:170px;top:267px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:186px;top:273px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>ILL (−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:203px;top:262px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:46px;top:260px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>DASHLIGHTS<br>BRIGHTNESS<br>CONTROLLER<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}