with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:640px;position:relative;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E2K000000000000EBA202.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:531px;top:652px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:531px;top:669px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:539px;top:669px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOES UNIT ‹26−B› ‹29−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:563px;top:628px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:369px;top:683px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:264px;top:683px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:203px;top:683px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:475px;top:177px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:475px;top:160px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:507px;top:201px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:319px;top:201px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:316px;top:239px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:619px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:200px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:261px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:365px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:627px;top:854px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:624px;top:904px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:621px;top:727px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:560px;top:727px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:499px;top:727px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:433px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:504px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:504px;top:239px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:560px;top:599px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:22px;top:394px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:16px;top:348px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LCD BACK LIGHT (LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:110px;top:348px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POINTER LIGHT (LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:116px;top:394px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:17px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>EEPROM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:106px;top:497px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LCD DISPLAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:212px;top:397px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOBILIZER <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:273px;top:397px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:378px;top:380px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DOOR/TAILGATE <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:590px;top:495px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRAKE SYSTEM <br>CHECK CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:539px;top:652px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY <br>CONTROL UNIT ‹9−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:181px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOBILIZER <br>CONTROL <br>UNIT−RECIEVER <br>‹26−C› ‹29−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:251px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY <br>CONTROL <br>UNIT <br>‹9−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:357px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>SWITCH <br>‹8−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:450px;top:796px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:517px;top:796px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT <br>REAR  <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:578px;top:796px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT <br>REAR  <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:639px;top:796px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TAILGATE <br>LATCH <br>SWITCH <br>(Closed : <br>Tailgate open)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:483px;top:177px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SECURITY <br>CONTROL UNIT ‹9−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:483px;top:159px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>INTEGRATED <br>CONTROL UNIT ‹8−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:299px;top:169px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER WINDOW <br>MASTER SWITCH <br>‹10−A›<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}