with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:911px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E10E34116317081LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:514px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLAVE CYLINDER BODY<br></b>Check the cylinder wall<br>for scoring and wear.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:630px;top:126px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:699px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLEEDER SCREW<br>8 N·m (0.8 kgf·m, 5.8 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:753px;top:132px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLEEDER SCREW CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:230px;top:84px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLAVE CYLINDER SPRING<br></b>Install with small end facing piston.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:89px;top:132px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(Brake Assembly Lube)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:138px;top:327px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PISTON CUP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:52px;top:453px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLAVE CYLINDER PISTON<br></b>Check for wear and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:588px;top:557px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BOOT<br></b>Check that it is fitted securely <br>over the cylinder body.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:124px;top:701px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUSH ROD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:401px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Urea Grease UM264<br>(P/N 41211-PY5-305)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:644px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(Brake Assembly Lube)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:630px;top:88px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>CONNECTOR<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}