with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E00R51100000000YDAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:681px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: J]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:630px;top:36px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br>(Without rear inner fender)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:210px;top:485px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: H]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:144px;top:504px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT FRONT WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:545px;top:485px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: I]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:482px;top:504px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT FRONT WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:253px;top:792px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: K]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:626px;top:792px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[SECTION: LL]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:630px;top:268px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br>(With rear inner fender)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:466px;top:224px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[J]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:435px;top:238px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[K]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:248px;top:367px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[I]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:76px;top:270px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[H]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:502px;top:1038px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:707px;top:1077px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR INNER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:471px;top:155px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:468px;top:197px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}