with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1017px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1017px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E1JE34150339091MFAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1017px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:664px;top:149px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DUST COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:659px;top:534px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:271px;top:169px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT <br>ARM <br>COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:298px;top:887px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELECT STOP<br>PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:723px;top:703px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:665px;top:412px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHANGE LEVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:16px;top:278px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m<br>(1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:234px;top:320px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:437px;top:101px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DUST SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:614px;top:88px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELECT LEVER<br></b>Be careful not to damage the dust seal<br>when installing it.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:392px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BREATHER CAP<br></b>Turn the arrow toward the front<br>of the vehicle, and install it.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:768px;top:750px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 mm SPRING WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:783px;top:792px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 mm SPECIAL BOLT<br>31 N·m <br>(3.2 kgf·m, 23 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:677px;top:655px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTERLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:99px;top:866px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:294px;top:663px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SCREW<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:183px;top:501px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BREATHER PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:37px;top:799px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Stake<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:426px;top:601px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST/2ND <br>SELECT<br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:257px;top:824px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5TH/6TH<br>SELECT<br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:419px;top:482px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:208px;top:249px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT <br>LOCK<br>CAM A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:14px;top:542px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE LOCKOUT<br>SOLENOID<br></b>Apply liquid gasket <br>(P/N 08C70-K0234M) to<br>the sealing surface.<br></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:777px;top:927px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MBS RETURN SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:818px;top:973px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MBS ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:391px;top:346px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(P/N 41211-PY5-305)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:691px;top:231px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(P/N 41211-PY5-305)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}