with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:640px;position:relative;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2K000000000000EBA126.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:264px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:264px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:264px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:264px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:608px;top:305px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:611px;top:267px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>63<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:553px;top:444px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:552px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:626px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RESUME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:572px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CANCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:533px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:572px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:583px;top:661px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>71<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:372px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:415px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:459px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:412px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MAP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:96px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:141px;top:99px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:180px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:180px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:101px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:141px;top:110px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:71px;top:55px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>K20A9 engine (3/3) :<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:23px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:71px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>ECM, Cruise Control, Immobilizer System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:571px;top:599px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THROTTLE <br>ACTUATOR <br>CONTROL <br>MODULE <br>RELAY <br>‹24−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:520px;top:309px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE <br>CONTROL SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:600px;top:235px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HORN <br>SWITCH <br>‹18−C›<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}