with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:495px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:495px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E300000000K0081BAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:495px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:192px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:179px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:303px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:16px;top:163px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:16px;top:134px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:325px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:16px;top:231px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:43px;top:68px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:880px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:15px;top:199px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:880px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:421px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:566px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:815px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:124px;top:449px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:44px;top:343px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:483px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:275px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:417px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:376px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:271px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:360px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:576px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:16px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}