with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:369px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:369px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00K71100087090FAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:369px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:60px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT CONNECTOR B (20P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:126px;top:33px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:71px;top:320px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>AIR MIX CONTROL MOTOR 5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:125px;top:338px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:268px;top:272px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:106px;top:59px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:217px;top:58px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:188px;top:154px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:256px;top:155px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:54px;top:91px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:243px;top:292px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:172px;top:272px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:300px;top:225px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:132px;top:240px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}