with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:520px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:520px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00D10600000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:520px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:35px;top:35px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:17px;top:20px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:12px;top:41px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:51px;top:51px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 14 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:51px;top:67px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 18 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:51px;top:116px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:51px;top:146px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 2 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:102px;top:38px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE PEDAL POSITION SWITCH<br>Closed: Brake pedal pressed<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:132px;top:53px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:150px;top:53px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:113px;top:60px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:162px;top:60px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:167px;top:91px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:232px;top:58px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE<br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:188px;top:115px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:194px;top:132px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:195px;top:166px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 3 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:246px;top:139px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:241px;top:130px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:241px;top:167px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:162px;top:75px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:42px;top:227px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 15 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:42px;top:242px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 3 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:256px;top:272px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:157px;top:271px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:138px;top:355px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:91px;top:365px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:59px;top:349px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:235px;top:259px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:235px;top:274px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:256px;top:302px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:235px;top:289px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:235px;top:304px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:256px;top:333px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:235px;top:319px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:235px;top:335px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:256px;top:363px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:235px;top:349px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:235px;top:365px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:167px;top:289px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:167px;top:350px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:91px;top:381px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:91px;top:395px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:91px;top:410px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:91px;top:426px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:136px;top:446px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:113px;top:387px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:113px;top:402px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:113px;top:417px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:113px;top:432px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:351px;top:110px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:279px;top:102px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:275px;top:118px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE SYSTEM<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:275px;top:185px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ABS INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:351px;top:126px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:351px;top:139px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:351px;top:195px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:390px;top:143px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE FLUID<br>LEVEL SWITCH<br>Closed: Low fluid<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:400px;top:201px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:400px;top:219px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:400px;top:250px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:400px;top:265px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:400px;top:280px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:400px;top:295px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:400px;top:310px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:400px;top:326px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:400px;top:341px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:396px;top:356px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:400px;top:402px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:400px;top:371px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:400px;top:387px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:318px;top:372px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:318px;top:341px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:441px;top:150px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:441px;top:137px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:747px;top:86px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:750px;top:129px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:747px;top:178px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:747px;top:215px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:747px;top:245px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:744px;top:223px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:607px;top:129px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PARKING<br>BRAKE SWITCH<br>Closed:<br>Parking<br> brake applied<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:739px;top:95px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>STOP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:743px;top:138px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>EBD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:737px;top:187px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WALP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:732px;top:239px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B-FSR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:702px;top:133px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:702px;top:183px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:702px;top:219px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:702px;top:234px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:702px;top:91px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:804px;top:91px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DTC<br>EEPROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:800px;top:62px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ABS MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:786px;top:73px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ABS CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:875px;top:73px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>MODULATOR UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:781px;top:217px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5 V<br>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:818px;top:229px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>To VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:811px;top:241px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FAIL-SAFE RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:788px;top:257px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUMP MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:747px;top:276px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:747px;top:261px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:747px;top:230px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:747px;top:337px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:747px;top:321px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:749px;top:306px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:749px;top:291px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:734px;top:254px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B-MR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:737px;top:269px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:733px;top:284px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FL-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:736px;top:299px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:733px;top:315px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FR-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:736px;top:330px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:702px;top:250px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:702px;top:265px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:702px;top:280px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:702px;top:295px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:702px;top:310px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:702px;top:326px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:780px;top:274px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:771px;top:291px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:771px;top:318px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:750px;top:397px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:747px;top:382px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:747px;top:367px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:750px;top:352px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:747px;top:443px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:747px;top:462px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:738px;top:451px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GND1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:738px;top:470px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GND2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:743px;top:390px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:733px;top:345px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RL-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:736px;top:360px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:732px;top:375px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RR-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:734px;top:406px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>DIAG-K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:702px;top:447px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:702px;top:341px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:698px;top:356px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:702px;top:402px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:702px;top:387px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:702px;top:466px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:771px;top:364px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:793px;top:380px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:819px;top:408px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>TXD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:819px;top:426px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RXD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:702px;top:371px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:625px;top:117px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:400px;top:168px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:400px;top:132px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:400px;top:117px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:400px;top:234px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:318px;top:326px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:400px;top:183px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:400px;top:91px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:246px;top:90px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:168px;top:417px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:113px;top:371px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:318px;top:356px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:169px;top:138px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:129px;top:123px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:148px;top:134px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:122px;top:138px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:96px;top:138px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:876px;top:242px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SOLENOIDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:876px;top:254px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:874px;top:295px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:878px;top:337px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:877px;top:379px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:879px;top:429px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUMP MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:894px;top:455px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:899px;top:269px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:899px;top:287px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:899px;top:310px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:899px;top:328px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:898px;top:352px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:898px;top:370px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:898px;top:412px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:898px;top:394px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}