with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:960px; height:991px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:960px;position:relative;height:991px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2AJ54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:960px;height:991px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:726px;top:229px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>TAILLIGHT RELAY<br></b>Wire colors: ORN, WHT,<br>RED and WHT<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:727px;top:117px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>IMMOBILIZER CONTROL<br>UNIT-RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:194px;top:464px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>WINDSHIELD WIPER MOTOR <br>HI/LO RELAY<br></b>Wire colors: GRY, BLU,<br>RED,BRN and YEL<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:625px;top:612px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:650px;top:660px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>INTEGRATED CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:400px;top:867px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:351px;top:900px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:125px;top:900px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>POWER WINDOW RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:80px;top:573px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>SEAT HEATER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:44px;top:867px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>STARTER CUT RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:245px;top:548px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>AIR FUEL RATIO SENSOR RELAY<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}