with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E25F00000047031LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:479px;top:473px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*ROLL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:548px;top:207px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RUBBER SEAL<br>(Black color)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:261px;top:448px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLIPPER SEAL<br>(White color)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:193px;top:404px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*OUTER CASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:354px;top:420px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*CAM RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:675px;top:332px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*ROTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:371px;top:193px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP COVER SEALS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:727px;top:372px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*SIDE PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:785px;top:412px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>51.0 x 2.4 mm<br>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:7px;top:764px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23.8 x 2.4 mm<br>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:43px;top:329px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:372px;top:990px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16.7 x 1.8 mm O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:337px;top:549px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12.7 x 1.8 mm O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:337px;top:602px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*PUMP PRELOAD SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:681px;top:737px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BALL BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:494px;top:749px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVESHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:725px;top:784px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40 mm INTERNAL SNAP RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:775px;top:828px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:854px;top:932px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PULLEY NUT<br>64 N·m <br>(6.5 kgf·m,<br>47 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:449px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>11 N·m <br>(1.1 kgf·m, 8.0 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:65px;top:843px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:143px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13 x 1.9 mm O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:332px;top:161px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INLET JOINT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:405px;top:676px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:1px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Replace the pump as an assembly if the parts indicated with asterisk (*) are worn or damaged.<br></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:640px;top:277px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VANES<br>(11 plates)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:628px;top:277px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:40px;top:463px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP HOUSING CAP<br>29 N·m<br>(3.0 kgf·m, 22 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:28px;top:463px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:111px;top:953px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE CONTROL<br>VALVE SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:100px;top:953px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:93px;top:1055px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:82px;top:1056px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:383px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE CONTROL VALVE CAP<br>49 N·m (5.0 kgf·m, 36 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:372px;top:1043px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}