with(document) {
write("<div id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1121px;\">");
write("<div id=\"rect3\"class=\"drag\" style=\"width:950px;position:relative;height:1121px;\">");
write("<img id=\"img3\" src=\"../img/SJD5E2AJ54260400000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1121px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:116px;top:27px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:98px;top:100px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:167px;top:655px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.8 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:167px;top:791px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:587px;top:806px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Integrated control unit (IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:134px;top:100px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:177px;top:100px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:216px;top:119px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:435px;top:213px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:587px;top:214px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (MAIN RLY−)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:587px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Air fuel ratio sensor*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:427px;top:420px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:216px;top:327px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.25 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:428px;top:484px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:587px;top:485px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (LAF R)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:422px;top:520px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:336px;top:520px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:587px;top:699px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Primary O<sub>2</sub> sensor*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:587px;top:685px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Vehicle speed sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:587px;top:671px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Alternator<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:417px;top:670px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:385px;top:795px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:587px;top:835px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Combination light switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:428px;top:834px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:428px;top:863px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:587px;top:863px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Keyless receiver unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:587px;top:892px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge assembly<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:428px;top:891px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:587px;top:906px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b> <br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:134px;top:1043px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:98px;top:1043px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:164px;top:969px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.11 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:156px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:587px;top:521px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Imoes control unit*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:422px;top:549px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:500px;top:548px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:587px;top:549px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Immobilizer control unit−receiver*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:488px;top:584px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:422px;top:584px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:587px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CKP sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:587px;top:599px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CMP sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:587px;top:585px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (IGP)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:585px;top:757px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:616px;top:756px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ELD unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:587px;top:878px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Security control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:419px;top:985px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:587px;top:985px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light relay<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:673px;top:28px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*1 : K20A9 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:344px;top:670px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:429px;top:755px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:585px;top:643px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:422px;top:641px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:501px;top:834px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:587px;top:920px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight adjuster switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:428px;top:920px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:501px;top:948px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:500px;top:920px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:587px;top:963px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlight adjuster unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:587px;top:949px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlight adjuster unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:673px;top:39px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2 : D17A2 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:587px;top:728px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Reverse lockout solenoid*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:223px;top:176px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PGM−FI <br>MAIN RELAY1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:616px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:215px;top:376px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AIR FUEL RATIO <br>SENSOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:587px;top:713px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Evap canister purge valve<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}