with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:1900px;position:relative;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E2K000000000000EBAD23.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:958px;top:376px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:958px;top:395px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:965px;top:385px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:958px;top:402px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:1742px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:1742px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:853px;top:468px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:935px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:935px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:935px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:935px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:1696px;top:164px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:1696px;top:173px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:1762px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:1717px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:1706px;top:209px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[  ] : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:486px;top:887px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[G502]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:1032px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[ORN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:987px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[WHT]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:727px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[PUR]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:683px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:639px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[BRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:590px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[LT BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:533px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[ORN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:489px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[RED]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:445px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:401px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[YEL]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:284px;top:476px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>[ORN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:165px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:165px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:163px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:124px;top:100px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:79px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:65px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:124px;top:89px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:120px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:79px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:124px;top:77px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:1762px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:1762px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:1762px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:1806px;top:100px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:1805px;top:77px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:1715px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:1717px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:1820px;top:89px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:1706px;top:191px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : Under−hood fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:1706px;top:200px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : Under−dash fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:1837px;top:37px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:23px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:1575px;top:423px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:733px;top:706px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:688px;top:706px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>68<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:1440px;top:682px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:1356px;top:682px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:1173px;top:682px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:1223px;top:682px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:1267px;top:682px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:344px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G304<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:488px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:1130px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:1078px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:71px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:940px;top:566px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:400px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G304<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:348px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:485px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:348px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:403px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:398px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:447px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:729px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:685px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:363px;top:296px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:363px;top:305px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:384px;top:304px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:323px;top:303px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:300px;top:305px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:302px;top:296px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:851px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:895px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:685px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:730px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:492px;top:782px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:597px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:642px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:536px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:491px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:286px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:940px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:891px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:802px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:846px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:1223px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:1178px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:1401px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:1355px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:1445px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:1483px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:1267px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:1311px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:1223px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:1178px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:1267px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:1312px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:1350px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:1401px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:991px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:1034px;top:466px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:1084px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:1034px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:1489px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:1444px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:1572px;top:472px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:758px;top:403px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:411px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>AIRBAG <br>FIRST <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:500px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>AIRBAG <br>SECOND <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:609px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>AIRBAG <br>FIRST <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:697px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>AIRBAG <br>SECOND <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:812px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT SIDE <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:906px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT SIDE <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:1001px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT [LEFT] <br>SIDE <br>OUTER LAP  <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:1095px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CENTER <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:1189px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT SIDE <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:1365px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT SIDE <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:1277px;top:337px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT SIDE <br>IMPACT <br>SENSOR <br>(FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:1454px;top:337px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT SIDE <br>IMPACT <br>SENSOR <br>(FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:1561px;top:381px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SRS <br>INDICATOR <br>CIRCUIT <br>‹3−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:520px;top:708px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MEMORY <br>ERASE <br>SIGNAL <br>(MES) <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:684px;top:736px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>‹26−D› ‹29−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:859px;top:741px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT FRONT <br>IMPACT <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:1048px;top:741px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT FRONT <br>IMPACT <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:1190px;top:736px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT SIDE <br>IMPACT <br>SENSOR <br>(SECOND)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:1367px;top:736px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT SIDE <br>IMPACT <br>SENSOR <br>(SECOND)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:1279px;top:775px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT SIDE <br>CURTAIN <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:1457px;top:775px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT SIDE <br>CURTAIN <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}