with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R41100000000YDAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:124px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L, l<br>Front Seat Side Mount<br>Hole 15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:504px;top:46px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>M, m<br>Rear Damper Mount<br>Hole 11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:334px;top:264px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:424px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:426px;top:790px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1672<br>(65.83)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:332px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1178 (46.38)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:630px;top:759px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:470px;top:936px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:522px;top:310px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:613px;top:309px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:532px;top:714px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1113<br>(43.82)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:343px;top:877px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1264<br>(49.76)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:446px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>m<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:251px;top:808px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>l<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:0px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}