with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:831px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00D14313514832EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:594px;top:84px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:432px;top:92px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:162px;top:95px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:130px;top:20px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:164px;top:120px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:380px;top:134px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:503px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:602px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:709px;top:134px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:254px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:449px;top:124px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:271px;top:288px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE<br>ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:229px;top:762px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G201: (KE)<br>G302: (KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:284px;top:625px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE FLUID<br>LEVEL SWITCH<br>CLOSED: Float down<br>OPEN: Float up<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:248px;top:691px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:246px;top:564px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:286px;top:351px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE SYSTEM<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:506px;top:624px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PARKING BRAKE<br>SWITCH<br>CLOSED: Lever up<br>OPEN: Lever down<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:471px;top:564px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:571px;top:456px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ABS MODULATOR-CONTROL UNIT or<br>VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}