with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:863px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R21100000000YCAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:45px;top:254px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT BUMPER<br></b>Body color<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:555px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR MIRROR HOUSING<br></b>Body color<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:235px;top:769px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR OUTER HANDLES<br></b>Chrome plated<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:700px;top:781px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR BUMPER<br></b>Body color<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:71px;top:138px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT GRILLE<br></b>Silver metallic (NH-627M)<br>or black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:71px;top:182px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MOLDING<br></b>Chrome plated<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:129px;top:74px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WINDSHIELD SIDE MOLDING<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:257px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WINDSHIELD UPPER MOLDING<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:529px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF RAIL<br></b>NH-666<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:638px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR OUTER SASH TAPE<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:683px;top:93px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR DOOR SASH TRIM<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:675px;top:272px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR MOLDINGS<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:618px;top:327px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR LOWER MOLDINGS<br></b>Body color or black (NH-533 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:492px;top:416px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT CORNER TRIM<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:283px;top:434px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT BUMPER LID<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:70px;top:398px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT BUMPER LOWER GRILLE<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:524px;top:465px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE HINGE COVER<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:732px;top:505px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE SPOILER<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:749px;top:560px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WIPER<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:751px;top:724px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LICENSE PLATE TRIM<br></b>Chrome plated<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:561px;top:820px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL DOOR<br></b>Body color<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}