with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E10E34116300000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:251px;top:13px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH PEDAL POSITION SWITCH<br><a href=\"javascript:parent.Cts('000000000000874','i000')\"></b>Adjustment,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:26px;top:377px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH PEDAL<br><a href=\"javascript:parent.Cts('000000000000874','i000')\"></b>Adjustment,</a><br><a href=\"javascript:parent.Cts('000000000000873','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:206px;top:319px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:381px;top:58px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PEDAL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:472px;top:82px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RESERVOIR HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:690px;top:127px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RESERVOIR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:458px;top:250px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RETAINING<br>CLIP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:400px;top:436px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:466px;top:360px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH MASTER CYLINDER<br><a href=\"javascript:parent.Cts('000000000000740','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000741','i000')\">Installation,</a><br><a href=\"javascript:parent.Cts('000000000000872','i000')\">Overhaul,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:279px;top:475px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:708px;top:740px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLYWHEEL<br><a href=\"javascript:parent.Cts('000000000000674','iR02')\"></b>Inspection,</a><br><a href=\"javascript:parent.Cts('000000000000674','iR03')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:645px;top:802px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH DISC<br><a href=\"javascript:parent.Cts('000000000000674','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000674','iR04')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:565px;top:867px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE PLATE<br><a href=\"javascript:parent.Cts('000000000000674','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000674','iR04')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:546px;top:926px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RELEASE BEARING<br><a href=\"javascript:parent.Cts('000000000000674','iR05')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:520px;top:965px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:376px;top:1029px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLAVE CYLINDER<br><a href=\"javascript:parent.Cts('000000000000675','i000')\"></b>Replacement,</a><br><a href=\"javascript:parent.Cts('000000000000842','i000')\">Overhaul,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:465px;top:1002px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROLL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:77px;top:443px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:0px;top:1074px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>RHD type is shown, LHD type is similar.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}