with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R31100000000YDAD34.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:546px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:267px;top:216px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:653px;top:329px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR INNER UPPER PILLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:672px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR INNER UPPER PILLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:137px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR UPPER<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:106px;top:908px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR UPPER<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:362px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT ROOF<br>RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:497px;top:870px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR ROOF<br>RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:370px;top:997px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MOUNTING BOLT<br>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:665px;top:996px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MOUNTING BOLTS<br>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}