with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:1039px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E2AG10100050652KBAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:37px;top:900px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Discharge hose to the A/C compressor (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:37px;top:996px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C compressor bracket to the engine block (10 x 1.25 mm): 44 N·m (4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:37px;top:916px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Discharge hose to the A/C condenser (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:37px;top:932px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Receiver line to the A/C condenser (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:37px;top:964px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Suction hose to the A/C compressor (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:37px;top:948px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C line to the evaporator (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:14px;top:900px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:14px;top:916px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:14px;top:932px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:14px;top:948px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:14px;top:964px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:14px;top:980px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:14px;top:996px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:510px;top:566px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:622px;top:662px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C COMPRESSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:243px;top:368px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISCHARGE HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:783px;top:444px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:313px;top:400px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:313px;top:308px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:575px;top:636px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:504px;top:518px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:493px;top:53px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:613px;top:853px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:517px;top:80px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:610px;top:489px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUCTION HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:37px;top:980px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C compressor to the A/C compressor bracket and water passage (8 x 1.25 mm): 22 N·m (2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:565px;top:518px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C CONDENSER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:0px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE: RHD type is shown, LHD type is similar.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}