with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:475px; height:417px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:475px;position:relative;height:417px;\">");
write("<img id=\"img2\" src=\"../img/SJD5E00J26220200000KDAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:417px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:348px;top:321px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, <br>7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:326px;top:18px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:423px;top:223px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:421px;top:171px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:383px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:265px;top:376px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:97px;top:345px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:64px;top:167px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}