with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:799px;\">");
write("<img id=\"img1\" src=\"../img/SJD5E00R11100000000YCAD14.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:83px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>:New high-tension steel sheet<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:256px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:568px;top:109px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CENTER ROOF ARCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:355px;top:109px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF SIDE RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:683px;top:186px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF SIDE STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:823px;top:282px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:706px;top:602px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR SIDE EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:649px;top:644px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CENTER PILLAR STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:591px;top:681px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:539px;top:721px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:466px;top:766px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR LOWER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:340px;top:731px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:119px;top:321px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR<br>INNER LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:175px;top:238px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PILLAR<br>INNER UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:42px;top:403px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:11px;top:702px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br>LOWER EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:61px;top:753px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME EXTENSION<br>REAR<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}