with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9UF00000047031LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:479px;top:276px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*ROLL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:463px;top:214px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RUBBER SEAL<br>(Black color)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:351px;top:385px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLIPPER SEAL<br>(White color)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:469px;top:471px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*CAM RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:625px;top:328px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*ROTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:390px;top:177px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP COVER SEALS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:702px;top:346px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*SIDE PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:779px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>51.0 x 2.4 mm<br>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:70px;top:743px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23.8 x 2.4 mm<br>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:411px;top:960px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16.7 x 1.8 mm O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:355px;top:561px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12.7 x 1.8 mm O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:351px;top:638px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*PUMP PRELOAD SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:578px;top:737px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BALL BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:488px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVESHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:622px;top:795px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40 mm <br>INTERNAL SNAP RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:810px;top:861px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:841px;top:907px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PULLEY NUT<br>64 N·m <br>(6.5 kgf·m,<br>47 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:408px;top:87px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>11 N·m <br>(1.1 kgf·m, 8.0 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:99px;top:839px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*PUMP HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:155px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13 x 1.9 mm O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:422px;top:146px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INLET JOINT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:393px;top:683px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:640px;top:264px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VANES<br>(11 plates)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:629px;top:264px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:113px;top:462px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PUMP HOUSING CAP<br>29 N·m<br>(3.0 kgf·m, 22 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:101px;top:462px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:137px;top:918px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE CONTROL<br>VALVE SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:126px;top:918px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:137px;top:1025px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:126px;top:1025px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:431px;top:1021px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE CONTROL <br>VALVE CAP<br>49 N·m (5.0 kgf·m, 36 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:420px;top:1021px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:17px;top:144px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>20 N·m <br>(2.0 kgf·m, <br>14 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:235px;top:343px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13 x 1.9 mm<br>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:78px;top:304px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*PUMP COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:285px;top:444px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*OUTER CASE<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}