with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:927px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9UD52100063635KDAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:488px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To-right rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:595px;top:48px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To-left front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:601px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLARE NUTS<br>15 N·m <br>(1.5 kgf·m, 11 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:382px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To-left rear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:316px;top:63px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To-right front<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:353px;top:512px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:227px;top:594px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:827px;top:570px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:361px;top:672px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:284px;top:173px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:771px;top:377px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLARE NUTS<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:800px;top:478px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 mm NUTS<br>8 N·m <br>(0.8 kgf·m, 6 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:744px;top:813px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 mm BOLTS<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}