with(document) {
write("<div id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect3\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img3\" src=\"../img/SJD6E8JA20300000000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:649px;top:201px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:649px;top:160px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:649px;top:94px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:737px;top:287px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:844px;top:53px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:844px;top:86px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:715px;top:119px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:715px;top:153px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:617px;top:252px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:617px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:617px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:617px;top:67px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:698px;top:21px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:478px;top:302px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:451px;top:302px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:844px;top:120px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:506px;top:302px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:505px;top:22px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:450px;top:22px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:649px;top:216px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:617px;top:134px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:617px;top:224px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:617px;top:209px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:773px;top:368px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:614px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:650px;top:372px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:614px;top:365px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:650px;top:357px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:614px;top:350px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:650px;top:342px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:200px;top:328px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:200px;top:343px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:200px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:200px;top:388px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELDGND<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:248px;top:336px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:248px;top:379px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:323px;top:327px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17 (13)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:320px;top:356px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br>(14)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:261px;top:301px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P CONNECTOR<br>(17P CONNECTOR)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:200px;top:244px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:200px;top:260px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:235px;top:252px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:311px;top:243px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15 (10)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:253px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P CONNECTOR<br>(17P CONNECTOR)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:716px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:716px;top:671px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:762px;top:548px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:200px;top:464px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:200px;top:481px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGP1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:231px;top:472px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:200px;top:496px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:200px;top:513px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGP2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:231px;top:504px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:200px;top:527px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:200px;top:544px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGP3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:231px;top:535px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:286px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:338px;top:464px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:338px;top:495px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:338px;top:527px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:319px;top:436px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:360px;top:472px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:360px;top:504px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:360px;top:535px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:411px;top:462px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" class=\"drag\" style=\"position:absolute;left:430px;top:462px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" class=\"drag\" style=\"position:absolute;left:449px;top:462px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" class=\"drag\" style=\"position:absolute;left:468px;top:462px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" class=\"drag\" style=\"position:absolute;left:417px;top:396px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" class=\"drag\" style=\"position:absolute;left:376px;top:407px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" class=\"drag\" style=\"position:absolute;left:314px;top:616px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" class=\"drag\" style=\"position:absolute;left:240px;top:602px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" class=\"drag\" style=\"position:absolute;left:205px;top:601px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" class=\"drag\" style=\"position:absolute;left:623px;top:490px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" class=\"drag\" style=\"position:absolute;left:641px;top:530px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" class=\"drag\" style=\"position:absolute;left:500px;top:565px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br>(11)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" class=\"drag\" style=\"position:absolute;left:641px;top:582px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" class=\"drag\" style=\"position:absolute;left:641px;top:602px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" class=\"drag\" style=\"position:absolute;left:641px;top:623px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" class=\"drag\" style=\"position:absolute;left:641px;top:642px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" class=\"drag\" style=\"position:absolute;left:587px;top:460px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" class=\"drag\" style=\"position:absolute;left:569px;top:820px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" class=\"drag\" style=\"position:absolute;left:200px;top:678px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" class=\"drag\" style=\"position:absolute;left:200px;top:694px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PTCRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" class=\"drag\" style=\"position:absolute;left:249px;top:686px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" class=\"drag\" style=\"position:absolute;left:200px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" class=\"drag\" style=\"position:absolute;left:200px;top:742px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PTCMON<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" class=\"drag\" style=\"position:absolute;left:252px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" class=\"drag\" style=\"position:absolute;left:186px;top:200px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" class=\"drag\" style=\"position:absolute;left:183px;top:711px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" class=\"drag\" style=\"position:absolute;left:800px;top:1075px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" class=\"drag\" style=\"position:absolute;left:838px;top:1047px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" class=\"drag\" style=\"position:absolute;left:649px;top:773px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" class=\"drag\" style=\"position:absolute;left:615px;top:781px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" class=\"drag\" style=\"position:absolute;left:685px;top:776px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TEST TACHOMETER CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" class=\"drag\" style=\"position:absolute;left:831px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUEL<br>HEATER<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" class=\"drag\" style=\"position:absolute;left:714px;top:887px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" class=\"drag\" style=\"position:absolute;left:717px;top:938px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" class=\"drag\" style=\"position:absolute;left:616px;top:1063px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" class=\"drag\" style=\"position:absolute;left:587px;top:1063px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" class=\"drag\" style=\"position:absolute;left:716px;top:970px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" class=\"drag\" style=\"position:absolute;left:641px;top:809px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" class=\"drag\" style=\"position:absolute;left:641px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" class=\"drag\" style=\"position:absolute;left:641px;top:849px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" class=\"drag\" style=\"position:absolute;left:641px;top:868px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" class=\"drag\" style=\"position:absolute;left:641px;top:954px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" class=\"drag\" style=\"position:absolute;left:641px;top:987px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" class=\"drag\" style=\"position:absolute;left:512px;top:1063px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" class=\"drag\" style=\"position:absolute;left:342px;top:840px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" class=\"drag\" style=\"position:absolute;left:458px;top:844px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" class=\"drag\" style=\"position:absolute;left:458px;top:828px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" class=\"drag\" style=\"position:absolute;left:458px;top:860px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" class=\"drag\" style=\"position:absolute;left:475px;top:929px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" class=\"drag\" style=\"position:absolute;left:307px;top:816px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" class=\"drag\" style=\"position:absolute;left:378px;top:1011px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" class=\"drag\" style=\"position:absolute;left:407px;top:944px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" class=\"drag\" style=\"position:absolute;left:248px;top:1051px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: LHD model<br>*2: RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" class=\"drag\" style=\"position:absolute;left:17px;top:837px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX:<br>(1)No. 14 +B STOP&amp;HORN (15 A)<br>(2)No. 1 +B GLOW (70 A)<br>(3)No. 1 BATTERY (100 A)<br>(4)No. 23 +B BACK UP (10 A)<br>(5)No. 2 IG1 MAIN (50 A)<br>(6)No. 28 (15 A)<br>(7)No. 25 (15 A)<br>(8)No. 12 +B FUEL MONITOR (30 A)<br>(9)No. 18 FUEL HEATER MONITOR<br>(7.5 A)<br>(10)No. 19 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" class=\"drag\" style=\"position:absolute;left:424px;top:1004px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" class=\"drag\" style=\"position:absolute;left:506px;top:978px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" class=\"drag\" style=\"position:absolute;left:520px;top:996px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" class=\"drag\" style=\"position:absolute;left:505px;top:1029px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" class=\"drag\" style=\"position:absolute;left:363px;top:599px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" class=\"drag\" style=\"position:absolute;left:393px;top:577px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P<br>CONNECTOR<br>(17P<br>CONNECTOR)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" class=\"drag\" style=\"position:absolute;left:457px;top:637px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" class=\"drag\" style=\"position:absolute;left:337px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" class=\"drag\" style=\"position:absolute;left:396px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" class=\"drag\" style=\"position:absolute;left:304px;top:710px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" class=\"drag\" style=\"position:absolute;left:451px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13 (9)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" class=\"drag\" style=\"position:absolute;left:451px;top:724px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7 (1)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" class=\"drag\" style=\"position:absolute;left:390px;top:764px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P CONNECTOR<br>(17P CONNECTOR)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" class=\"drag\" style=\"position:absolute;left:763px;top:660px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY 2<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}