with(document) {
write("<div id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\">");
write("<div id=\"rect4\"class=\"drag\" style=\"width:950px;position:relative;height:543px;\">");
write("<img id=\"img4\" src=\"../img/SJD6E8LA20300000000DBAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:245px;top:469px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:367px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:401px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:455px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:487px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:516px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:606px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:717px;top:205px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:722px;top:358px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:721px;top:386px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:720px;top:414px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:595px;top:512px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:570px;top:512px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:540px;top:511px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:514px;top:511px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:479px;top:511px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:270px;top:492px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS A<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:232px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:732px;top:244px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}