with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:640px;position:relative;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9U000000000000EBA103.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:278px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:569px;top:172px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:569px;top:191px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:513px;top:256px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:517px;top:218px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:453px;top:256px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:456px;top:218px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:568px;top:154px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:40px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:119px;top:89px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:74px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:164px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:426px;top:684px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:364px;top:684px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:305px;top:683px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:367px;top:218px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:138px;top:270px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:180px;top:406px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:142px;top:571px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:142px;top:295px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:455px;top:406px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:364px;top:256px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:299px;top:465px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:224px;top:904px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:227px;top:632px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:227px;top:826px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:302px;top:632px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:360px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:424px;top:634px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:72px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Gauges (Indicator Lights)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:119px;top:144px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:115px;top:135px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:115px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:111px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:112px;top:68px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:77px;top:146px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:165px;top:135px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:166px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:166px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:74px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:119px;top:78px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:184px;top:342px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WATER DRAIN<br>INDICATOR<br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:320px;top:391px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOW FUEL <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:349px;top:185px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY <br>‹4−D› ‹5−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:410px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LIGHT ON <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:238px;top:746px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>SEAT BELT <br>SWITCH <br>(Closed : <br>Belt unbuckled)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:285px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>OUTSIDE AIR <br>TEMPERATURE <br>SENSOR <br>‹20−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:352px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL <br>UNIT<br>‹20−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:412px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR LOCK <br>KNOB SWITCH <br>‹8−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:576px;top:154px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HEADLIGHTS ADJUSTER <br>SWITCH LIGHT ‹6−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:470px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>FOG LIGHT <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:531px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR <br>FOG LIGHT <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:435px;top:185px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>COMBINATION<br>LIGHT SWITCH <br>‹6−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:501px;top:176px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR <br>FOG LIGHT <br>CONTROL <br>UNIT ‹6−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:576px;top:191px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER MIRROR <br>SWITCH LIGHT ‹11−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:576px;top:172px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HAZARD WARNING <br>SWITCH LIGHT ‹7−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:247px;top:342px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SEAT BELT <br>REMINDER <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:161px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:171px;top:746px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FUEL FILTER<br>WATER LEVEL<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:153px;top:683px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU : KE<br>WHT : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:636px;top:705px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ALTERNATOR <br>‹1−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:585px;top:634px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:546px;top:715px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM <br>‹25−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:505px;top:634px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LTGRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:526px;top:504px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE<br>CONTROL<br>INDICATOR<br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:605px;top:504px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE<br>MAIN<br>INDICATOR<br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:489px;top:455px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:638px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:153px;top:900px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G504 : KE<br>G302 : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:162px;top:825px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:510px;top:684px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:589px;top:685px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}