with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:1108px;\">");
write("<img id=\"img2\" src=\"../img/SJD6E8AJ54260400000EAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:592px;top:821px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Immobilizer control unit−receiver*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:592px;top:835px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Inertia switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:592px;top:735px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Secondary O<sub>2</sub>   sensor (RHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:592px;top:74px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*1 : K20A9 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:592px;top:807px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Secondary O<sub>2</sub>   sensor (LHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:592px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (IG1) (RHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:419px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:592px;top:578px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wiper intermittent control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:592px;top:564px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield wiper HI/LO relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:592px;top:550px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield wiper/washer switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:505px;top:549px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:592px;top:757px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Imoes unit*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:592px;top:521px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Auto wiper relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:506px;top:607px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:182px;top:86px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:311px;top:86px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:419px;top:757px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:592px;top:607px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Back−up light switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:420px;top:606px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:505px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:505px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:413px;top:285px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:226px;top:979px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:182px;top:979px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:592px;top:792px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (IG1) (LHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:419px;top:792px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:419px;top:864px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:592px;top:864px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Fuel pump<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:419px;top:942px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:592px;top:942px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (FLR)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:592px;top:685px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Inertia switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:420px;top:685px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:212px;top:670px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.7 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:211px;top:592px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.6 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:592px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield washer motor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:212px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.5 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:420px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:281px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.21 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:419px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:419px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:419px;top:321px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:419px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:281px;top:306px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.20 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:413px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:281px;top:234px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.19 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:147px;top:979px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:503px;top:228px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:420px;top:170px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:63px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:146px;top:86px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:168px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:37px;top:55px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER WINDOW <br>MASTER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:195px;top:133px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER <br>WINDOW RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:592px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's power window motor <br>(Via front passenger's power window switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:592px;top:285px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's power window motor <br>(Via front passenger's power window switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:592px;top:321px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear power window motor <br>(Via left rear power window switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:592px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear power window motor <br>(Via left rear power window switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:592px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear power window motor <br>(Via right rear power window switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:592px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear power window motor <br>(Via right rear power window switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:592px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield wiper motor <br>(Via windshield washer switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:256px;top:819px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PGM−FI <br>MAIN RELAY2<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}