with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:927px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9JE34150200000LDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:799px;top:893px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SYNCHRO SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:362px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:347px;top:781px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:788px;top:128px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BALL BEARING<br></b>Check for wear<br>and operation.<br>Note the direction<br>of installation.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:816px;top:561px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2ND GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:332px;top:251px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SYNCHRO SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:337px;top:159px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST/2ND <br>SYNCHRO HUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:352px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST/2ND <br>SYNCHRO SLEEVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:353px;top:450px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b>Check for wear and <br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:784px;top:630px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b>Check for wear and <br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:824px;top:414px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:828px;top:360px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:832px;top:487px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3RD GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:798px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISTANCE COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:344px;top:308px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRIPLE CONE SYNCHRO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:375px;top:549px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT<br>REVERSE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:807px;top:818px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRIPLE CONE <br>SYNCHRO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:823px;top:297px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:817px;top:260px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35 mm SHIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:754px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20 mm SPECIAL BOLT<br></b>NOTE: Left hand threads<br>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:754px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>118 N·m (12.0 kgf·m, <br>86.8 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}