with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:554px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E8JD52100000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:129px;top:331px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:13px;top:423px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:80px;top:427px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:40px;top:438px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:40px;top:488px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:202px;top:319px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:202px;top:336px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:202px;top:353px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:202px;top:369px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:202px;top:403px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:202px;top:387px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:202px;top:437px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:202px;top:420px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:214px;top:333px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:214px;top:367px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:214px;top:401px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:214px;top:435px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:40px;top:455px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:40px;top:471px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:349px;top:426px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:352px;top:392px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:353px;top:460px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:264px;top:392px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:264px;top:409px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:264px;top:426px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:264px;top:443px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:352px;top:308px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:353px;top:291px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:61px;top:443px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:61px;top:460px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:61px;top:477px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:320px;top:260px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:279px;top:260px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:33px;top:31px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:14px;top:15px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:12px;top:37px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:38px;top:49px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 14 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:37px;top:84px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 20 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:38px;top:122px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:40px;top:180px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 2 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:33px;top:284px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 15 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:35px;top:301px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 3 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:265px;top:36px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:180px;top:176px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 3<br>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:180px;top:146px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 9<br>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:166px;top:128px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:113px;top:174px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:131px;top:184px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:130px;top:47px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:146px;top:47px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:100px;top:34px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE PEDAL POSITION SWITCH<br>Closed: Brake pedal pressed<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:170px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:206px;top:54px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE<br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:238px;top:58px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:103px;top:56px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:127px;top:91px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:130px;top:107px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:107px;top:188px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:150px;top:188px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:242px;top:100px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:269px;top:48px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA ACTIVATION<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:270px;top:72px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:270px;top:114px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ABS INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:270px;top:155px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE SYSTEM<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:353px;top:63px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:334px;top:57px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:334px;top:91px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:334px;top:133px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:334px;top:164px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:334px;top:180px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:334px;top:197px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:334px;top:222px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:369px;top:250px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:388px;top:250px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G201: (KE)<br>G302: (KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:407px;top:207px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE FLUID<br>LEVEL SWITCH<br>Closed: Low fluid<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:395px;top:231px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:353px;top:97px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:353px;top:186px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:353px;top:273px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:352px;top:203px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:353px;top:169px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:352px;top:139px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:353px;top:227px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:82px;top:188px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:225px;top:260px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:214px;top:247px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:190px;top:260px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:178px;top:247px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:178px;top:273px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(KE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:214px;top:273px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:251px;top:243px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:143px;top:350px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:144px;top:418px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:151px;top:56px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:765px;top:202px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>CAN<br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:710px;top:314px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>5 V<br>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:683px;top:307px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VALVE<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:671px;top:340px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUMP MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:765px;top:230px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>MODULATOR UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:775px;top:240px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PRESSURE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:771px;top:491px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUMP MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:688px;top:35px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:714px;top:47px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:728px;top:63px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>DTC<br>EEPROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:689px;top:108px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:673px;top:271px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>5 V<br>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:722px;top:301px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:694px;top:421px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:671px;top:368px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:660px;top:386px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:660px;top:403px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:631px;top:320px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:631px;top:337px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:631px;top:354px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:631px;top:371px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:631px;top:388px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:631px;top:405px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:631px;top:422px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:635px;top:439px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:631px;top:456px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:631px;top:480px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:631px;top:499px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:619px;top:312px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>MR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:622px;top:329px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:618px;top:346px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FL-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:622px;top:508px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GND1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:660px;top:254px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:635px;top:75px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:614px;top:68px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ACT LMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:635px;top:92px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:631px;top:58px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:631px;top:117px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:631px;top:134px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:634px;top:188px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:631px;top:231px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:631px;top:269px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:631px;top:286px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:631px;top:303px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:616px;top:84px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA WL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:622px;top:102px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WALP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:628px;top:127px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>EBD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:624px;top:144px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PARK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:623px;top:198px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>STOP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:619px;top:240px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>OFF SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:629px;top:278px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:617px;top:295px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B-FSR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:560px;top:148px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:565px;top:530px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G204<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:584px;top:63px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:584px;top:80px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:584px;top:97px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:584px;top:122px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:584px;top:139px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:584px;top:193px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:584px;top:290px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:584px;top:274px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:584px;top:308px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:584px;top:324px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:584px;top:341px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:584px;top:358px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:584px;top:375px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:584px;top:409px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:580px;top:426px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:584px;top:443px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:584px;top:392px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:584px;top:460px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:584px;top:485px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:584px;top:503px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:527px;top:139px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:620px;top:465px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:622px;top:490px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GND2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:621px;top:363px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:617px;top:380px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FR-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:621px;top:397px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:617px;top:414px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RL-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:620px;top:430px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:617px;top:448px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RR-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:775px;top:267px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:775px;top:302px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:766px;top:344px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:765px;top:379px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:768px;top:414px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:767px;top:449px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:798px;top:281px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:798px;top:296px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:798px;top:317px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:798px;top:331px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:798px;top:358px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:798px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:797px;top:393px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:798px;top:408px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:797px;top:428px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:798px;top:443px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:798px;top:464px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:798px;top:478px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:902px;top:113px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:826px;top:114px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:826px;top:106px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:826px;top:123px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:854px;top:119px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" class=\"drag\" style=\"position:absolute;left:885px;top:119px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" class=\"drag\" style=\"position:absolute;left:794px;top:51px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" class=\"drag\" style=\"position:absolute;left:804px;top:91px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" class=\"drag\" style=\"position:absolute;left:902px;top:46px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" class=\"drag\" style=\"position:absolute;left:902px;top:63px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" class=\"drag\" style=\"position:absolute;left:902px;top:79px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" class=\"drag\" style=\"position:absolute;left:902px;top:97px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" class=\"drag\" style=\"position:absolute;left:826px;top:46px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" class=\"drag\" style=\"position:absolute;left:826px;top:63px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" class=\"drag\" style=\"position:absolute;left:826px;top:80px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" class=\"drag\" style=\"position:absolute;left:826px;top:97px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" class=\"drag\" style=\"position:absolute;left:849px;top:68px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" class=\"drag\" style=\"position:absolute;left:885px;top:68px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" class=\"drag\" style=\"position:absolute;left:854px;top:51px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" class=\"drag\" style=\"position:absolute;left:885px;top:51px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" class=\"drag\" style=\"position:absolute;left:854px;top:85px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" class=\"drag\" style=\"position:absolute;left:885px;top:85px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" class=\"drag\" style=\"position:absolute;left:854px;top:102px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" class=\"drag\" style=\"position:absolute;left:885px;top:102px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" class=\"drag\" style=\"position:absolute;left:826px;top:56px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ST-A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" class=\"drag\" style=\"position:absolute;left:826px;top:72px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ST-B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" class=\"drag\" style=\"position:absolute;left:826px;top:90px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ST-Z<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" class=\"drag\" style=\"position:absolute;left:908px;top:28px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>STEERING<br>ANGLE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" class=\"drag\" style=\"position:absolute;left:518px;top:155px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PARKING<br>BRAKE<br>SWITCH<br>Closed:<br>Parking<br> brake applied<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" class=\"drag\" style=\"position:absolute;left:556px;top:250px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(KE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" class=\"drag\" style=\"position:absolute;left:499px;top:230px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" class=\"drag\" style=\"position:absolute;left:549px;top:221px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA OFF SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" class=\"drag\" style=\"position:absolute;left:585px;top:229px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" class=\"drag\" style=\"position:absolute;left:595px;top:236px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" class=\"drag\" style=\"position:absolute;left:503px;top:193px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" class=\"drag\" style=\"position:absolute;left:553px;top:229px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" class=\"drag\" style=\"position:absolute;left:536px;top:253px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" class=\"drag\" style=\"position:absolute;left:520px;top:193px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" class=\"drag\" style=\"position:absolute;left:502px;top:216px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" class=\"drag\" style=\"position:absolute;left:521px;top:216px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" class=\"drag\" style=\"position:absolute;left:353px;top:409px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" class=\"drag\" style=\"position:absolute;left:352px;top:443px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" class=\"drag\" style=\"position:absolute;left:353px;top:325px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" class=\"drag\" style=\"position:absolute;left:353px;top:342px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" class=\"drag\" style=\"position:absolute;left:353px;top:359px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" class=\"drag\" style=\"position:absolute;left:353px;top:375px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" class=\"drag\" style=\"position:absolute;left:77px;top:511px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" class=\"drag\" style=\"position:absolute;left:61px;top:494px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" class=\"drag\" style=\"position:absolute;left:99px;top:511px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G501: (KE)<br>G503: (KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" class=\"drag\" style=\"position:absolute;left:852px;top:180px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" class=\"drag\" style=\"position:absolute;left:829px;top:182px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" class=\"drag\" style=\"position:absolute;left:902px;top:157px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" class=\"drag\" style=\"position:absolute;left:902px;top:174px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" class=\"drag\" style=\"position:absolute;left:902px;top:191px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" class=\"drag\" style=\"position:absolute;left:902px;top:208px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" class=\"drag\" style=\"position:absolute;left:895px;top:254px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" class=\"drag\" style=\"position:absolute;left:895px;top:271px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" class=\"drag\" style=\"position:absolute;left:888px;top:264px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>CAN-H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" class=\"drag\" style=\"position:absolute;left:888px;top:282px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>CAN-L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" class=\"drag\" style=\"position:absolute;left:866px;top:252px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" class=\"drag\" style=\"position:absolute;left:876px;top:231px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" class=\"drag\" style=\"position:absolute;left:826px;top:191px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" class=\"drag\" style=\"position:absolute;left:826px;top:208px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" class=\"drag\" style=\"position:absolute;left:826px;top:201px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>CAN-H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" class=\"drag\" style=\"position:absolute;left:826px;top:217px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>CAN-L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" class=\"drag\" style=\"position:absolute;left:852px;top:196px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" class=\"drag\" style=\"position:absolute;left:853px;top:213px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" class=\"drag\" style=\"position:absolute;left:870px;top:163px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" class=\"drag\" style=\"position:absolute;left:877px;top:180px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" class=\"drag\" style=\"position:absolute;left:918px;top:244px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" class=\"drag\" style=\"position:absolute;left:879px;top:139px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YAW RATE/LATERAL<br>ACCELERATION<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" class=\"drag\" style=\"position:absolute;left:884px;top:245px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 2 (58P)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}