with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:1070px; height:1055px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:1070px;position:relative;height:1055px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E8JJ54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1070px;height:1055px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:2px;top:49px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>VSA CONTROL UNIT-MODULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:387px;top:16px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>GLOW PLUG CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:798px;top:840px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>PTC HEATER A RELAY<br></b>Wire colors: GRY, WHT,<br>BLU and YEL<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:808px;top:494px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>AUXILIARY UNDER-HOOD<br>RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:450px;top:651px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:464px;top:698px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>HEADLIGHT RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:464px;top:777px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>HEADLIGHT RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:434px;top:850px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>A/C CONDENSER FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:413px;top:898px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>FUEL HEATER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:346px;top:929px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>A/C COMPRESSOR CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:677px;top:903px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>PTC HEATER B RELAY<br></b>Wire colors: BLU, RED,<br>GRN and YEL<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:231px;top:577px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>BLOWER MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:122px;top:608px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>RADIATOR FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:28px;top:639px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>PTC HEATER C RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:253px;top:961px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>FAN CONTROL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:113px;top:930px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:1px;top:838px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>AUTO WIPER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:28px;top:671px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:0px;top:1023px;font-weight:normal;font-size:9.7pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}