with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1108px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E8JA14500000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:89px;top:571px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:184px;top:571px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:95px;top:121px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 1<br>(100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:72px;top:24px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:184px;top:514px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:90px;top:514px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:401px;top:86px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>HORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:79px;top:466px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:373px;top:548px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:373px;top:593px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:93px;top:1003px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:104px;top:986px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:104px;top:952px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:282px;top:971px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 1 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:210px;top:908px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:263px;top:908px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:396px;top:908px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:107px;top:882px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CLSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:838px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SETIND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:554px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRMSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:732px;top:607px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:586px;top:548px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:536px;top:548px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:787px;top:485px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:435px;top:326px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:79px;top:277px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:90px;top:319px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:70px;top:308px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:115px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IGNITION<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:297px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>VSS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:469px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRRESSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:79px;top:352px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:108px;top:47px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:97px;top:199px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 2<br>(50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:36px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:223px;top:882px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ1−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:275px;top:882px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ1+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:368px;top:883px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ2−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:419px;top:883px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ2+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:511px;top:882px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ3−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:563px;top:882px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ3+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:660px;top:883px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ4−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:712px;top:883px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ4+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:385px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRSETSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:91px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:186px;top:637px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BKSWNO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:708px;top:941px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:708px;top:997px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:720px;top:971px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 4 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:649px;top:909px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:699px;top:909px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:571px;top:971px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 3 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:499px;top:909px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:541px;top:909px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:426px;top:971px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 2 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:354px;top:908px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:429px;top:388px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CAN−<br>CEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:204px;top:529px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRAKE <br>PEDAL <br>POSITION <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:117px;top:953px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CLUTCH PEDAL <br>POSITION <br>SWITCH <br>(ON : Pedal <br>released)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:586px;top:183px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:328px;top:218px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>HORN <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:385px;top:388px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SET/<br>DECEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:468px;top:388px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RESUME/<br>ACCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:272px;top:51px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:849px;top:518px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE<br>CONTROL<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:833px;top:450px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:71px;top:758px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>12 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:94px;top:415px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 9<br>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:78px;top:252px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:559px;top:941px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:559px;top:997px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:415px;top:941px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:415px;top:997px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:271px;top:941px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:271px;top:997px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:759px;top:519px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE<br>MAIN<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:491px;top:86px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SMALL<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:541px;top:58px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DASH LIGHTS<br>BRIGHTNESS<br>CONTOROLLER<br>(In the gauge<br>assembly)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:495px;top:141px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:556px;top:141px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:337px;top:106px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:392px;top:106px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:213px;top:86px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:175px;top:253px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:79px;top:588px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:168px;top:588px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:446px;top:593px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT BLU*1<br>LT GRN*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:457px;top:548px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:541px;top:593px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:827px;top:607px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:373px;top:451px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:586px;top:452px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:535px;top:451px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:457px;top:451px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:601px;top:384px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE<br>CONTROL<br>MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:493px;top:238px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:555px;top:238px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:416px;top:238px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:53px;top:481px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:687px;top:376px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:371px;top:438px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:455px;top:438px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:540px;top:438px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:585px;top:438px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:416px;top:248px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:494px;top:248px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:555px;top:248px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:39px;top:901px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:39px;top:932px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:89px;top:918px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:285px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>VSS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:829px;top:29px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>*1 : KG MODEL<br>*2 : KE MODEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:577px;top:239px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE CONTROL<br>COMBINATION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:584px;top:590px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G481<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:92px;top:1061px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:93px;top:380px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:621px;top:493px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:568px;top:653px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5 V<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}