with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:475px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9U000000000000EBA911.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:138px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:360px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:582px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:804px;top:22px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:858px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:858px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:83px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:736px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>EXTEND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:736px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RETRACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:711px;top:430px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RETRACT ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:789px;top:430px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MIRROR ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:694px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:720px;top:292px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:718px;top:298px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:690px;top:298px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:689px;top:292px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:657px;top:292px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:623px;top:292px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:773px;top:337px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUR : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:774px;top:331px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:559px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUR : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:545px;top:331px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK : KE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:857px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:858px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:858px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:857px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:82px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:83px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:83px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:82px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:82px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:919px;top:18px;font-weight:normal;font-size:8.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:11px;top:17px;font-weight:normal;font-size:8.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:624px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:566px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:616px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:558px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:517px;top:295px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:517px;top:159px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:516px;top:178px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:903px;top:77px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:880px;top:78px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.18 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:39px;top:73px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.14 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:62px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:880px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.14 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:902px;top:72px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:62px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:39px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:32px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:62px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:880px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:902px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:880px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:908px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:220px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>61<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:847px;top:99px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2 : Under−dash fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:847px;top:95px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1 : Under−hood fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:181px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:338px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:238px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:215px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:514px;top:259px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:516px;top:200px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:630px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:676px;top:454px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:811px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:785px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:716px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:742px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:724px;top:143px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:693px;top:159px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:825px;top:149px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:756px;top:216px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:545px;top:337px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:559px;top:320px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:656px;top:298px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:788px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:778px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:725px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:626px;top:298px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:605px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:571px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:805px;top:135px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>POWER MIRROR SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:555px;top:231px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>EXTEND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:612px;top:231px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RETRACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:611px;top:430px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RETRACT ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:561px;top:430px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MIRROR ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:612px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>EXTEND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:610px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RETRACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:628px;top:438px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT POWER MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:789px;top:438px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT POWER MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:540px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:587px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:588px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:536px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:765px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:816px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:815px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:767px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:516px;top:281px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:678px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:725px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:738px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:794px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:805px;top:253px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:563px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:550px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:577px;top:359px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:660px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:630px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:318px;top:234px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:444px;top:347px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:427px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:426px;top:454px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:425px;top:284px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:336px;top:347px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:317px;top:454px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:319px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:316px;top:284px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:326px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:326px;top:104px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:260px;top:234px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:219px;top:164px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:226px;top:104px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:226px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:171px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:171px;top:104px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:215px;top:234px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:163px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:161px;top:454px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:163px;top:248px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:163px;top:284px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:62px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:39px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:58px;top:34px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:58px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:60px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:60px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:880px;top:34px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:880px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:880px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:880px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:902px;top:38px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:35px;top:11px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>Rear Window Defogger, Power Mirrors, Power Mirror Defoggers<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:333px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>POWER <br>MIRROR <br>DEFOGGER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:133px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR <br>WINDOW <br>DEFOGGER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:209px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER/ <br>POWER MIRROR <br>DEFOGGER <br>SWITCH<br>(CLIMATE <br>CONTROL UNIT)<br>‹19−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:177px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REAR <br>WINDOW <br>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:344px;top:309px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:441px;top:309px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT <br>POWER <br>MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:508px;top:142px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY <br>‹4−D› ‹5−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:509px;top:309px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DASHLIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>‹3−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:528px;top:227px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LIGHT <br>(1.4 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:162px;top:164px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:730px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:718px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:718px;top:89px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:711px;top:105px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:711px;top:126px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:264px;top:144px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>62 <br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:261px;top:155px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ECM<br>‹24−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:263px;top:132px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}