with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9UJ20170700000KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:247px;top:57px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:170px;top:271px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Reference hole alignment<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:349px;top:305px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REFERENCE HOLE<br>(Body side)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:104px;top:299px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUBFRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:96px;top:444px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SCREWDRIVER or<br>TAPERED PUNCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:351px;top:409px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSTALLATION<br>REFERENCE HOLE<br>(Subframe side)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:229px;top:579px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:214px;top:642px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:330px;top:508px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:471px;top:508px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:550px;top:535px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSTALLATION<br>REFERENCE HOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:735px;top:572px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:757px;top:464px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:786px;top:628px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:804px;top:682px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSTALLATION<br>REFERENCE HOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:595px;top:744px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:350px;top:877px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPECIAL BOLTS<br>14 x 1.5 mm<br>103 N·m<br>(10.5 kgf·m, 76 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:654px;top:977px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPECIAL BOLTS<br>14 x 1.5 mm<br>103 N·m<br>(10.5 kgf·m, 76 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:564px;top:385px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}