with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:554px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E8JJ22100000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:580px;top:136px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:572px;top:113px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:897px;top:331px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:900px;top:152px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:509px;top:136px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:740px;top:263px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:498px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:505px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:544px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:537px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:605px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:603px;top:431px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:630px;top:399px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:762px;top:502px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:761px;top:535px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:758px;top:431px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:726px;top:431px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:694px;top:431px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:651px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:697px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:612px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:662px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:705px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:705px;top:136px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:697px;top:113px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:734px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:726px;top:360px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:801px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:801px;top:502px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:800px;top:535px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:833px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:841px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:809px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:869px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:862px;top:381px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:887px;top:402px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:862px;top:431px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:614px;top:355px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:614px;top:366px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:713px;top:394px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:713px;top:405px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:718px;top:405px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IMOES UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:568px;top:50px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>POWER <br>WINDOW <br>MASTER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:823px;top:425px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ABS/VSA <br>MODULATOR−<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:876px;top:360px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IMMOBILIZER <br>CONTROL <br>UNIT−RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:794px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRAKE <br>SYSTEM <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:745px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRAKE SYSTEM <br>CHECK CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:718px;top:394px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:869px;top:468px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PARKING <br>BRAKE SWITCH<br>(Close : <br>Pedal pushed)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:809px;top:468px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRAKE FLUID <br>LEVEL SWITCH <br>(Close : <br>Float down)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:769px;top:465px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TAILGATE <br>LATCH<br>SWITCH <br>(Closed : <br>Tailgate open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:737px;top:465px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>REAR <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:705px;top:465px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>REAR <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:662px;top:465px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:612px;top:465px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:619px;top:366px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:619px;top:355px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INTEGRATED <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:531px;top:425px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:486px;top:425px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IMMOBILIZER <br>CONTROL <br>UNIT−RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:612px;top:214px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOOR/TAILGATE <br>INDICATOR <br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:544px;top:214px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:505px;top:214px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IMMOBILIZER <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:688px;top:63px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INTEGRATED <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:58px;top:370px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:65px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:176px;top:136px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:58px;top:419px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:422px;top:224px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:371px;top:224px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:258px;top:65px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:258px;top:70px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:207px;top:370px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:140px;top:106px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:167px;top:54px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:169px;top:84px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:169px;top:106px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:423px;top:294px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LCD DISPLAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:371px;top:291px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EEPROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:342px;top:263px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:321px;top:224px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:83px;top:370px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:255px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:244px;top:370px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:137px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:171px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:33px;top:370px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:40px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:248px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:219px;top:458px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:219px;top:418px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:211px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:121px;top:263px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:283px;top:124px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:248px;top:124px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:164px;top:31px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:187px;top:150px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BEEPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:290px;top:136px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:235px;top:13px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:89px;top:23px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:42px;top:23px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.1 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:15px;top:136px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:255px;top:136px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:90px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:58px;top:205px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TACHOMETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:136px;top:31px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:197px;top:37px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:188px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:223px;top:31px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:136px;top:49px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:92px;top:41px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:43px;top:13px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:13px;top:19px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:179px;top:13px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:132px;top:125px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TEST <br>TACHOMETER <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:226px;top:430px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FUEL <br>GAUGE <br>SENDING <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:29px;top:199px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SPEEDO− <br>METER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:101px;top:199px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FUEL <br>GAUGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:133px;top:193px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>COOLANT <br>TEMPERATURE <br>GAUGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:318px;top:171px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RATED VOLTAGE <br>SUPPLY CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:332px;top:189px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BACK LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:382px;top:189px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LCD BACK <br>LIGHT (LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:432px;top:189px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>POINTER <br>LIGHT (LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:291px;top:290px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ODO/TRIP SWITCH, <br>DASH LIGHTS BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:261px;top:203px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>POWER <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}