with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:640px;position:relative;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SJD6E9U000000000000EBA224.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:285px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:294px;top:579px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:157px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:240px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:240px;top:415px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br>‹2−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:567px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:567px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:561px;top:421px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ALTERNATOR <br>‹1−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:379px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:385px;top:446px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:369px;top:403px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GLOW PLUG<br>INDICATOR<br>LIGHT<br>‹3−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:491px;top:445px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:488px;top:515px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:471px;top:403px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MALFUNCTION<br>INDICATOR<br>LAMP(MIL)<br>‹3−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:33px;top:454px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/YEL : KE<br>PUR : KG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:47px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:112px;top:646px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:59px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:6px;top:646px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:194px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:239px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:285px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:337px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:382px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:428px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:188px;top:816px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>APP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:481px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:525px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:570px;top:645px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:507px;top:816px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTER SHAFT)<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:634px;top:788px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C PRESSURE<br>SWITCH<br>‹19−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:244px;top:445px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>6 <br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:288px;top:445px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>8 <br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:163px;top:445px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>7 <br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:583px;top:446px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>3 <br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:137px;top:380px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br>‹2−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:137px;top:399px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HEADLIGHTS ADJUSTER <br>CONTROL UNIT ‹6−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:137px;top:418px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>NAVIGATION UNIT <br>‹17−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:131px;top:380px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>· <br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:131px;top:399px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>· <br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:131px;top:418px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>· <br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}