with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1108px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9UJ32113100000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:482px;top:291px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:418px;top:363px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:417px;top:291px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:405px;top:520px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:429px;top:455px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:429px;top:413px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:280px;top:706px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:409px;top:706px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:285px;top:1063px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G702<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:402px;top:63px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:300px;top:791px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:300px;top:749px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:429px;top:791px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:429px;top:749px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:482px;top:134px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:81px;top:23px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:30px;top:39px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:302px;top:63px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:187px;top:48px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:475px;top:51px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:289px;top:834px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:500px;top:218px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:500px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:418px;top:834px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:454px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:416px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:494px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:413px;top:1063px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:93px;top:48px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.1 (BAT) (100 A) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:446px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BACK−UP <br>LIGHT SWITCH <br>(On the transmission <br>housing) <br>(Closed : In position R)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:446px;top:753px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RIGHT <br>BACK−UP <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:317px;top:753px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LEFT <br>BACK−UP <br>LIGHT <br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:553px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}