with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:465px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:465px;\">");
write("<img id=\"img1\" src=\"../img/SJD6E9UA46500056901KDAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:465px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:75px;top:423px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:39px;top:12px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:363px;top:161px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:331px;top:35px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:386px;top:13px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, <br>7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:389px;top:178px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, <br>7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:341px;top:423px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:360px;top:401px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:408px;top:282px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:122px;top:101px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}