with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0A20336335001KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:74px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION<br>(EGR) JOINT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:504px;top:99px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKETS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:537px;top:151px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m <br>(1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:578px;top:216px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5 x 0.8 mm<br>3.4 N·m <br>(0.35 kgf·m, 2.5 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:797px;top:747px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>24 N·m <br>(2.4 kgf·m, 17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:677px;top:960px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:16px;top:703px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>24 N·m <br>(2.4 kgf·m, 17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:30px;top:456px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:289px;top:812px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:714px;top:348px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:621px;top:284px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE PRESSURE <br>(MAP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:686px;top:873px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:351px;top:872px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD<br></b>Replace if cracked or if<br>mating surface is damaged.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:126px;top:812px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THROTTLE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:504px;top:960px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>24 N·m <br>(2.4 kgf·m, 17 lbf·ft)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}