with(document) {
write("<div id=\"group7\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect7\"class=\"drag\" style=\"width:950px;position:relative;height:1071px;\">");
write("<img id=\"img7\" src=\"../img/SJD7EC0A20300000000DBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p7_1\" class=\"drag\" style=\"position:absolute;left:416px;top:571px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR (22)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" class=\"drag\" style=\"position:absolute;left:515px;top:16px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION<br>SWITCH (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" class=\"drag\" style=\"position:absolute;left:209px;top:38px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DATA LINK CONNECTOR<br>(2)*<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" class=\"drag\" style=\"position:absolute;left:463px;top:156px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12P CONNECTOR (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" class=\"drag\" style=\"position:absolute;left:820px;top:680px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INERTIA <br>SWITCH (29)<br>(KE model)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" class=\"drag\" style=\"position:absolute;left:248px;top:155px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" class=\"drag\" style=\"position:absolute;left:267px;top:858px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P JUNCTION CONNECTOR (31)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" class=\"drag\" style=\"position:absolute;left:297px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY BOX (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" class=\"drag\" style=\"position:absolute;left:510px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" class=\"drag\" style=\"position:absolute;left:758px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" class=\"drag\" style=\"position:absolute;left:446px;top:433px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY<br>BOX (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" class=\"drag\" style=\"position:absolute;left:665px;top:692px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR (28)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" class=\"drag\" style=\"position:absolute;left:49px;top:703px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7P CONNECTOR<br>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" class=\"drag\" style=\"position:absolute;left:268px;top:433px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY<br>BOX (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" class=\"drag\" style=\"position:absolute;left:83px;top:857px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16P CONNECTOR (30)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" class=\"drag\" style=\"position:absolute;left:727px;top:38px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE B (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" class=\"drag\" style=\"position:absolute;left:44px;top:433px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY<br>BOX (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" class=\"drag\" style=\"position:absolute;left:205px;top:571px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DIODE (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" class=\"drag\" style=\"position:absolute;left:462px;top:703px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR (27)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" class=\"drag\" style=\"position:absolute;left:771px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR (24)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" class=\"drag\" style=\"position:absolute;left:43px;top:561px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" class=\"drag\" style=\"position:absolute;left:55px;top:144px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" class=\"drag\" style=\"position:absolute;left:658px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY<br>BOX (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" class=\"drag\" style=\"position:absolute;left:800px;top:144px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY<br>BOX (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" class=\"drag\" style=\"position:absolute;left:404px;top:17px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CLUTCH PEDAL<br>POSITION<br>SWITCH (3)<br>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_26\" class=\"drag\" style=\"position:absolute;left:51px;top:16px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D3 SWITCH/<br>SHIFT LOCK<br>SOLENOID<br>(1) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_27\" class=\"drag\" style=\"position:absolute;left:55px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY BOX (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_28\" class=\"drag\" style=\"position:absolute;left:706px;top:433px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_29\" class=\"drag\" style=\"position:absolute;left:289px;top:571px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DIODE (21)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_30\" class=\"drag\" style=\"position:absolute;left:609px;top:571px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12P CONNECTOR <br>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_31\" class=\"drag\" style=\"position:absolute;left:226px;top:703px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR (26)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_32\" class=\"drag\" style=\"position:absolute;left:0px;top:994px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}