with(document) {
write("<div id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect6\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img6\" src=\"../img/SJD7EC0A20300000000EAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:576px;top:249px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:576px;top:312px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:576px;top:270px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:576px;top:291px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:646px;top:240px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:577px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:576px;top:483px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:575px;top:461px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:576px;top:356px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:575px;top:441px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:646px;top:283px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:646px;top:305px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:646px;top:326px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:646px;top:347px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:646px;top:431px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:644px;top:452px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" class=\"drag\" style=\"position:absolute;left:645px;top:474px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" class=\"drag\" style=\"position:absolute;left:785px;top:510px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TRANSMISSION<br>RANGE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" class=\"drag\" style=\"position:absolute;left:327px;top:155px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" class=\"drag\" style=\"position:absolute;left:301px;top:156px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" class=\"drag\" style=\"position:absolute;left:354px;top:155px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" class=\"drag\" style=\"position:absolute;left:380px;top:155px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" class=\"drag\" style=\"position:absolute;left:535px;top:551px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" class=\"drag\" style=\"position:absolute;left:682px;top:250px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" class=\"drag\" style=\"position:absolute;left:681px;top:313px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" class=\"drag\" style=\"position:absolute;left:682px;top:270px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" class=\"drag\" style=\"position:absolute;left:682px;top:292px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" class=\"drag\" style=\"position:absolute;left:753px;top:242px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" class=\"drag\" style=\"position:absolute;left:681px;top:334px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" class=\"drag\" style=\"position:absolute;left:681px;top:482px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" class=\"drag\" style=\"position:absolute;left:680px;top:460px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" class=\"drag\" style=\"position:absolute;left:682px;top:357px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" class=\"drag\" style=\"position:absolute;left:680px;top:440px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" class=\"drag\" style=\"position:absolute;left:753px;top:263px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p6_35\" class=\"drag\" style=\"position:absolute;left:753px;top:284px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p6_36\" class=\"drag\" style=\"position:absolute;left:753px;top:306px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p6_37\" class=\"drag\" style=\"position:absolute;left:753px;top:327px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p6_38\" class=\"drag\" style=\"position:absolute;left:753px;top:349px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p6_39\" class=\"drag\" style=\"position:absolute;left:753px;top:433px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p6_40\" class=\"drag\" style=\"position:absolute;left:753px;top:454px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_41\" class=\"drag\" style=\"position:absolute;left:748px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p6_42\" class=\"drag\" style=\"position:absolute;left:771px;top:630px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2ND CLUTCH<br>TRANSMISSION FLUID<br>PRESSURE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p6_43\" class=\"drag\" style=\"position:absolute;left:771px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3RD CLUTCH<br>TRANSMISSION FLUID<br>PRESSURE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p6_44\" class=\"drag\" style=\"position:absolute;left:762px;top:671px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_45\" class=\"drag\" style=\"position:absolute;left:762px;top:767px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_46\" class=\"drag\" style=\"position:absolute;left:690px;top:679px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_47\" class=\"drag\" style=\"position:absolute;left:691px;top:775px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_48\" class=\"drag\" style=\"position:absolute;left:575px;top:419px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_49\" class=\"drag\" style=\"position:absolute;left:645px;top:410px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p6_50\" class=\"drag\" style=\"position:absolute;left:680px;top:419px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_51\" class=\"drag\" style=\"position:absolute;left:752px;top:412px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p6_52\" class=\"drag\" style=\"position:absolute;left:646px;top:262px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p6_53\" class=\"drag\" style=\"position:absolute;left:330px;top:799px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p6_54\" class=\"drag\" style=\"position:absolute;left:358px;top:808px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p6_55\" class=\"drag\" style=\"position:absolute;left:40px;top:61px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_56\" class=\"drag\" style=\"position:absolute;left:192px;top:199px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p6_57\" class=\"drag\" style=\"position:absolute;left:192px;top:256px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p6_58\" class=\"drag\" style=\"position:absolute;left:241px;top:208px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_59\" class=\"drag\" style=\"position:absolute;left:243px;top:264px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_60\" class=\"drag\" style=\"position:absolute;left:192px;top:369px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B21<br></b></nobr>");
write("</p>");
write("<p id=\"p6_61\" class=\"drag\" style=\"position:absolute;left:192px;top:312px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p6_62\" class=\"drag\" style=\"position:absolute;left:192px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPP<br></b></nobr>");
write("</p>");
write("<p id=\"p6_63\" class=\"drag\" style=\"position:absolute;left:192px;top:274px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPR<br></b></nobr>");
write("</p>");
write("<p id=\"p6_64\" class=\"drag\" style=\"position:absolute;left:192px;top:387px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPD<br></b></nobr>");
write("</p>");
write("<p id=\"p6_65\" class=\"drag\" style=\"position:absolute;left:192px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_66\" class=\"drag\" style=\"position:absolute;left:192px;top:426px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p6_67\" class=\"drag\" style=\"position:absolute;left:192px;top:539px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B28<br></b></nobr>");
write("</p>");
write("<p id=\"p6_68\" class=\"drag\" style=\"position:absolute;left:192px;top:557px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPFWD<br></b></nobr>");
write("</p>");
write("<p id=\"p6_69\" class=\"drag\" style=\"position:absolute;left:192px;top:595px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B22<br></b></nobr>");
write("</p>");
write("<p id=\"p6_70\" class=\"drag\" style=\"position:absolute;left:192px;top:613px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPRVS<br></b></nobr>");
write("</p>");
write("<p id=\"p6_71\" class=\"drag\" style=\"position:absolute;left:331px;top:176px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/<br>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_72\" class=\"drag\" style=\"position:absolute;left:386px;top:182px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/<br>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_73\" class=\"drag\" style=\"position:absolute;left:336px;top:969px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p6_74\" class=\"drag\" style=\"position:absolute;left:192px;top:670px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p6_75\" class=\"drag\" style=\"position:absolute;left:192px;top:767px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p6_76\" class=\"drag\" style=\"position:absolute;left:192px;top:688px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OP2SW<br></b></nobr>");
write("</p>");
write("<p id=\"p6_77\" class=\"drag\" style=\"position:absolute;left:192px;top:784px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OP3SW<br></b></nobr>");
write("</p>");
write("<p id=\"p6_78\" class=\"drag\" style=\"position:absolute;left:192px;top:482px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p6_79\" class=\"drag\" style=\"position:absolute;left:192px;top:500px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATP1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_80\" class=\"drag\" style=\"position:absolute;left:330px;top:855px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_81\" class=\"drag\" style=\"position:absolute;left:423px;top:135px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p6_82\" class=\"drag\" style=\"position:absolute;left:333px;top:106px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_83\" class=\"drag\" style=\"position:absolute;left:191px;top:444px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATP2<br></b></nobr>");
write("</p>");
write("<p id=\"p6_84\" class=\"drag\" style=\"position:absolute;left:835px;top:353px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p6_85\" class=\"drag\" style=\"position:absolute;left:835px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_86\" class=\"drag\" style=\"position:absolute;left:835px;top:269px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p6_87\" class=\"drag\" style=\"position:absolute;left:834px;top:291px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p6_88\" class=\"drag\" style=\"position:absolute;left:835px;top:312px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p6_89\" class=\"drag\" style=\"position:absolute;left:834px;top:332px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p6_90\" class=\"drag\" style=\"position:absolute;left:359px;top:911px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br>(21P CONNECTOR)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_91\" class=\"drag\" style=\"position:absolute;left:345px;top:884px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br>(1)*4<br></b></nobr>");
write("</p>");
write("<p id=\"p6_92\" class=\"drag\" style=\"position:absolute;left:464px;top:922px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p6_93\" class=\"drag\" style=\"position:absolute;left:384px;top:106px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_94\" class=\"drag\" style=\"position:absolute;left:223px;top:1027px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: A/T<br>*4: LHD model<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}