with(document) {
write("<div id=\"group10\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect10\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img10\" src=\"../img/SJD7EC0A20300000000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p10_1\" class=\"drag\" style=\"position:absolute;left:796px;top:263px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" class=\"drag\" style=\"position:absolute;left:805px;top:385px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION COIL<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" class=\"drag\" style=\"position:absolute;left:817px;top:513px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI  <br>SUBRELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" class=\"drag\" style=\"position:absolute;left:689px;top:87px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TEST<br>TACHOMETER<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" class=\"drag\" style=\"position:absolute;left:714px;top:19px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" class=\"drag\" style=\"position:absolute;left:717px;top:518px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" class=\"drag\" style=\"position:absolute;left:718px;top:576px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" class=\"drag\" style=\"position:absolute;left:718px;top:602px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" class=\"drag\" style=\"position:absolute;left:718px;top:629px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" class=\"drag\" style=\"position:absolute;left:718px;top:655px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" class=\"drag\" style=\"position:absolute;left:718px;top:681px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" class=\"drag\" style=\"position:absolute;left:718px;top:709px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" class=\"drag\" style=\"position:absolute;left:780px;top:866px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" class=\"drag\" style=\"position:absolute;left:741px;top:882px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" class=\"drag\" style=\"position:absolute;left:795px;top:771px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" class=\"drag\" style=\"position:absolute;left:652px;top:238px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" class=\"drag\" style=\"position:absolute;left:603px;top:247px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" class=\"drag\" style=\"position:absolute;left:652px;top:291px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" class=\"drag\" style=\"position:absolute;left:603px;top:300px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" class=\"drag\" style=\"position:absolute;left:603px;top:693px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" class=\"drag\" style=\"position:absolute;left:652px;top:686px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" class=\"drag\" style=\"position:absolute;left:603px;top:720px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" class=\"drag\" style=\"position:absolute;left:652px;top:712px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" class=\"drag\" style=\"position:absolute;left:604px;top:752px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" class=\"drag\" style=\"position:absolute;left:653px;top:744px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" class=\"drag\" style=\"position:absolute;left:653px;top:762px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" class=\"drag\" style=\"position:absolute;left:603px;top:788px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" class=\"drag\" style=\"position:absolute;left:652px;top:780px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" class=\"drag\" style=\"position:absolute;left:650px;top:89px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" class=\"drag\" style=\"position:absolute;left:562px;top:849px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G304<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" class=\"drag\" style=\"position:absolute;left:425px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" class=\"drag\" style=\"position:absolute;left:458px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" class=\"drag\" style=\"position:absolute;left:500px;top:190px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" class=\"drag\" style=\"position:absolute;left:394px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5 (13)*4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" class=\"drag\" style=\"position:absolute;left:328px;top:334px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" class=\"drag\" style=\"position:absolute;left:262px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Y<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" class=\"drag\" style=\"position:absolute;left:470px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" class=\"drag\" style=\"position:absolute;left:338px;top:238px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" class=\"drag\" style=\"position:absolute;left:612px;top:99px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" class=\"drag\" style=\"position:absolute;left:193px;top:152px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" class=\"drag\" style=\"position:absolute;left:193px;top:170px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" class=\"drag\" style=\"position:absolute;left:194px;top:359px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" class=\"drag\" style=\"position:absolute;left:194px;top:377px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" class=\"drag\" style=\"position:absolute;left:435px;top:809px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P <br>CONNECOTR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" class=\"drag\" style=\"position:absolute;left:292px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AC<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" class=\"drag\" style=\"position:absolute;left:328px;top:412px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" class=\"drag\" style=\"position:absolute;left:194px;top:470px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" class=\"drag\" style=\"position:absolute;left:193px;top:488px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SUBRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" class=\"drag\" style=\"position:absolute;left:472px;top:685px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" class=\"drag\" style=\"position:absolute;left:430px;top:662px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7P <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" class=\"drag\" style=\"position:absolute;left:472px;top:712px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" class=\"drag\" style=\"position:absolute;left:507px;top:797px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" class=\"drag\" style=\"position:absolute;left:307px;top:213px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P <br>CONNECOTR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" class=\"drag\" style=\"position:absolute;left:322px;top:298px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br>(21P CONNECOTR)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" class=\"drag\" style=\"position:absolute;left:383px;top:695px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" class=\"drag\" style=\"position:absolute;left:383px;top:722px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" class=\"drag\" style=\"position:absolute;left:194px;top:761px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A23<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" class=\"drag\" style=\"position:absolute;left:194px;top:779px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" class=\"drag\" style=\"position:absolute;left:517px;top:917px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" class=\"drag\" style=\"position:absolute;left:323px;top:917px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" class=\"drag\" style=\"position:absolute;left:280px;top:916px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Z<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" class=\"drag\" style=\"position:absolute;left:237px;top:971px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*3: RHD model<br>*4: LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" class=\"drag\" style=\"position:absolute;left:604px;top:231px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" class=\"drag\" style=\"position:absolute;left:603px;top:334px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" class=\"drag\" style=\"position:absolute;left:603px;top:368px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" class=\"drag\" style=\"position:absolute;left:603px;top:496px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" class=\"drag\" style=\"position:absolute;left:600px;top:557px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" class=\"drag\" style=\"position:absolute;left:257px;top:479px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" class=\"drag\" style=\"position:absolute;left:359px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" class=\"drag\" style=\"position:absolute;left:603px;top:614px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" class=\"drag\" style=\"position:absolute;left:603px;top:641px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" class=\"drag\" style=\"position:absolute;left:603px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" class=\"drag\" style=\"position:absolute;left:604px;top:588px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" class=\"drag\" style=\"position:absolute;left:605px;top:908px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUSES:<br>UNDER-HOOD FUSE/RELAY BOX:<br>(1)No. 19 OIL LEVEL (7.5 A)<br>(2)No. 14 +B STOP &amp; HORN (15 A)<br>(3)No. 13 IGNITION COIL RELAY (15 A)<br>(4)No. 15 A/F SENSOR (15 A)<br>(5)No. 23 +B BACK UP (10 A)<br>(6)No. 2 +B OPTION (50 A)<br>(7)No. 2 +B IG1 MAIN (50 A)<br>(8)No. 1 BATTERY (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" class=\"drag\" style=\"position:absolute;left:242px;top:770px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_76\" class=\"drag\" style=\"position:absolute;left:424px;top:309px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_77\" class=\"drag\" style=\"position:absolute;left:427px;top:336px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_78\" class=\"drag\" style=\"position:absolute;left:234px;top:368px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_79\" class=\"drag\" style=\"position:absolute;left:511px;top:858px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_80\" class=\"drag\" style=\"position:absolute;left:299px;top:246px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_81\" class=\"drag\" style=\"position:absolute;left:398px;top:246px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_82\" class=\"drag\" style=\"position:absolute;left:195px;top:90px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A28<br></b></nobr>");
write("</p>");
write("<p id=\"p10_83\" class=\"drag\" style=\"position:absolute;left:194px;top:108px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>NEP<br></b></nobr>");
write("</p>");
write("<p id=\"p10_84\" class=\"drag\" style=\"position:absolute;left:532px;top:189px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p10_85\" class=\"drag\" style=\"position:absolute;left:603px;top:444px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_86\" class=\"drag\" style=\"position:absolute;left:603px;top:530px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_87\" class=\"drag\" style=\"position:absolute;left:843px;top:681px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_88\" class=\"drag\" style=\"position:absolute;left:410px;top:213px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P <br>CONNECOTR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_89\" class=\"drag\" style=\"position:absolute;left:393px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p10_90\" class=\"drag\" style=\"position:absolute;left:430px;top:642px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_91\" class=\"drag\" style=\"position:absolute;left:604px;top:461px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}