with(document) {
write("<div id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect4\"class=\"drag\" style=\"width:950px;position:relative;height:1071px;\">");
write("<img id=\"img4\" src=\"../img/SJD7ECJA20300000000EAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:644px;top:220px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:644px;top:178px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:644px;top:112px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:731px;top:306px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:838px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:838px;top:105px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:709px;top:138px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:709px;top:171px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:612px;top:271px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:612px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:612px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:612px;top:86px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:692px;top:39px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:474px;top:321px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:444px;top:321px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:838px;top:138px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:500px;top:321px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:500px;top:41px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:443px;top:41px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:644px;top:235px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:612px;top:153px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:611px;top:243px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:612px;top:228px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:764px;top:387px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" class=\"drag\" style=\"position:absolute;left:609px;top:398px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" class=\"drag\" style=\"position:absolute;left:644px;top:390px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" class=\"drag\" style=\"position:absolute;left:609px;top:384px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" class=\"drag\" style=\"position:absolute;left:644px;top:375px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" class=\"drag\" style=\"position:absolute;left:609px;top:369px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" class=\"drag\" style=\"position:absolute;left:644px;top:361px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" class=\"drag\" style=\"position:absolute;left:194px;top:346px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" class=\"drag\" style=\"position:absolute;left:194px;top:362px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" class=\"drag\" style=\"position:absolute;left:194px;top:390px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" class=\"drag\" style=\"position:absolute;left:194px;top:407px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELDGND<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" class=\"drag\" style=\"position:absolute;left:243px;top:354px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" class=\"drag\" style=\"position:absolute;left:242px;top:397px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" class=\"drag\" style=\"position:absolute;left:318px;top:346px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17 (21)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" class=\"drag\" style=\"position:absolute;left:314px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br>(20)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" class=\"drag\" style=\"position:absolute;left:255px;top:319px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P CONNECTOR<br>(24P CONNECTOR)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" class=\"drag\" style=\"position:absolute;left:194px;top:263px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" class=\"drag\" style=\"position:absolute;left:194px;top:278px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" class=\"drag\" style=\"position:absolute;left:229px;top:270px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" class=\"drag\" style=\"position:absolute;left:305px;top:262px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15 (23)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" class=\"drag\" style=\"position:absolute;left:247px;top:236px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P CONNECTOR<br>(24P CONNECTOR)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" class=\"drag\" style=\"position:absolute;left:711px;top:690px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" class=\"drag\" style=\"position:absolute;left:756px;top:566px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" class=\"drag\" style=\"position:absolute;left:194px;top:483px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" class=\"drag\" style=\"position:absolute;left:194px;top:500px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGP1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" class=\"drag\" style=\"position:absolute;left:225px;top:490px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" class=\"drag\" style=\"position:absolute;left:194px;top:514px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" class=\"drag\" style=\"position:absolute;left:194px;top:531px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGP2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" class=\"drag\" style=\"position:absolute;left:225px;top:522px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" class=\"drag\" style=\"position:absolute;left:194px;top:546px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" class=\"drag\" style=\"position:absolute;left:194px;top:563px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGP3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" class=\"drag\" style=\"position:absolute;left:225px;top:553px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" class=\"drag\" style=\"position:absolute;left:278px;top:586px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" class=\"drag\" style=\"position:absolute;left:332px;top:482px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" class=\"drag\" style=\"position:absolute;left:332px;top:514px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" class=\"drag\" style=\"position:absolute;left:332px;top:545px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" class=\"drag\" style=\"position:absolute;left:313px;top:454px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" class=\"drag\" style=\"position:absolute;left:354px;top:490px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" class=\"drag\" style=\"position:absolute;left:354px;top:522px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" class=\"drag\" style=\"position:absolute;left:354px;top:553px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" class=\"drag\" style=\"position:absolute;left:405px;top:480px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" class=\"drag\" style=\"position:absolute;left:424px;top:480px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" class=\"drag\" style=\"position:absolute;left:443px;top:480px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" class=\"drag\" style=\"position:absolute;left:463px;top:481px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" class=\"drag\" style=\"position:absolute;left:412px;top:415px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" class=\"drag\" style=\"position:absolute;left:366px;top:435px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" class=\"drag\" style=\"position:absolute;left:277px;top:783px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" class=\"drag\" style=\"position:absolute;left:617px;top:508px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_72\" class=\"drag\" style=\"position:absolute;left:635px;top:548px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_73\" class=\"drag\" style=\"position:absolute;left:494px;top:583px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br>(24)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_74\" class=\"drag\" style=\"position:absolute;left:635px;top:601px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_75\" class=\"drag\" style=\"position:absolute;left:635px;top:621px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_76\" class=\"drag\" style=\"position:absolute;left:635px;top:641px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_77\" class=\"drag\" style=\"position:absolute;left:635px;top:660px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_78\" class=\"drag\" style=\"position:absolute;left:581px;top:478px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p4_79\" class=\"drag\" style=\"position:absolute;left:180px;top:219px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_80\" class=\"drag\" style=\"position:absolute;left:244px;top:1024px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: LHD model<br>*2: RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p4_81\" class=\"drag\" style=\"position:absolute;left:610px;top:920px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUSES:<br>UNDER-HOOD FUSE/RELAY BOX:<br>(1)No. 14 +B STOP &amp; HORN (15 A)<br>(2)No. 1 +B GLOW (70 A)<br>(3)No. 1 BATTERY (100 A)<br>(4)No. 23 +B BACK UP (10 A)<br>(5)No. 2 IG1 MAIN (50 A)<br>(6)No. 28 +B ECU SUB (+B ECM SUB)(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_82\" class=\"drag\" style=\"position:absolute;left:358px;top:618px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p4_83\" class=\"drag\" style=\"position:absolute;left:387px;top:595px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P<br>CONNECTOR<br>(24P<br>CONNECTOR)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_84\" class=\"drag\" style=\"position:absolute;left:451px;top:656px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_85\" class=\"drag\" style=\"position:absolute;left:758px;top:678px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_86\" class=\"drag\" style=\"position:absolute;left:405px;top:728px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_87\" class=\"drag\" style=\"position:absolute;left:329px;top:706px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_88\" class=\"drag\" style=\"position:absolute;left:563px;top:777px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p4_89\" class=\"drag\" style=\"position:absolute;left:631px;top:777px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p4_90\" class=\"drag\" style=\"position:absolute;left:769px;top:776px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p4_91\" class=\"drag\" style=\"position:absolute;left:213px;top:844px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_92\" class=\"drag\" style=\"position:absolute;left:333px;top:877px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_93\" class=\"drag\" style=\"position:absolute;left:333px;top:857px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_94\" class=\"drag\" style=\"position:absolute;left:333px;top:840px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_95\" class=\"drag\" style=\"position:absolute;left:333px;top:820px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_96\" class=\"drag\" style=\"position:absolute;left:830px;top:777px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Y<br></b></nobr>");
write("</p>");
write("<p id=\"p4_97\" class=\"drag\" style=\"position:absolute;left:456px;top:1034px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p4_98\" class=\"drag\" style=\"position:absolute;left:579px;top:850px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_99\" class=\"drag\" style=\"position:absolute;left:522px;top:873px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_100\" class=\"drag\" style=\"position:absolute;left:521px;top:839px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_101\" class=\"drag\" style=\"position:absolute;left:521px;top:856px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p4_102\" class=\"drag\" style=\"position:absolute;left:506px;top:934px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p4_103\" class=\"drag\" style=\"position:absolute;left:450px;top:934px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_104\" class=\"drag\" style=\"position:absolute;left:450px;top:988px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_105\" class=\"drag\" style=\"position:absolute;left:483px;top:960px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_106\" class=\"drag\" style=\"position:absolute;left:464px;top:950px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}