with(document) {
write("<div id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1017px;\">");
write("<div id=\"rect3\"class=\"drag\" style=\"width:950px;position:relative;height:1017px;\">");
write("<img id=\"img3\" src=\"../img/SJD7EC0J54230100000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1017px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:298px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:327px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:327px;top:786px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:298px;top:787px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:658px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:658px;top:787px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ELD unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:327px;top:858px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:298px;top:858px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:658px;top:858px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:88px;top:915px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G304<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:427px;top:858px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:456px;top:858px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:456px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:427px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:129px;top:965px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:122px;top:964px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:105px;top:965px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:658px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Hood latch switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:658px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlight leveling motor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:327px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:299px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:327px;top:529px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:299px;top:529px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:299px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:327px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:658px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight washer motor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:327px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:299px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:299px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:327px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:658px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield wiper motor*<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:658px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Brake fluid level switch*<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:658px;top:529px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left front fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:377px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction connector<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:499px;top:529px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:527px;top:529px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:88px;top:765px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:658px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Auto wiper relay<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:327px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:298px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:527px;top:94px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:499px;top:94px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:380px;top:47px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction connector<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:658px;top:430px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C condensor fan motor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:298px;top:287px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:327px;top:287px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:658px;top:287px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Blower motor relay <br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:658px;top:94px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left HID unit (KG)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:327px;top:429px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:298px;top:430px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:658px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Fan control relay<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:658px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left front turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:327px;top:222px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:298px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:298px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:327px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:658px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:327px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:298px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:298px;top:94px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:88px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:327px;top:94px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:129px;top:944px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:122px;top:942px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:105px;top:944px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" class=\"drag\" style=\"position:absolute;left:511px;top:242px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER-HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" class=\"drag\" style=\"position:absolute;left:298px;top:650px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" class=\"drag\" style=\"position:absolute;left:327px;top:650px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" class=\"drag\" style=\"position:absolute;left:658px;top:650px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight leveling switch*<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" class=\"drag\" style=\"position:absolute;left:804px;top:29px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>* : LHD type<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}