with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:591px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:591px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0J54300031125FCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:591px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:318px;top:216px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:619px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:383px;top:328px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:442px;top:327px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:394px;top:565px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:447px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:527px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:580px;top:436px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Wire side of<br>female terminals<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}