with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:554px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0J46643400000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:886px;top:21px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:886px;top:14px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:893px;top:14px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:757px;top:471px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:751px;top:471px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:751px;top:464px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:757px;top:464px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:764px;top:414px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:758px;top:413px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:758px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:764px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:742px;top:414px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:737px;top:413px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:737px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:742px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:727px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:628px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:623px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:623px;top:413px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:628px;top:414px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:617px;top:464px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:612px;top:464px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:612px;top:471px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:617px;top:471px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:607px;top:414px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:601px;top:413px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:601px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:607px;top:406px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:527px;top:461px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:527px;top:415px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:882px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:827px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:835px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:892px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:827px;top:234px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:880px;top:234px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:502px;top:309px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:810px;top:309px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:686px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:651px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:695px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:660px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:562px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:570px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:590px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:591px;top:388px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:544px;top:393px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>KEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:611px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:599px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:611px;top:388px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:602px;top:488px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:600px;top:527px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:585px;top:443px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:617px;top:437px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UN-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:617px;top:443px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:735px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:756px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:620px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:518px;top:527px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:520px;top:488px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:495px;top:154px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:570px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:527px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:638px;top:192px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INTEGRATED CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:527px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:519px;top:249px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:726px;top:388px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:748px;top:388px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:756px;top:443px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:740px;top:527px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:741px;top:488px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:724px;top:443px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:756px;top:437px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UN-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:748px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:519px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:852px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:858px;top:427px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:858px;top:449px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:773px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:851px;top:388px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:860px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:527px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:570px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:781px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:642px;top:309px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:562px;top:249px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:513px;top:201px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(KEYLESS <br>SET)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:556px;top:201px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(KEYLESS <br>UNSET)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:828px;top:151px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INTEGRATED CONTROL UNIT <br>(TURN SIGNAL/HAZARD <br>DRIVE CIRCUIT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:542px;top:437px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>AUDIO <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:638px;top:426px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>KEY <br>CYLINDER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:692px;top:394px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOOR <br>LOCK KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:777px;top:429px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR LOCK <br>KNOB <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:867px;top:429px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HOOD <br>SWITCH <br>(Closed : <br>Hood open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:893px;top:21px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: LHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:852px;top:527px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:198px;top:214px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:212px;top:42px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:423px;top:535px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:416px;top:535px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:416px;top:528px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:423px;top:528px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:213px;top:181px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:209px;top:145px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:198px;top:197px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:294px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:212px;top:70px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:294px;top:145px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:303px;top:232px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:303px;top:157px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:303px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:295px;top:248px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:140px;top:34px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 2 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:90px;top:34px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 1 (100 A) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:355px;top:467px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:355px;top:445px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:284px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:420px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:377px;top:398px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:348px;top:427px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:284px;top:427px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:220px;top:398px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:127px;top:398px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:148px;top:427px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:98px;top:398px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:77px;top:427px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:77px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:298px;top:34px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:237px;top:248px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:141px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:74px;top:248px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:85px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:145px;top:145px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:102px;top:145px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:140px;top:62px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 23 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:102px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:112px;top:73px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:112px;top:67px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:85px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:292px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:428px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:359px;top:248px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:367px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:246px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:110px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:270px;top:42px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:247px;top:48px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:237px;top:35px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:227px;top:22px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:183px;top:42px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:87px;top:67px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:87px;top:73px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:348px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:357px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:220px;top:427px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:148px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:349px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:347px;top:527px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:157px;top:347px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:217px;top:306px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:102px;top:248px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:67px;top:22px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:40px;top:29px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:203px;top:197px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ALARM <br>CONTROL <br>SIREN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:203px;top:214px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ULTRASONIC <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:289px;top:15px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:317px;top:151px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE <br>ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:164px;top:170px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY <br>HORN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:310px;top:201px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:367px;top:358px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INTEGRATED <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:210px;top:358px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INTEGRATED <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:103px;top:354px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INTEGRATED <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:92px;top:446px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:164px;top:444px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:235px;top:446px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT REAR <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:299px;top:446px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT REAR <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:364px;top:446px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION <br>KEY <br>SWITCH <br>(Closed : <br>Key inserted)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:160px;top:231px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY<br>HORN<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}