with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:655px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:655px;\">");
write("<img id=\"img1\" src=\"../img/SJD7ECJA20323500000CAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:655px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:693px;top:34px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:695px;top:130px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:792px;top:212px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:826px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To PGM-FI<br>MAIN<br>RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:811px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VARIOUS<br>SENSORS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:674px;top:269px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:716px;top:323px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:551px;top:130px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:344px;top:605px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR COOLER<br>BYPASS VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:410px;top:580px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:494px;top:558px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:530px;top:500px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR CONTROL SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:270px;top:144px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR COOLER<br>BYPASS CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}