with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:554px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC2J10300000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:515px;top:212px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:524px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:564px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:549px;top:164px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:570px;top:142px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:555px;top:212px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:711px;top:67px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:595px;top:67px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:892px;top:524px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:852px;top:333px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:851px;top:305px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:665px;top:305px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:665px;top:333px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:594px;top:333px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:594px;top:391px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:852px;top:391px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:665px;top:391px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:763px;top:433px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3.9 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:735px;top:433px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1.2 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:707px;top:433px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>470 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:678px;top:433px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>270 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:794px;top:426px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>10 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:678px;top:425px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>100 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:764px;top:461px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:764px;top:456px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:707px;top:464px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:713px;top:464px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:684px;top:464px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:735px;top:456px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:735px;top:461px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(-)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:585px;top:489px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:792px;top:459px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:707px;top:459px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:707px;top:453px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VOL.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:678px;top:453px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VOL.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:678px;top:459px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:678px;top:464px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:849px;top:11px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1 : With premium audio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:752px;top:49px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:634px;top:49px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:652px;top:148px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:672px;top:148px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:715px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:737px;top:148px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:712px;top:148px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:772px;top:219px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:794px;top:219px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:772px;top:148px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:794px;top:148px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:889px;top:17px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:860px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:850px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>STR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:850px;top:272px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:659px;top:272px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:659px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>REMOTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:674px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:905px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:884px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:892px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:884px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RR+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:905px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:884px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:906px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RR-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:914px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:860px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:853px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RL-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:830px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:851px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:830px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:839px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:782px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:773px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FR+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:737px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:715px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:772px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:794px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:794px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:772px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:795px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FR-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:803px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:685px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:678px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FL-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:652px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:672px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:676px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:651px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:594px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:615px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:656px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:830px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:851px;top:112px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:664px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:706px;top:258px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:654px;top:60px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>FRONT SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:771px;top:61px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>FRONT SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:826px;top:61px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>REAR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:880px;top:61px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>REAR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:874px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:689px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:617px;top:359px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:589px;top:297px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:508px;top:152px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SECURITY <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:209px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:242px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:210px;top:272px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:242px;top:272px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:205px;top:414px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:268px;top:362px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:237px;top:435px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(With navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:126px;top:251px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:126px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:137px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:156px;top:219px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ANTENNA SUBLEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:128px;top:205px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:249px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:240px;top:337px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:217px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:207px;top:337px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:176px;top:272px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:176px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:176px;top:337px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:184px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:71px;top:205px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:80px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:67px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ILLUMI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:67px;top:251px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:160px;top:169px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ANTENNA LEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:160px;top:81px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ROOF ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:127px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:69px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BULB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:69px;top:272px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ILLUMI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:71px;top:319px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:80px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:300px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:261px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:192px;top:37px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:300px;top:205px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:137px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:129px;top:319px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:272px;top:101px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:272px;top:95px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:128px;top:526px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:261px;top:205px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:269px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:311px;top:95px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:311px;top:101px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:309px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:201px;top:258px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:49px;top:29px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 1 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:216px;top:17px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:11px;top:24px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:102px;top:29px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:44px;top:17px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:101px;top:51px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 2 (OP) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:157px;top:37px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:272px;top:37px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:225px;top:31px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:234px;top:43px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:157px;top:58px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:334px;top:95px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:161px;top:128px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WINDOW <br>ANTENNA COIL <br>(AMPLIFIER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:67px;top:147px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:62px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:342px;top:405px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUXILIARY JACK ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:316px;top:272px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:323px;top:289px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:349px;top:289px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:375px;top:288px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:400px;top:288px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:426px;top:289px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:451px;top:289px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:342px;top:272px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:368px;top:272px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:393px;top:272px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:418px;top:272px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:444px;top:266px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>SHIELD<br>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:316px;top:337px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:341px;top:337px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:367px;top:337px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:394px;top:337px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:419px;top:337px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:445px;top:314px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:323px;top:381px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:349px;top:381px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:375px;top:381px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:401px;top:381px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:426px;top:381px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:316px;top:392px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:341px;top:392px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:368px;top:392px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:393px;top:392px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:418px;top:392px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUX<br>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:455px;top:435px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}