with(document) {
write("<div id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect3\"class=\"drag\" style=\"width:950px;position:relative;height:1108px;\">");
write("<img id=\"img3\" src=\"../img/SJD7ECJJ54260400000EAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:629px;top:381px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:472px;top:380px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:387px;top:273px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:630px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:475px;top:251px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:389px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:473px;top:144px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:239px;top:176px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HORN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:52px;top:116px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:57px;top:67px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:159px;top:23px;font-weight:normal;font-size:6.7pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:141px;top:360px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:216px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 8 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:216px;top:658px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:630px;top:673px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Integrated control unit (IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:177px;top:360px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:205px;top:401px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 12 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:630px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:473px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:199px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 25 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:466px;top:544px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:630px;top:581px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Alternator<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:464px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:428px;top:662px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:630px;top:702px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Combination light switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:388px;top:701px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:630px;top:766px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge assembly<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:473px;top:766px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:177px;top:932px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:142px;top:932px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:213px;top:858px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 11 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:205px;top:894px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 13 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:629px;top:610px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:659px;top:609px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ELD unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:466px;top:873px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:389px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:475px;top:609px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:475px;top:701px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:630px;top:795px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight leveling switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:473px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:54px;top:439px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:50px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:630px;top:630px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MAF sensor/IAT sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:473px;top:730px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:630px;top:745px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Security control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:630px;top:731px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Keyless receiver unit<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:473px;top:823px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:630px;top:823px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Brake pedal position switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:630px;top:838px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlight leveling motor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:630px;top:852px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlight leveling motor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:630px;top:870px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light control unit <br>( Via rear fog light relay )<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:630px;top:545px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window defogger/power <br>mirror defogger switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:28px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 18 (7.5 A) <br>UNDER-DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:257px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER MIRROR  <br>DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:29px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 14 (15 A) <br>UNDER-HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:630px;top:145px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Security horn <br>(Via security horn relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:630px;top:173px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Security control unit <br>(Via security horn relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:630px;top:327px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn (High)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:475px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:630px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn (Low)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:678px;top:222px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:678px;top:299px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:787px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*1 : With security horn<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:787px;top:36px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2 : Without security horn<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}