with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:543px;\">");
write("<img id=\"img2\" src=\"../img/SJD7ECKA20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:17px;top:194px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:257px;top:496px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:641px;top:496px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE OIL LEVEL<br>SENSOR SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:765px;top:431px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STARTER<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:316px;top:58px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:178px;top:92px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:391px;top:38px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:821px;top:307px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:815px;top:356px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:603px;top:504px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:724px;top:452px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:571px;top:503px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:442px;top:28px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:495px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:641px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:562px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:782px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:143px;top:403px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:512px;top:512px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:479px;top:502px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:423px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:451px;top:509px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:378px;top:496px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}