with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1055px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1055px;\">");
write("<img id=\"img1\" src=\"../img/SJD7ECJA20300062951CAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1055px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:237px;top:127px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:236px;top:216px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:91px;top:153px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:231px;top:437px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:138px;top:507px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:234px;top:547px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:158px;top:574px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:481px;top:516px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:460px;top:494px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:551px;top:589px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:553px;top:508px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:592px;top:514px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:534px;top:443px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:478px;top:442px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:474px;top:419px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:444px;top:394px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:622px;top:428px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:674px;top:431px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:688px;top:360px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:534px;top:310px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:629px;top:235px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:649px;top:135px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:771px;top:121px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:696px;top:208px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:744px;top:230px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:795px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:861px;top:223px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:721px;top:163px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:821px;top:82px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:794px;top:212px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:452px;top:594px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:425px;top:630px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:38px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VACUUM PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:38px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TURBOCHARGER BOOST CONTROL SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:38px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TURBOCHARGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:38px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WARM UP CATALYTIC CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:16px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:16px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:16px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:16px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:16px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:16px;top:784px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:15px;top:800px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:16px;top:832px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:16px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:16px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:16px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:16px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:16px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:16px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:15px;top:960px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:15px;top:992px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:502px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:502px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:502px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:501px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:502px;top:784px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:502px;top:816px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:502px;top:832px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:502px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:502px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:501px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:501px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:502px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:502px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:502px;top:944px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:38px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CATALYTIC CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:38px;top:784px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AIR CLEANER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:38px;top:800px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MASS AIR FLOW (MAF) SENSOR/<br>INTAKE AIR TEMPERATURE (IAT) SENSOR 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:38px;top:832px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:38px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT POSITION (CMP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:38px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLOW PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:38px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COOLANT TEMPERATURE (ECT) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:38px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT POSITION (CKP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:38px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTER COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:38px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) COOLER<br>BYPASS CONTROL SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:38px;top:960px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) COOLER<br>BYPASS VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:38px;top:992px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:524px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:524px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:524px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD RUNNER CONTROL (IMRC)<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:524px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD RUNNER CONTROL (IMRC) VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:524px;top:784px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE PRESSURE (MAP) SENSOR/<br>INTAKE AIR TEMPERATURE (IAT) SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:501px;top:960px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:524px;top:816px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:524px;top:832px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:524px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HAND PRIMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:524px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RAIL PRESSURE (FRP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:524px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL HEATER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:524px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TEMPERATURE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:524px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:524px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILTER WATER LEVEL SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:524px;top:944px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:524px;top:960px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:501px;top:976px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:524px;top:976px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE OIL LEVEL SENSOR<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}