with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1085px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0J54300000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:271px;top:73px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:798px;top:856px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:798px;top:791px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:780px;top:1038px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:544px;top:1038px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G481<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:547px;top:631px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:783px;top:931px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:106px;top:820px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>As<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:118px;top:598px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WINDSHIELD WIPER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:142px;top:677px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:177px;top:698px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:691px;top:88px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:628px;top:100px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:611px;top:77px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:584px;top:48px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:547px;top:88px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:257px;top:48px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:349px;top:73px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:186px;top:63px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:761px;top:173px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:761px;top:161px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:99px;top:598px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:741px;top:301px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:461px;top:88px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:740px;top:231px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:446px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:477px;top:463px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:416px;top:431px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MIST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:507px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:537px;top:431px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:335px;top:327px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WINDSHIELD WIPER/WASHER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:549px;top:266px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:80px;top:467px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:388px;top:631px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:298px;top:674px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:298px;top:745px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:296px;top:831px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:623px;top:631px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:774px;top:731px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:782px;top:631px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:346px;top:631px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:182px;top:931px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:282px;top:661px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:268px;top:661px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:268px;top:646px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:282px;top:646px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:282px;top:732px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:268px;top:732px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:268px;top:718px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:282px;top:718px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:282px;top:818px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:268px;top:818px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:268px;top:803px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:282px;top:804px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:217px;top:904px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:204px;top:903px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:204px;top:889px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:217px;top:889px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:347px;top:874px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:388px;top:874px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:806px;top:157px;font-weight:normal;font-size:6.7pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:813px;top:400px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:631px;top:490px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INTERMITTENT WIPER <br>CONTROL CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:655px;top:560px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INTERMITTENT DWELL <br>TIME CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:813px;top:814px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:346px;top:967px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>REAR WIPER <br>INTERMITTENT <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:811px;top:26px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:797px;top:26px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:797px;top:41px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:811px;top:69px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: KU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:797px;top:55px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:797px;top:69px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:811px;top:41px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: LHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:168px;top:1051px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:168px;top:1037px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:182px;top:1037px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:182px;top:1052px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: G302<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:774px;top:330px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:760px;top:329px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:760px;top:315px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:774px;top:315px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:379px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:365px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:365px;top:599px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:379px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:422px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:408px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:408px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:422px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:580px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:566px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:566px;top:599px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:580px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:659px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:645px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:645px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:659px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:816px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:802px;top:614px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:802px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:816px;top:600px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: 6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:811px;top:55px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: Except KU<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}