with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:319px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:319px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB0E10410600000CAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:319px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:89px;top:25px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>100 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:108px;top:147px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:115px;top:269px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:458px;top:288px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Vehicle speed<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:193px;top:14px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ASCENDING MODE: Upshift Schedule<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:615px;top:101px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: FLAT ROAD MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:615px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: GRADUAL ASCENDING MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:615px;top:157px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: MEDIUM ASCENDING MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:615px;top:188px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: STEEP ASCENDING MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:400px;top:42px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>3RD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:458px;top:42px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>4TH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:423px;top:153px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>4TH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:299px;top:42px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>2ND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:214px;top:42px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>1ST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:480px;top:153px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>5TH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:615px;top:215px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: HEAVY STEEP ASCENDING MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:356px;top:42px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>3RD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:269px;top:42px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>2ND<br></b></nobr>");
write("</p>");
write("</div>");
write("<svg id=\"bl1_1\" class=\"drag\" style=\"position:absolute; left:92px; top:95px; width:4px; height:130px; overflow:visible;\"><line x1=\"1\" y1=\"128\" x2=\"0\" y2=\"0\" stroke=\"black\" stroke-width=\"1\"/></svg>");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" class=\"drag\" on=\"true\" string=\"Throttle opening\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</div>");
}