with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:991px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:991px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB2E10411412282MFAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:991px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:806px;top:389px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>RELEASE LID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:216px;top:383px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARK PIN<br>SWITCH <br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:38px;top:655px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HARNESS<br>BAND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:18px;top:302px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER/<br>BRACKET BASE<br>ASSEMBLY <br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:822px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEVER COVER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:818px;top:485px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T GEAR<br>POSITION<br>INDICATOR<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:23px;top:729px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>STOP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:713px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SCREW <br>3 N·m (0.3 kgf·m, 2 lbf·ft)<br></b>Apply non-hardening<br>thread lock sealant.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:508px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER<br>KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:821px;top:254px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER<br>BUTTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:778px;top:304px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D3 SWITCH <br>COVER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:389px;top:138px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:225px;top:139px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SILICONE GREASE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:225px;top:89px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER ROD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:443px;top:326px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T GEAR<br>POSITION<br>INDICATOR PANEL <br>LIGHT BULB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:413px;top:276px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>RELEASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:244px;top:338px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>RELEASE SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:27px;top:780px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>STOP <br>CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:164px;top:900px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>SOLENOID PLUNGER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:205px;top:857px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PLUNGER <br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:269px;top:805px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>SOLENOID <br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:308px;top:872px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONNECTOR<br>CLAMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:403px;top:915px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONNECTOR <br>(8P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:712px;top:930px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T GEAR<br>POSITION INDICATOR<br>PANEL BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:823px;top:688px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T GEAR <br>POSITION <br>INDICATOR<br>PANEL BASE<br>COVER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:4px;top:463px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SILICONE GREASE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:48px;top:871px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SILICONE GREASE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:749px;top:93px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D3 SWITCH <br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:786px;top:168px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SILICONE GREASE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:787px;top:118px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BUTTON SPRING<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}