with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:831px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB0E10480100000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:219px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT SOLENOID VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:107px;top:405px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SERVO BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:136px;top:466px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR VALVE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:118px;top:757px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN VALVE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:739px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID<br>VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:775px;top:76px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID<br>VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:823px;top:291px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T CLUTCH<br>PRESSURE<br>CONTROL<br>SOLENOID<br>VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:154px;top:113px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT SOLENOID VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:557px;top:121px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT SOLENOID <br>VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:521px;top:76px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT SOLENOID <br>VALVE E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:455px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT SOLENOID <br>VALVE D<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}