with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0J54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:43px;top:54px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:554px;top:733px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLOWER MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:622px;top:769px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IGNITION COIL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:656px;top:804px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHT RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:677px;top:846px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHT RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:654px;top:994px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HORN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:565px;top:1032px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C COMPRESSOR CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:494px;top:1056px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER MIRROR DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:338px;top:1032px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/F SENSOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:205px;top:939px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUTO WIPER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:257px;top:734px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WINDOW<br>DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:162px;top:1003px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:401px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C CONDENSER<br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:265px;top:92px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUXILIARY UNDER-HOOD RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:744px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RADIATOR FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:751px;top:198px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FAN CONTROL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:1px;top:1072px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>RHD type is shown, LHD type is similar.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}