with(document) {
write("<div id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1017px;\">");
write("<div id=\"rect3\"class=\"drag\" style=\"width:950px;position:relative;height:1017px;\">");
write("<img id=\"img3\" src=\"../img/SJD7EC0J54260400000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1017px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:730px;top:926px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rain sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:530px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:229px;top:911px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 31 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:69px;top:905px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:730px;top:590px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C compressor clutch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:730px;top:654px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:529px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:228px;top:574px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 29 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:230px;top:710px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 15 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:232px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 9 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:629px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:134px;top:156px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:127px;top:205px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:219px;top:98px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:521px;top:233px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:232px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 8 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:730px;top:169px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:529px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:530px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:230px;top:289px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 11 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:730px;top:305px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Blower motor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:667px;top:419px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:529px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:729px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radiator fan motor<br>(Via radiator fan relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:230px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 10 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:529px;top:511px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:529px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:730px;top:726px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/F sensor (Sensor 1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:243px;top:29px;font-weight:normal;font-size:6.7pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:101px;top:113px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 18 (7.5 A) <br>UNDER-DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:327px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:335px;top:260px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLOWER <br>MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:327px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C COMPRESSOR <br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:338px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/F SENSOR<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:758px;top:227px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window defogger/power <br>mirror defogger switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:51px;top:832px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AUTO WIPER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:378px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No. 19<br>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:730px;top:511px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C condensor fan motor<br>(Via A/C condensor fan relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:525px;top:654px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:529px;top:726px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:526px;top:791px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:730px;top:790px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM (SRLY)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:622px;top:861px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:527px;top:861px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:730px;top:862px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Engine oil level sensor<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}