with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:543px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB0E10480154501MEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:619px;top:30px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m (1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:634px;top:222px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:557px;top:463px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SERVO VALVE/SHIFT FORK SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:223px;top:475px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING SEAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:627px;top:84px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ACCUMULATOR COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:631px;top:141px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:638px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5TH ACCUMULATOR PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:696px;top:332px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SERVO BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:559px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:330px;top:447px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT VALVE D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:252px;top:345px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:140px;top:223px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4TH ACCUMULATOR PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:289px;top:185px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:293px;top:138px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:183px;top:98px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2ND ACCUMULATOR PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:417px;top:93px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:417px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:320px;top:325px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:423px;top:239px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}