with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:959px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:959px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB0E10480139301KCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:959px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:277px;top:69px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>Two Bolts<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:105px;top:116px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF<br>STRAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:283px;top:249px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:34px;top:270px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 Bolts<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:79px;top:666px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOWEL PINS,<br>Two Pins<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:424px;top:542px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>Three Bolts<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:813px;top:673px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOWEL PINS,<br>Two Pins<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:813px;top:628px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF PUMP <br>DRIVEN GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:813px;top:586px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF PUMP DRIVEN<br>GEAR SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:813px;top:544px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN VALVE <br>BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:813px;top:501px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COOLER CHECK<br>VALVE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:813px;top:457px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COOLER CHECK<br>VALVE SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:805px;top:415px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHECK BALLS,<br>Two Balls<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:777px;top:325px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOWEL PINS,<br>Two Pins<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:773px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF FEED PIPES,<br>8 x 198 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:661px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>Eight Bolts<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:569px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR<br>VALVE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:473px;top:51px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>One Bolts<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:458px;top:349px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF JOINT <br>PIPES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:52px;top:499px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SERVO BODY <br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:198px;top:926px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE CONVERTER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:348px;top:631px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF MAGNET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:348px;top:594px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF PUMP DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:749px;top:303px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STATOR SHAFT STOP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:422px;top:401px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STATOR SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:46px;top:600px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SERVO <br>SEPARATOR <br>PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:798px;top:362px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR <br>SEPARATOR<br>PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:813px;top:717px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAIN <br>SEPARATOR <br>PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:749px;top:262px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:370px;top:212px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF FEED PIPES,<br>8 x 220 mm<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}