with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:671px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:671px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB0E10474000000CAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:671px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:295px;top:43px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:320px;top:281px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>LOCK-UP<br>SHIFT VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:312px;top:455px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>LOCK-UP<br>CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:222px;top:502px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>RELIEF VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:129px;top:540px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>ATF<br>COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:190px;top:456px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>COOLER<br>CHECK<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:136px;top:371px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:289px;top:561px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>REGULATOR<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:657px;top:636px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>ATF PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:523px;top:174px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE CONTROL SOLENOID VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:473px;top:445px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IDLER SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:473px;top:456px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:473px;top:467px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:473px;top:478px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:473px;top:487px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FINAL DRIVE<br>GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:473px;top:498px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SECONDARY<br>SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:231px;top:234px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:309px;top:224px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:324px;top:210px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:210px;top:269px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:202px;top:304px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:219px;top:304px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:246px;top:305px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:266px;top:305px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:294px;top:305px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:311px;top:305px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:280px;top:272px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:256px;top:272px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:228px;top:271px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:362px;top:401px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>97<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:344px;top:401px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:318px;top:401px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:288px;top:401px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:244px;top:433px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:262px;top:437px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:279px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:243px;top:447px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:327px;top:436px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:215px;top:403px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:165px;top:438px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:205px;top:436px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:315px;top:513px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:336px;top:514px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:271px;top:549px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:294px;top:545px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:286px;top:594px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:373px;top:529px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:399px;top:529px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:364px;top:563px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:403px;top:563px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:473px;top:397px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:448px;top:415px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:473px;top:421px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:473px;top:432px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:525px;top:117px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:507px;top:157px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:537px;top:157px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:562px;top:134px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:547px;top:104px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT SOLENOID VALVE E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:463px;top:217px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:476px;top:226px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:504px;top:198px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:517px;top:217px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:528px;top:217px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:680px;top:262px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT VALVE A and D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:680px;top:348px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>MANUAL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:300px;top:441px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:263px;top:481px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}