with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1108px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB0E10410700000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:691px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:661px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:255px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:274px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:203px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:278px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:769px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:787px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:676px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:492px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:200px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:322px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:322px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:614px;top:1058px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:385px;top:1058px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:157px;top:1058px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:332px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:293px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:322px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:780px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:780px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:468px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:447px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:466px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:428px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:462px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:417px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:431px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:430px;top:1071px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:661px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:646px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:417px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:314px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:293px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:307px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:410px;top:917px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PCM Harness Connector Terminal Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:638px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:694px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:713px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:750px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:705px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:735px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:735px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:691px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:705px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:720px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:661px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:752px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:771px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:790px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:734px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:715px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:697px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:678px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:660px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:641px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:720px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:181px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:329px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:293px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:218px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:233px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:307px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:307px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:189px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:203px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:248px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:277px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:258px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:239px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:263px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:293px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:521px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:412px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:450px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:561px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:542px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:524px;top:963px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:432px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:447px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:492px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:477px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:462px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:521px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:536px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:507px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:447px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:432px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:417px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:551px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:507px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:551px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:536px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:521px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:477px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:447px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:432px;top:1019px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:521px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:540px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:559px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:503px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:410px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:269px;top:696px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:410px;top:616px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D3 SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:384px;top:616px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A41<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:237px;top:657px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:213px;top:650px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:213px;top:616px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:157px;top:658px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:157px;top:623px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:49px;top:640px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D3 SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:557px;top:270px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:633px;top:278px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:741px;top:278px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:581px;top:270px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:312px;top:417px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:312px;top:400px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:339px;top:417px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:386px;top:435px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:356px;top:149px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:356px;top:321px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:357px;top:368px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:385px;top:332px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:384px;top:281px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:339px;top:142px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:410px;top:314px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CAN L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:384px;top:314px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:384px;top:263px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:410px;top:263px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CAN H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:814px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:728px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:699px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:671px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:642px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:613px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:756px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:785px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:840px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:864px;top:545px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:871px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:842px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:785px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:756px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:613px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:642px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:671px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:699px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:728px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:809px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:872px;top:518px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:581px;top:436px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:625px;top:235px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:581px;top:228px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:559px;top:228px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:521px;top:195px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>To 12 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:78px;top:118px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:458px;top:49px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 7 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:421px;top:29px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:457px;top:78px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:835px;top:466px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:624px;top:409px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:633px;top:449px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:308px;top:53px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:381px;top:53px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:324px;top:93px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:444px;top:215px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>To 5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:634px;top:323px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:872px;top:466px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:835px;top:529px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:799px;top:566px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FWD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:827px;top:566px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RVS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:741px;top:583px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:856px;top:566px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:627px;top:600px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:656px;top:583px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:684px;top:572px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:598px;top:692px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>TRANSMISSION RANGE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:713px;top:572px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:884px;top:566px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:770px;top:600px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:581px;top:316px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:542px;top:316px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP RVS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:541px;top:333px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP FWD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:552px;top:436px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:552px;top:419px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:552px;top:402px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:552px;top:384px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:551px;top:368px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:551px;top:351px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:778px;top:529px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:581px;top:333px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:897px;top:541px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:581px;top:402px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:581px;top:385px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:581px;top:351px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:758px;top:518px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:729px;top:529px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:701px;top:518px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:663px;top:529px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:642px;top:518px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" class=\"drag\" style=\"position:absolute;left:607px;top:529px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" class=\"drag\" style=\"position:absolute;left:581px;top:419px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" class=\"drag\" style=\"position:absolute;left:581px;top:368px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" class=\"drag\" style=\"position:absolute;left:805px;top:517px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" class=\"drag\" style=\"position:absolute;left:607px;top:466px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" class=\"drag\" style=\"position:absolute;left:624px;top:392px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" class=\"drag\" style=\"position:absolute;left:633px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" class=\"drag\" style=\"position:absolute;left:633px;top:357px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" class=\"drag\" style=\"position:absolute;left:625px;top:340px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" class=\"drag\" style=\"position:absolute;left:213px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" class=\"drag\" style=\"position:absolute;left:213px;top:577px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" class=\"drag\" style=\"position:absolute;left:237px;top:550px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" class=\"drag\" style=\"position:absolute;left:363px;top:435px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" class=\"drag\" style=\"position:absolute;left:361px;top:502px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" class=\"drag\" style=\"position:absolute;left:236px;top:280px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" class=\"drag\" style=\"position:absolute;left:235px;top:326px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>D3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" class=\"drag\" style=\"position:absolute;left:237px;top:584px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" class=\"drag\" style=\"position:absolute;left:236px;top:302px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" class=\"drag\" style=\"position:absolute;left:236px;top:257px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" class=\"drag\" style=\"position:absolute;left:236px;top:234px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" class=\"drag\" style=\"position:absolute;left:236px;top:211px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" class=\"drag\" style=\"position:absolute;left:236px;top:188px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" class=\"drag\" style=\"position:absolute;left:135px;top:29px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" class=\"drag\" style=\"position:absolute;left:216px;top:49px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" class=\"drag\" style=\"position:absolute;left:153px;top:49px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No. 1 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" class=\"drag\" style=\"position:absolute;left:91px;top:41px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" class=\"drag\" style=\"position:absolute;left:102px;top:228px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CAN <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" class=\"drag\" style=\"position:absolute;left:268px;top:239px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A/T GEAR <br>POSITION <br>INDICATOR <br>DIMMING <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" class=\"drag\" style=\"position:absolute;left:178px;top:238px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A/T GEAR <br>POSITION <br>INDICATOR <br>DRIVER <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" class=\"drag\" style=\"position:absolute;left:181px;top:361px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>F-CAN <br>TRANSCEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" class=\"drag\" style=\"position:absolute;left:827px;top:269px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" class=\"drag\" style=\"position:absolute;left:833px;top:386px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>STARTER <br>CUT <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" class=\"drag\" style=\"position:absolute;left:444px;top:176px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>POWERTRAIN CONTROL <br>MODULE (PCM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" class=\"drag\" style=\"position:absolute;left:629px;top:61px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" class=\"drag\" style=\"position:absolute;left:339px;top:399px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" class=\"drag\" style=\"position:absolute;left:339px;top:379px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" class=\"drag\" style=\"position:absolute;left:339px;top:339px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" class=\"drag\" style=\"position:absolute;left:263px;top:981px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" class=\"drag\" style=\"position:absolute;left:218px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" class=\"drag\" style=\"position:absolute;left:237px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" class=\"drag\" style=\"position:absolute;left:536px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" class=\"drag\" style=\"position:absolute;left:675px;top:1000px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" class=\"drag\" style=\"position:absolute;left:657px;top:1037px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" class=\"drag\" style=\"position:absolute;left:340px;top:623px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" class=\"drag\" style=\"position:absolute;left:237px;top:623px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" class=\"drag\" style=\"position:absolute;left:38px;top:715px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RHD Model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" class=\"drag\" style=\"position:absolute;left:151px;top:584px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" class=\"drag\" style=\"position:absolute;left:150px;top:550px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" class=\"drag\" style=\"position:absolute;left:339px;top:533px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER-DASH <br>FUSE/RELAY <br>BOX <br>No. 26 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" class=\"drag\" style=\"position:absolute;left:339px;top:577px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INTEGRATED<br>CONTROL<br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" class=\"drag\" style=\"position:absolute;left:52px;top:548px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A/T GEAR<br>POSITION<br>INDICATOR<br>PANEL<br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" class=\"drag\" style=\"position:absolute;left:269px;top:897px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" class=\"drag\" style=\"position:absolute;left:237px;top:858px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" class=\"drag\" style=\"position:absolute;left:213px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" class=\"drag\" style=\"position:absolute;left:213px;top:816px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" class=\"drag\" style=\"position:absolute;left:157px;top:858px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" class=\"drag\" style=\"position:absolute;left:157px;top:824px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" class=\"drag\" style=\"position:absolute;left:49px;top:841px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D3 SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" class=\"drag\" style=\"position:absolute;left:213px;top:743px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" class=\"drag\" style=\"position:absolute;left:213px;top:777px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" class=\"drag\" style=\"position:absolute;left:237px;top:750px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" class=\"drag\" style=\"position:absolute;left:237px;top:784px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" class=\"drag\" style=\"position:absolute;left:237px;top:824px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" class=\"drag\" style=\"position:absolute;left:38px;top:916px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LHD Model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" class=\"drag\" style=\"position:absolute;left:151px;top:785px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" class=\"drag\" style=\"position:absolute;left:150px;top:750px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" class=\"drag\" style=\"position:absolute;left:52px;top:748px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A/T GEAR<br>POSITION<br>INDICATOR<br>PANEL<br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" class=\"drag\" style=\"position:absolute;left:779px;top:877px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" class=\"drag\" style=\"position:absolute;left:582px;top:808px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" class=\"drag\" style=\"position:absolute;left:582px;top:779px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" class=\"drag\" style=\"position:absolute;left:582px;top:750px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" class=\"drag\" style=\"position:absolute;left:582px;top:722px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" class=\"drag\" style=\"position:absolute;left:633px;top:729px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" class=\"drag\" style=\"position:absolute;left:633px;top:757px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" class=\"drag\" style=\"position:absolute;left:624px;top:785px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" class=\"drag\" style=\"position:absolute;left:624px;top:813px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" class=\"drag\" style=\"position:absolute;left:557px;top:722px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" class=\"drag\" style=\"position:absolute;left:557px;top:750px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" class=\"drag\" style=\"position:absolute;left:558px;top:779px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" class=\"drag\" style=\"position:absolute;left:558px;top:807px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LG2<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}