with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:319px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:319px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0J22100000000BBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:319px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:195px;top:73px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:194px;top:38px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON (II)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:195px;top:148px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:194px;top:112px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:195px;top:223px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:194px;top:187px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:66px;top:48px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Ignition<br>Switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:66px;top:122px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Lighting<br>Switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:66px;top:197px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Select/Reset<br>button<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:443px;top:273px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:580px;top:246px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Move to self-diagnosis function.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:310px;top:272px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2 to 5 sec.<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}