with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SJD7ECJA20300000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:829px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:829px;top:144px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:829px;top:188px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:829px;top:231px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:822px;top:170px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:822px;top:257px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:822px;top:344px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:822px;top:431px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:829px;top:275px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:829px;top:318px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:829px;top:362px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:829px;top:405px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:197px;top:549px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CKP+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:197px;top:571px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:197px;top:702px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:197px;top:718px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RPSVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:263px;top:709px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:197px;top:745px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:197px;top:761px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:263px;top:752px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:197px;top:789px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:197px;top:805px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RPSSG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:263px;top:796px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:829px;top:701px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:829px;top:744px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:829px;top:788px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:838px;top:641px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CKP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:829px;top:865px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:829px;top:908px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:829px;top:952px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:263px;top:873px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:263px;top:917px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:263px;top:961px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:197px;top:866px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:197px;top:886px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CMPVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:197px;top:909px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>60<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:197px;top:929px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:197px;top:953px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:197px;top:973px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CMPSG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:838px;top:979px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CMP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:87px;top:19px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:197px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:197px;top:122px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ1+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:197px;top:144px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>74<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:197px;top:188px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:197px;top:209px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ2+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:197px;top:231px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:197px;top:252px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ2−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:197px;top:275px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:197px;top:296px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ3+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:197px;top:318px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>73<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:197px;top:339px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ3−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:197px;top:362px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:197px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ4+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:197px;top:406px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:197px;top:426px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ4−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:263px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:263px;top:152px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:263px;top:196px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:263px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:265px;top:283px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:263px;top:370px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:263px;top:413px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:263px;top:326px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:197px;top:527px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:197px;top:591px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CKP−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:197px;top:615px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:197px;top:635px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CKPSHLD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:263px;top:535px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:263px;top:578px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:263px;top:622px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:187px;top:73px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:197px;top:165px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INJ1−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:839px;top:815px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FRP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:829px;top:527px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:829px;top:570px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:829px;top:613px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:263px;top:1004px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:197px;top:997px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:197px;top:1013px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CMPSHLD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:100px;top:63px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:127px;top:674px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5 V<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}