with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:577px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:577px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0A20326919461FAAD29.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:577px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:38px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:38px;top:296px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:185px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PG2 (BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:185px;top:197px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PG1 (BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:210px;top:296px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PGMETCS (BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:178px;top:450px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>LG1<br>(BRN/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:382px;top:450px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>LG2<br>(BRN/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:150px;top:544px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:181px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ECM/PCM CONNECTORS<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}