with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:911px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EB0E10410459801KCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:77px;top:268px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:707px;top:860px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE CONVERTER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:245px;top:28px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT <br>REVERSE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:70px;top:211px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE SHIFT<br>FORK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:64px;top:303px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT <br>REVERSE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:41px;top:787px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DIFFERENTIAL <br>ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:792px;top:560px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAINSHAFT <br>SUBASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:827px;top:77px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT SOLENOID <br>VALVE COVER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:715px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF LUBRICATION <br>PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:441px;top:28px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION <br>HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:312px;top:132px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE <br>SELECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:145px;top:74px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK WASHER<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:44px;top:393px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY <br>SHAFT<br>SUBASSEMBLY <br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:765px;top:608px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m <br>(1.2 kgf·m, 8.7 lbf·ft)<br>Two Bolts<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:327px;top:481px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BAFFLE <br>PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:838px;top:315px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SOLENOID<br>HARNESS<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:589px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF FEED PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:813px;top:434px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION <br>HOUSING<br>HANGER<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}