with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1055px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1055px;\">");
write("<img id=\"img1\" src=\"../img/SJD7ECJJ54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1055px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:1px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:343px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLOW PLUG CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:708px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PTC HEATER A RELAY<br></b>Wire colors: GRY, WHT,<br>BLU and YEL<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:717px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUXILIARY UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:450px;top:638px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PGM-FI<br>MAIN RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:462px;top:685px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHT<br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:463px;top:764px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHT<br>RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:463px;top:819px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C CONDENSER<br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:418px;top:885px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL HEATER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:330px;top:917px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C COMPRESSOR CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:601px;top:903px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PTC HEATER B RELAY<br></b>Wire colors: BLU, RED,<br>GRN and YEL<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:216px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLOWER<br>MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:106px;top:601px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RADIATOR FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:58px;top:636px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PTC HEATER C RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:246px;top:964px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FAN CONTROL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:112px;top:917px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:51px;top:825px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUTO WIPER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:18px;top:675px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:0px;top:1023px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</div>");
write("</div>");
}