with(document) {
write("<div id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect2\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img2\" src=\"../img/SJD7EC0A20300000000EAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:849px;top:34px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EOP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:271px;top:73px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:193px;top:64px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:193px;top:81px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>POILCS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:848px;top:188px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ROCKER ARM<br>OIL CONTROL<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:271px;top:146px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:193px;top:137px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B34<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:193px;top:154px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:854px;top:354px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:273px;top:297px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:193px;top:287px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:193px;top:305px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:477px;top:259px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:496px;top:259px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:514px;top:259px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:487px;top:191px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:836px;top:45px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:770px;top:53px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:835px;top:64px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:835px;top:288px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:770px;top:91px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:769px;top:166px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:770px;top:295px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:770px;top:314px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:770px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:835px;top:307px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:835px;top:326px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:741px;top:226px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:455px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:507px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:193px;top:325px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:193px;top:342px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:193px;top:363px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:193px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:273px;top:335px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:273px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:554px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:582px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:609px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:628px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:572px;top:360px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:593px;top:549px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:835px;top:83px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:862px;top:425px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br>POSITION<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:857px;top:560px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:273px;top:445px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:193px;top:436px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:193px;top:453px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:835px;top:456px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:770px;top:464px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:193px;top:475px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:193px;top:492px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGRP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:835px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:770px;top:484px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:770px;top:543px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:836px;top:535px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:741px;top:603px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:770px;top:503px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:836px;top:495px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:193px;top:515px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:193px;top:532px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:835px;top:515px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:770px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:557px;top:546px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:827px;top:776px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMT ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:801px;top:648px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:735px;top:656px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:273px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:193px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B39<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:193px;top:685px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMTM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" class=\"drag\" style=\"position:absolute;left:801px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" class=\"drag\" style=\"position:absolute;left:273px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" class=\"drag\" style=\"position:absolute;left:193px;top:717px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B37<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" class=\"drag\" style=\"position:absolute;left:193px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMT+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" class=\"drag\" style=\"position:absolute;left:801px;top:717px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" class=\"drag\" style=\"position:absolute;left:193px;top:755px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B38<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" class=\"drag\" style=\"position:absolute;left:193px;top:772px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMT−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" class=\"drag\" style=\"position:absolute;left:273px;top:764px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" class=\"drag\" style=\"position:absolute;left:801px;top:738px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" class=\"drag\" style=\"position:absolute;left:801px;top:689px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" class=\"drag\" style=\"position:absolute;left:735px;top:697px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" class=\"drag\" style=\"position:absolute;left:683px;top:781px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" class=\"drag\" style=\"position:absolute;left:781px;top:929px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KNOCK SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" class=\"drag\" style=\"position:absolute;left:755px;top:882px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" class=\"drag\" style=\"position:absolute;left:193px;top:881px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C42<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" class=\"drag\" style=\"position:absolute;left:193px;top:900px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" class=\"drag\" style=\"position:absolute;left:479px;top:938px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" class=\"drag\" style=\"position:absolute;left:271px;top:889px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" class=\"drag\" style=\"position:absolute;left:224px;top:987px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: A/T<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" class=\"drag\" style=\"position:absolute;left:835px;top:138px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" class=\"drag\" style=\"position:absolute;left:835px;top:157px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" class=\"drag\" style=\"position:absolute;left:647px;top:428px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" class=\"drag\" style=\"position:absolute;left:105px;top:90px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12 V<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}