with(document) {
write("<div id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\">");
write("<div id=\"rect8\"class=\"drag\" style=\"width:950px;position:relative;height:1103px;\">");
write("<img id=\"img8\" src=\"../img/SJD7EC0A20300000000EAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:829px;top:196px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:819px;top:149px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:195px;top:149px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A33<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:195px;top:165px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:819px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:195px;top:188px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:195px;top:204px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:747px;top:157px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:747px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:830px;top:320px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/C PRESSURE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:818px;top:227px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:195px;top:228px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:195px;top:244px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:747px;top:236px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:818px;top:258px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:195px;top:258px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:195px;top:275px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACPD<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:747px;top:267px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:818px;top:289px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:747px;top:298px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:194px;top:620px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A40<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:194px;top:637px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:376px;top:746px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:662px;top:739px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:193px;top:738px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A39<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:193px;top:754px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:496px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:758px;top:689px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: closed<br>Brake pedal released: open<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:759px;top:731px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: open<br>Brake pedal released: closed<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:662px;top:719px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:392px;top:597px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:662px;top:700px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:590px;top:708px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:662px;top:680px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:590px;top:688px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:366px;top:542px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:325px;top:452px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:296px;top:452px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:670px;top:655px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:194px;top:920px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C37<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" class=\"drag\" style=\"position:absolute;left:194px;top:936px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OILLVL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" class=\"drag\" style=\"position:absolute;left:268px;top:928px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" class=\"drag\" style=\"position:absolute;left:506px;top:898px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" class=\"drag\" style=\"position:absolute;left:740px;top:897px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" class=\"drag\" style=\"position:absolute;left:747px;top:960px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" class=\"drag\" style=\"position:absolute;left:820px;top:981px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ENGINE OIL <br>LEVEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" class=\"drag\" style=\"position:absolute;left:590px;top:1027px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" class=\"drag\" style=\"position:absolute;left:480px;top:1003px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" class=\"drag\" style=\"position:absolute;left:417px;top:708px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" class=\"drag\" style=\"position:absolute;left:818px;top:951px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" class=\"drag\" style=\"position:absolute;left:816px;top:920px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" class=\"drag\" style=\"position:absolute;left:817px;top:889px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" class=\"drag\" style=\"position:absolute;left:687px;top:888px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" class=\"drag\" style=\"position:absolute;left:238px;top:1027px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*3: RHD model<br>*4: LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p8_55\" class=\"drag\" style=\"position:absolute;left:345px;top:502px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_56\" class=\"drag\" style=\"position:absolute;left:629px;top:959px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_57\" class=\"drag\" style=\"position:absolute;left:617px;top:898px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_58\" class=\"drag\" style=\"position:absolute;left:678px;top:858px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_59\" class=\"drag\" style=\"position:absolute;left:688px;top:920px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_60\" class=\"drag\" style=\"position:absolute;left:483px;top:738px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_61\" class=\"drag\" style=\"position:absolute;left:687px;top:951px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_62\" class=\"drag\" style=\"position:absolute;left:748px;top:928px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_63\" class=\"drag\" style=\"position:absolute;left:598px;top:124px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_64\" class=\"drag\" style=\"position:absolute;left:302px;top:725px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br>(6)*3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_65\" class=\"drag\" style=\"position:absolute;left:564px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL (BRN)*4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_66\" class=\"drag\" style=\"position:absolute;left:547px;top:859px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_67\" class=\"drag\" style=\"position:absolute;left:258px;top:628px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_68\" class=\"drag\" style=\"position:absolute;left:410px;top:558px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_69\" class=\"drag\" style=\"position:absolute;left:381px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR<br>(17P CONNECTOR)*4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_70\" class=\"drag\" style=\"position:absolute;left:538px;top:811px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br>(13)*4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_71\" class=\"drag\" style=\"position:absolute;left:439px;top:431px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_72\" class=\"drag\" style=\"position:absolute;left:430px;top:336px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_73\" class=\"drag\" style=\"position:absolute;left:436px;top:589px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_74\" class=\"drag\" style=\"position:absolute;left:449px;top:397px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_75\" class=\"drag\" style=\"position:absolute;left:475px;top:365px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_76\" class=\"drag\" style=\"position:absolute;left:435px;top:619px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_77\" class=\"drag\" style=\"position:absolute;left:593px;top:746px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_78\" class=\"drag\" style=\"position:absolute;left:261px;top:745px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_79\" class=\"drag\" style=\"position:absolute;left:414px;top:688px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_80\" class=\"drag\" style=\"position:absolute;left:252px;top:317px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_81\" class=\"drag\" style=\"position:absolute;left:496px;top:404px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_82\" class=\"drag\" style=\"position:absolute;left:386px;top:406px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_83\" class=\"drag\" style=\"position:absolute;left:402px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_84\" class=\"drag\" style=\"position:absolute;left:354px;top:452px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_85\" class=\"drag\" style=\"position:absolute;left:522px;top:44px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_86\" class=\"drag\" style=\"position:absolute;left:516px;top:123px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br>(13)*4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_87\" class=\"drag\" style=\"position:absolute;left:462px;top:123px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br>(11)*4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_88\" class=\"drag\" style=\"position:absolute;left:300px;top:195px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_89\" class=\"drag\" style=\"position:absolute;left:280px;top:771px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR<br>(13P CONNECTOR)*3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_90\" class=\"drag\" style=\"position:absolute;left:477px;top:860px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_91\" class=\"drag\" style=\"position:absolute;left:445px;top:1003px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p8_92\" class=\"drag\" style=\"position:absolute;left:590px;top:889px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}