with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SJD7ECJA20300062951CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:204px;top:87px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VACUUM PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:349px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TURBOCHARGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:529px;top:62px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:709px;top:37px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TURBOCHARGER<br>BOOST CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:768px;top:389px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS<br>RECIRCULATION (EGR)<br>COOLER BYPASS<br>CONTROL SOLENOID <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:696px;top:899px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS<br>RECIRCULATION (EGR)<br>COOLER BYPASS VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:344px;top:972px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD RUNNER<br>CONTROL (IMRC) VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:77px;top:972px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT OF<br>VEHICLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:17px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS<br>RECIRCULATION (EGR)<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:16px;top:570px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS<br>RECIRCULATION (EGR)<br>CONTROL SOLENOID <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:3px;top:154px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD<br>RUNNER CONTROL (IMRC)<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}