with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:353px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:353px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0A14666300000KCAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:353px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:231px;top:322px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:240px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:319px;top:322px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:119px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:401px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:406px;top:321px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:38px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:125px;top:321px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:322px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:39px;top:321px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}