with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:369px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:475px;position:relative;height:369px;\">");
write("<img id=\"img1\" src=\"../img/SJD7EC0A14600000000KAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:369px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:39px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:404px;top:337px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:397px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:39px;top:337px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:321px;top:337px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:236px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:230px;top:337px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:321px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:124px;top:337px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:118px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}