with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SJD7ECJA20300062951CAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:234px;top:125px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:230px;top:214px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:89px;top:152px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:228px;top:436px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:135px;top:505px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:231px;top:545px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:478px;top:515px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:457px;top:492px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:548px;top:587px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:550px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:589px;top:512px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:531px;top:441px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:476px;top:440px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:467px;top:417px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:438px;top:392px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:619px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:686px;top:358px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:531px;top:308px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:625px;top:233px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:647px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:769px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:693px;top:207px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:740px;top:228px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:791px;top:165px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:858px;top:222px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:719px;top:161px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:817px;top:80px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:791px;top:210px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:159px;top:574px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:217px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:286px;top:518px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:182px;top:532px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:671px;top:430px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:733px;top:441px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:449px;top:593px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:422px;top:629px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:38px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VACUUM PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:38px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TURBOCHARGER BOOST CONTROL SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:38px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TURBOCHARGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:38px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WARM UP CATALYTIC CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:16px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:16px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:16px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:16px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:16px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:16px;top:784px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:15px;top:800px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:15px;top:831px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:16px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:16px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:16px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:16px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:16px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:15px;top:944px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:15px;top:959px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:15px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:15px;top:991px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:16px;top:1022px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:501px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:502px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:502px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:502px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:502px;top:800px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:502px;top:816px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:502px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:502px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:502px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:502px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:502px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:38px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AIR CLEANER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:38px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MASS AIR FLOW (MAF) SENSOR/<br>INTAKE AIR TEMPERATURE (IAT) SENSOR 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:38px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:38px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT POSITION (CMP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:38px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLOW PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:38px;top:944px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COOLANT TEMPERATURE (ECT) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:38px;top:959px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT POSITION (CKP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:38px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTER COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:38px;top:991px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) COOLER<br>BYPASS CONTROL SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:38px;top:1022px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) COOLER<br>BYPASS VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:524px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:524px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:524px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:524px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD RUNNER CONTROL (IMRC)<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:524px;top:800px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD RUNNER CONTROL (IMRC) VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:524px;top:816px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE PRESSURE (MAP) SENSOR/<br>INTAKE AIR TEMPERATURE (IAT) SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:502px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:524px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:524px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:524px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HAND PRIMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:524px;top:912px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RAIL PRESSURE (FRP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:524px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL HEATER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:524px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TEMPERATURE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:524px;top:943px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:524px;top:959px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILTER WATER LEVEL SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:524px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:524px;top:992px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:38px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS TEMPERATURE (EGT) SENSOR 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:38px;top:784px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS TEMPERATURE (EGT) SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:38px;top:800px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DIESEL PARTICULATE FILTER (DPF)<br>DIFFERENTIAL PRESSURE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:38px;top:831px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DIESEL PARTICULATE FILTER (DPF)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:524px;top:1007px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE SHUTTER VALVE (ISV)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:501px;top:943px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:502px;top:959px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:502px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(33)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:502px;top:991px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(34)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:501px;top:1007px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(35)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:524px;top:1024px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE OIL LEVEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:501px;top:1024px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(36)<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}