with(document) {
write("<div id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:735px;\">");
write("<div id=\"rect1\"class=\"drag\" style=\"width:950px;position:relative;height:735px;\">");
write("<img id=\"img1\" src=\"../img/SJD7ECJA20321200000CAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:735px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:414px;top:43px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:414px;top:77px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:492px;top:60px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:579px;top:42px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:579px;top:77px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:493px;top:95px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:579px;top:112px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:596px;top:129px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:508px;top:129px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:502px;top:147px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>LTBLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:416px;top:60px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:415px;top:130px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:415px;top:147px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:581px;top:146px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:513px;top:368px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:177px;top:602px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:700px;top:204px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:831px;top:184px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:792px;top:268px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:853px;top:314px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:759px;top:469px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:170px;top:634px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>LTBLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:694px;top:386px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:851px;top:94px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VARIOUS<br>SENSORS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:875px;top:443px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>From<br>ISV<br>CONTROL<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:719px;top:103px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:509px;top:271px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE SHUTTER<br>VALVE (ISV)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:287px;top:622px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGT<br>SENSOR 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:131px;top:685px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGT<br>SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:74px;top:656px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DPF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:42px;top:342px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DPF<br>DIFFERENTIAL<br>PRESSURE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:241px;top:667px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WARM UP<br>CATALYTIC<br>CONVERTER<br></b></nobr>");
write("</p>");
write("</div>");
write("</div>");
}